// @generated by fhir-codegen from usnistgov/igamt-hl7Tools-service 83322dffdac18cb129a1bd80149f5439cf5686fd src/main/resources/hl7db. DO NOT EDIT.
// Change the emitter (tools/fhir-codegen) and regenerate.
// SPDX-FileCopyrightText: Vernum Projecten B.V.
// SPDX-License-Identifier: Apache-2.0
//! The `MSA` segment: Message Acknowledgment.

use crate::model::{Cardinality, DataTypeRef, Field, Length, Max, Optionality, Segment, Table};

/// The `MSA` segment of the 2.5.1 tables.
pub static MSA: Segment = Segment {
    id: "MSA",
    url: None,
    name: "Message Acknowledgment",
    fields: &[
        Field {
            id: "MSA.1",
            position: 1,
            name: "Acknowledgment Code",
            data_type: Some(DataTypeRef::Legacy("ID")),
            cardinality: Cardinality {
                min: 1,
                max: Max::Bounded(1),
            },
            optionality: Optionality::R,
            length: Some(Length {
                min: 0,
                max: Some(2),
            }),
            conformance_length: None,
            table: Some(Table {
                id: "0008",
                value_set: "http://terminology.hl7.org/ValueSet/v2-0008",
            }),
            standards_status: None,
        },
        Field {
            id: "MSA.2",
            position: 2,
            name: "Message Control ID",
            data_type: Some(DataTypeRef::Legacy("ST")),
            cardinality: Cardinality {
                min: 1,
                max: Max::Bounded(1),
            },
            optionality: Optionality::R,
            length: Some(Length {
                min: 0,
                max: Some(20),
            }),
            conformance_length: None,
            table: None,
            standards_status: None,
        },
        Field {
            id: "MSA.3",
            position: 3,
            name: "Text Message",
            data_type: Some(DataTypeRef::Legacy("ST")),
            cardinality: Cardinality {
                min: 0,
                max: Max::Bounded(1),
            },
            optionality: Optionality::O,
            length: Some(Length {
                min: 0,
                max: Some(80),
            }),
            conformance_length: None,
            table: None,
            standards_status: None,
        },
        Field {
            id: "MSA.4",
            position: 4,
            name: "Expected Sequence Number",
            data_type: Some(DataTypeRef::Legacy("NM")),
            cardinality: Cardinality {
                min: 0,
                max: Max::Bounded(1),
            },
            optionality: Optionality::O,
            length: Some(Length {
                min: 0,
                max: Some(15),
            }),
            conformance_length: None,
            table: None,
            standards_status: None,
        },
        Field {
            id: "MSA.5",
            position: 5,
            name: "Delayed Acknowledgment Type",
            data_type: None,
            cardinality: Cardinality {
                min: 0,
                max: Max::Bounded(1),
            },
            optionality: Optionality::X,
            length: None,
            conformance_length: None,
            table: None,
            standards_status: None,
        },
        Field {
            id: "MSA.6",
            position: 6,
            name: "Error Condition",
            data_type: Some(DataTypeRef::Legacy("CE")),
            cardinality: Cardinality {
                min: 0,
                max: Max::Bounded(1),
            },
            optionality: Optionality::O,
            length: Some(Length {
                min: 0,
                max: Some(250),
            }),
            conformance_length: None,
            table: Some(Table {
                id: "0357",
                value_set: "http://terminology.hl7.org/ValueSet/v2-0357",
            }),
            standards_status: None,
        },
    ],
};
