// @generated by fhir-codegen from usnistgov/igamt-hl7Tools-service 83322dffdac18cb129a1bd80149f5439cf5686fd src/main/resources/hl7db. DO NOT EDIT.
// Change the emitter (tools/fhir-codegen) and regenerate.
// SPDX-FileCopyrightText: Vernum Projecten B.V.
// SPDX-License-Identifier: Apache-2.0
//! The `MFR_M01` message structure of the 2.4 tables, withdrawn as of 2.7.

use crate::model::{Cardinality, Group, GroupKind, Max, Node, Placeholder, SegmentRef, Structure};

/// The `MFR_M01` message structure of the 2.4 tables, withdrawn as of 2.7.
pub static MFR_M01: Structure = Structure {
    id: "MFR_M01",
    url: None,
    version: "2.4",
    withdrawn_as_of: Some("2.7"),
    nodes: &[
        Node::Segment(SegmentRef {
            id: "MFR_M01.1-MSH",
            position: 1,
            segment: &crate::legacy::v2_4::segment::msh::MSH,
            cardinality: Cardinality {
                min: 1,
                max: Max::Bounded(1),
            },
            status: None,
        }),
        Node::Segment(SegmentRef {
            id: "MFR_M01.2-MSA",
            position: 2,
            segment: &crate::legacy::v2_4::segment::msa::MSA,
            cardinality: Cardinality {
                min: 1,
                max: Max::Bounded(1),
            },
            status: None,
        }),
        Node::Segment(SegmentRef {
            id: "MFR_M01.3-ERR",
            position: 3,
            segment: &crate::legacy::v2_4::segment::err::ERR,
            cardinality: Cardinality {
                min: 0,
                max: Max::Bounded(1),
            },
            status: None,
        }),
        Node::Segment(SegmentRef {
            id: "MFR_M01.4-QAK",
            position: 4,
            segment: &crate::legacy::v2_4::segment::qak::QAK,
            cardinality: Cardinality {
                min: 0,
                max: Max::Bounded(1),
            },
            status: None,
        }),
        Node::Segment(SegmentRef {
            id: "MFR_M01.5-QRD",
            position: 5,
            segment: &crate::legacy::v2_4::segment::qrd::QRD,
            cardinality: Cardinality {
                min: 1,
                max: Max::Bounded(1),
            },
            status: None,
        }),
        Node::Segment(SegmentRef {
            id: "MFR_M01.6-QRF",
            position: 6,
            segment: &crate::legacy::v2_4::segment::qrf::QRF,
            cardinality: Cardinality {
                min: 0,
                max: Max::Bounded(1),
            },
            status: None,
        }),
        Node::Segment(SegmentRef {
            id: "MFR_M01.7-MFI",
            position: 7,
            segment: &crate::legacy::v2_4::segment::mfi::MFI,
            cardinality: Cardinality {
                min: 1,
                max: Max::Bounded(1),
            },
            status: None,
        }),
        Node::Group(Group {
            id: "MFR_M01.8-MF_QUERY",
            position: 8,
            name: "MF_QUERY",
            cardinality: Cardinality {
                min: 1,
                max: Max::Unbounded,
            },
            kind: GroupKind::Sequence,
            children: &[
                Node::Segment(SegmentRef {
                    id: "MFR_M01.8-MF_QUERY.1-MFE",
                    position: 1,
                    segment: &crate::legacy::v2_4::segment::mfe::MFE,
                    cardinality: Cardinality {
                        min: 1,
                        max: Max::Bounded(1),
                    },
                    status: None,
                }),
                Node::Placeholder(Placeholder {
                    id: "MFR_M01.8-MF_QUERY.2-Zxx",
                    position: 2,
                    cardinality: Cardinality {
                        min: 0,
                        max: Max::Bounded(1),
                    },
                }),
                Node::Segment(SegmentRef {
                    id: "MFR_M01.8-MF_QUERY.3-DSC",
                    position: 3,
                    segment: &crate::segment::dsc::DSC,
                    cardinality: Cardinality {
                        min: 0,
                        max: Max::Bounded(1),
                    },
                    status: None,
                }),
            ],
        }),
    ],
};
