// @generated by fhir-codegen from usnistgov/igamt-hl7Tools-service 83322dffdac18cb129a1bd80149f5439cf5686fd src/main/resources/hl7db. DO NOT EDIT.
// Change the emitter (tools/fhir-codegen) and regenerate.
// SPDX-FileCopyrightText: Vernum Projecten B.V.
// SPDX-License-Identifier: Apache-2.0
//! The `ADT_A05` message structure of the 2.5.1 tables.

use crate::model::{Cardinality, Group, GroupKind, Max, Node, SegmentRef, Structure};

/// The top-level nodes of [`ADT_A05`], one `static` so a structure with the same tree links to it.
pub static ADT_A05_NODES: [Node; 21] = [
    Node::Segment(SegmentRef {
        id: "ADT_A05.1-MSH",
        position: 1,
        segment: &crate::legacy::v2_5::segment::msh::MSH,
        cardinality: Cardinality {
            min: 1,
            max: Max::Bounded(1),
        },
        status: None,
    }),
    Node::Segment(SegmentRef {
        id: "ADT_A05.2-SFT",
        position: 2,
        segment: &crate::legacy::v2_5::segment::sft::SFT,
        cardinality: Cardinality {
            min: 0,
            max: Max::Unbounded,
        },
        status: None,
    }),
    Node::Segment(SegmentRef {
        id: "ADT_A05.3-EVN",
        position: 3,
        segment: &crate::legacy::v2_5::segment::evn::EVN,
        cardinality: Cardinality {
            min: 1,
            max: Max::Bounded(1),
        },
        status: None,
    }),
    Node::Segment(SegmentRef {
        id: "ADT_A05.4-PID",
        position: 4,
        segment: &crate::legacy::v2_5_1::segment::pid::PID,
        cardinality: Cardinality {
            min: 1,
            max: Max::Bounded(1),
        },
        status: None,
    }),
    Node::Segment(SegmentRef {
        id: "ADT_A05.5-PD1",
        position: 5,
        segment: &crate::legacy::v2_5::segment::pd1::PD1,
        cardinality: Cardinality {
            min: 0,
            max: Max::Bounded(1),
        },
        status: None,
    }),
    Node::Segment(SegmentRef {
        id: "ADT_A05.6-ROL",
        position: 6,
        segment: &crate::legacy::v2_5::segment::rol::ROL,
        cardinality: Cardinality {
            min: 0,
            max: Max::Unbounded,
        },
        status: None,
    }),
    Node::Segment(SegmentRef {
        id: "ADT_A05.7-NK1",
        position: 7,
        segment: &crate::legacy::v2_5_1::segment::nk1::NK1,
        cardinality: Cardinality {
            min: 0,
            max: Max::Unbounded,
        },
        status: None,
    }),
    Node::Segment(SegmentRef {
        id: "ADT_A05.8-PV1",
        position: 8,
        segment: &crate::legacy::v2_5::segment::pv1::PV1,
        cardinality: Cardinality {
            min: 1,
            max: Max::Bounded(1),
        },
        status: None,
    }),
    Node::Segment(SegmentRef {
        id: "ADT_A05.9-PV2",
        position: 9,
        segment: &crate::legacy::v2_5::segment::pv2::PV2,
        cardinality: Cardinality {
            min: 0,
            max: Max::Bounded(1),
        },
        status: None,
    }),
    Node::Segment(SegmentRef {
        id: "ADT_A05.10-ROL",
        position: 10,
        segment: &crate::legacy::v2_5::segment::rol::ROL,
        cardinality: Cardinality {
            min: 0,
            max: Max::Unbounded,
        },
        status: None,
    }),
    Node::Segment(SegmentRef {
        id: "ADT_A05.11-DB1",
        position: 11,
        segment: &crate::legacy::v2_5::segment::db1::DB1,
        cardinality: Cardinality {
            min: 0,
            max: Max::Unbounded,
        },
        status: None,
    }),
    Node::Segment(SegmentRef {
        id: "ADT_A05.12-OBX",
        position: 12,
        segment: &crate::legacy::v2_5_1::segment::obx::OBX,
        cardinality: Cardinality {
            min: 0,
            max: Max::Unbounded,
        },
        status: None,
    }),
    Node::Segment(SegmentRef {
        id: "ADT_A05.13-AL1",
        position: 13,
        segment: &crate::legacy::v2_5::segment::al1::AL1,
        cardinality: Cardinality {
            min: 0,
            max: Max::Unbounded,
        },
        status: None,
    }),
    Node::Segment(SegmentRef {
        id: "ADT_A05.14-DG1",
        position: 14,
        segment: &crate::legacy::v2_5::segment::dg1::DG1,
        cardinality: Cardinality {
            min: 0,
            max: Max::Unbounded,
        },
        status: None,
    }),
    Node::Segment(SegmentRef {
        id: "ADT_A05.15-DRG",
        position: 15,
        segment: &crate::legacy::v2_5::segment::drg::DRG,
        cardinality: Cardinality {
            min: 0,
            max: Max::Bounded(1),
        },
        status: None,
    }),
    Node::Group(Group {
        id: "ADT_A05.16-PROCEDURE",
        position: 16,
        name: "PROCEDURE",
        cardinality: Cardinality {
            min: 0,
            max: Max::Unbounded,
        },
        kind: GroupKind::Sequence,
        children: &[
            Node::Segment(SegmentRef {
                id: "ADT_A05.16-PROCEDURE.1-PR1",
                position: 1,
                segment: &crate::legacy::v2_5::segment::pr1::PR1,
                cardinality: Cardinality {
                    min: 1,
                    max: Max::Bounded(1),
                },
                status: None,
            }),
            Node::Segment(SegmentRef {
                id: "ADT_A05.16-PROCEDURE.2-ROL",
                position: 2,
                segment: &crate::legacy::v2_5::segment::rol::ROL,
                cardinality: Cardinality {
                    min: 0,
                    max: Max::Unbounded,
                },
                status: None,
            }),
        ],
    }),
    Node::Segment(SegmentRef {
        id: "ADT_A05.17-GT1",
        position: 17,
        segment: &crate::legacy::v2_5::segment::gt1::GT1,
        cardinality: Cardinality {
            min: 0,
            max: Max::Unbounded,
        },
        status: None,
    }),
    Node::Group(Group {
        id: "ADT_A05.18-INSURANCE",
        position: 18,
        name: "INSURANCE",
        cardinality: Cardinality {
            min: 0,
            max: Max::Unbounded,
        },
        kind: GroupKind::Sequence,
        children: &[
            Node::Segment(SegmentRef {
                id: "ADT_A05.18-INSURANCE.1-IN1",
                position: 1,
                segment: &crate::legacy::v2_5::segment::in1::IN1,
                cardinality: Cardinality {
                    min: 1,
                    max: Max::Bounded(1),
                },
                status: None,
            }),
            Node::Segment(SegmentRef {
                id: "ADT_A05.18-INSURANCE.2-IN2",
                position: 2,
                segment: &crate::legacy::v2_5_1::segment::in2::IN2,
                cardinality: Cardinality {
                    min: 0,
                    max: Max::Bounded(1),
                },
                status: None,
            }),
            Node::Segment(SegmentRef {
                id: "ADT_A05.18-INSURANCE.3-IN3",
                position: 3,
                segment: &crate::legacy::v2_5::segment::in3::IN3,
                cardinality: Cardinality {
                    min: 0,
                    max: Max::Unbounded,
                },
                status: None,
            }),
            Node::Segment(SegmentRef {
                id: "ADT_A05.18-INSURANCE.4-ROL",
                position: 4,
                segment: &crate::legacy::v2_5::segment::rol::ROL,
                cardinality: Cardinality {
                    min: 0,
                    max: Max::Unbounded,
                },
                status: None,
            }),
        ],
    }),
    Node::Segment(SegmentRef {
        id: "ADT_A05.19-ACC",
        position: 19,
        segment: &crate::legacy::v2_5::segment::acc::ACC,
        cardinality: Cardinality {
            min: 0,
            max: Max::Bounded(1),
        },
        status: None,
    }),
    Node::Segment(SegmentRef {
        id: "ADT_A05.20-UB1",
        position: 20,
        segment: &crate::legacy::v2_5_1::segment::ub1::UB1,
        cardinality: Cardinality {
            min: 0,
            max: Max::Bounded(1),
        },
        status: None,
    }),
    Node::Segment(SegmentRef {
        id: "ADT_A05.21-UB2",
        position: 21,
        segment: &crate::legacy::v2_5_1::segment::ub2::UB2,
        cardinality: Cardinality {
            min: 0,
            max: Max::Bounded(1),
        },
        status: None,
    }),
];

/// The `ADT_A05` message structure of the 2.5.1 tables.
pub static ADT_A05: Structure = Structure {
    id: "ADT_A05",
    url: None,
    version: "2.5.1",
    withdrawn_as_of: None,
    nodes: &ADT_A05_NODES,
};
