// @generated by fhir-codegen from usnistgov/igamt-hl7Tools-service 83322dffdac18cb129a1bd80149f5439cf5686fd src/main/resources/hl7db. DO NOT EDIT.
// Change the emitter (tools/fhir-codegen) and regenerate.
// SPDX-FileCopyrightText: Vernum Projecten B.V.
// SPDX-License-Identifier: Apache-2.0
//! The `BAR_P02` message structure of the 2.5.1 tables.

use crate::model::{Cardinality, Group, GroupKind, Max, Node, SegmentRef, Structure};

/// The top-level nodes of [`BAR_P02`], one `static` so a structure with the same tree links to it.
pub static BAR_P02_NODES: [Node; 4] = [
    Node::Segment(SegmentRef {
        id: "BAR_P02.1-MSH",
        position: 1,
        segment: &crate::legacy::v2_5::segment::msh::MSH,
        cardinality: Cardinality {
            min: 1,
            max: Max::Bounded(1),
        },
        status: None,
    }),
    Node::Segment(SegmentRef {
        id: "BAR_P02.2-SFT",
        position: 2,
        segment: &crate::legacy::v2_5::segment::sft::SFT,
        cardinality: Cardinality {
            min: 0,
            max: Max::Unbounded,
        },
        status: None,
    }),
    Node::Segment(SegmentRef {
        id: "BAR_P02.3-EVN",
        position: 3,
        segment: &crate::legacy::v2_5::segment::evn::EVN,
        cardinality: Cardinality {
            min: 1,
            max: Max::Bounded(1),
        },
        status: None,
    }),
    Node::Group(Group {
        id: "BAR_P02.4-PATIENT",
        position: 4,
        name: "PATIENT",
        cardinality: Cardinality {
            min: 1,
            max: Max::Unbounded,
        },
        kind: GroupKind::Sequence,
        children: &[
            Node::Segment(SegmentRef {
                id: "BAR_P02.4-PATIENT.1-PID",
                position: 1,
                segment: &crate::legacy::v2_5_1::segment::pid::PID,
                cardinality: Cardinality {
                    min: 1,
                    max: Max::Bounded(1),
                },
                status: None,
            }),
            Node::Segment(SegmentRef {
                id: "BAR_P02.4-PATIENT.2-PD1",
                position: 2,
                segment: &crate::legacy::v2_5::segment::pd1::PD1,
                cardinality: Cardinality {
                    min: 0,
                    max: Max::Bounded(1),
                },
                status: None,
            }),
            Node::Segment(SegmentRef {
                id: "BAR_P02.4-PATIENT.3-PV1",
                position: 3,
                segment: &crate::legacy::v2_5::segment::pv1::PV1,
                cardinality: Cardinality {
                    min: 0,
                    max: Max::Bounded(1),
                },
                status: None,
            }),
            Node::Segment(SegmentRef {
                id: "BAR_P02.4-PATIENT.4-DB1",
                position: 4,
                segment: &crate::legacy::v2_5::segment::db1::DB1,
                cardinality: Cardinality {
                    min: 0,
                    max: Max::Unbounded,
                },
                status: None,
            }),
        ],
    }),
];

/// The `BAR_P02` message structure of the 2.5.1 tables.
pub static BAR_P02: Structure = Structure {
    id: "BAR_P02",
    url: None,
    version: "2.5.1",
    withdrawn_as_of: None,
    nodes: &BAR_P02_NODES,
};
