// @generated by fhir-codegen from usnistgov/igamt-hl7Tools-service 83322dffdac18cb129a1bd80149f5439cf5686fd src/main/resources/hl7db. DO NOT EDIT.
// Change the emitter (tools/fhir-codegen) and regenerate.
// SPDX-FileCopyrightText: Vernum Projecten B.V.
// SPDX-License-Identifier: Apache-2.0
//! The `ORU_R01` message structure of the 2.5.1 tables.

use crate::model::{Cardinality, Group, GroupKind, Max, Node, SegmentRef, Structure};

/// The top-level nodes of [`ORU_R01`], one `static` so a structure with the same tree links to it.
pub static ORU_R01_NODES: [Node; 4] = [
    Node::Segment(SegmentRef {
        id: "ORU_R01.1-MSH",
        position: 1,
        segment: &crate::legacy::v2_5::segment::msh::MSH,
        cardinality: Cardinality {
            min: 1,
            max: Max::Bounded(1),
        },
        status: None,
    }),
    Node::Segment(SegmentRef {
        id: "ORU_R01.2-SFT",
        position: 2,
        segment: &crate::legacy::v2_5::segment::sft::SFT,
        cardinality: Cardinality {
            min: 0,
            max: Max::Unbounded,
        },
        status: None,
    }),
    Node::Group(Group {
        id: "ORU_R01.3-PATIENT_RESULT",
        position: 3,
        name: "PATIENT_RESULT",
        cardinality: Cardinality {
            min: 1,
            max: Max::Unbounded,
        },
        kind: GroupKind::Sequence,
        children: &[
            Node::Group(Group {
                id: "ORU_R01.3-PATIENT_RESULT.1-PATIENT",
                position: 1,
                name: "PATIENT",
                cardinality: Cardinality {
                    min: 0,
                    max: Max::Bounded(1),
                },
                kind: GroupKind::Sequence,
                children: &[
                    Node::Segment(SegmentRef {
                        id: "ORU_R01.3-PATIENT_RESULT.1-PATIENT.1-PID",
                        position: 1,
                        segment: &crate::legacy::v2_5_1::segment::pid::PID,
                        cardinality: Cardinality {
                            min: 1,
                            max: Max::Bounded(1),
                        },
                        status: None,
                    }),
                    Node::Segment(SegmentRef {
                        id: "ORU_R01.3-PATIENT_RESULT.1-PATIENT.2-PD1",
                        position: 2,
                        segment: &crate::legacy::v2_5::segment::pd1::PD1,
                        cardinality: Cardinality {
                            min: 0,
                            max: Max::Bounded(1),
                        },
                        status: None,
                    }),
                    Node::Segment(SegmentRef {
                        id: "ORU_R01.3-PATIENT_RESULT.1-PATIENT.3-NTE",
                        position: 3,
                        segment: &crate::legacy::v2_5::segment::nte::NTE,
                        cardinality: Cardinality {
                            min: 0,
                            max: Max::Unbounded,
                        },
                        status: None,
                    }),
                    Node::Segment(SegmentRef {
                        id: "ORU_R01.3-PATIENT_RESULT.1-PATIENT.4-NK1",
                        position: 4,
                        segment: &crate::legacy::v2_5_1::segment::nk1::NK1,
                        cardinality: Cardinality {
                            min: 0,
                            max: Max::Unbounded,
                        },
                        status: None,
                    }),
                    Node::Group(Group {
                        id: "ORU_R01.3-PATIENT_RESULT.1-PATIENT.5-VISIT",
                        position: 5,
                        name: "VISIT",
                        cardinality: Cardinality {
                            min: 0,
                            max: Max::Bounded(1),
                        },
                        kind: GroupKind::Sequence,
                        children: &[
                            Node::Segment(SegmentRef {
                                id: "ORU_R01.3-PATIENT_RESULT.1-PATIENT.5-VISIT.1-PV1",
                                position: 1,
                                segment: &crate::legacy::v2_5::segment::pv1::PV1,
                                cardinality: Cardinality {
                                    min: 1,
                                    max: Max::Bounded(1),
                                },
                                status: None,
                            }),
                            Node::Segment(SegmentRef {
                                id: "ORU_R01.3-PATIENT_RESULT.1-PATIENT.5-VISIT.2-PV2",
                                position: 2,
                                segment: &crate::legacy::v2_5::segment::pv2::PV2,
                                cardinality: Cardinality {
                                    min: 0,
                                    max: Max::Bounded(1),
                                },
                                status: None,
                            }),
                        ],
                    }),
                ],
            }),
            Node::Group(Group {
                id: "ORU_R01.3-PATIENT_RESULT.2-ORDER_OBSERVATION",
                position: 2,
                name: "ORDER_OBSERVATION",
                cardinality: Cardinality {
                    min: 1,
                    max: Max::Unbounded,
                },
                kind: GroupKind::Sequence,
                children: &[
                    Node::Segment(SegmentRef {
                        id: "ORU_R01.3-PATIENT_RESULT.2-ORDER_OBSERVATION.1-ORC",
                        position: 1,
                        segment: &crate::legacy::v2_5_1::segment::orc::ORC,
                        cardinality: Cardinality {
                            min: 0,
                            max: Max::Bounded(1),
                        },
                        status: None,
                    }),
                    Node::Segment(SegmentRef {
                        id: "ORU_R01.3-PATIENT_RESULT.2-ORDER_OBSERVATION.2-OBR",
                        position: 2,
                        segment: &crate::legacy::v2_5_1::segment::obr::OBR,
                        cardinality: Cardinality {
                            min: 1,
                            max: Max::Bounded(1),
                        },
                        status: None,
                    }),
                    Node::Segment(SegmentRef {
                        id: "ORU_R01.3-PATIENT_RESULT.2-ORDER_OBSERVATION.3-NTE",
                        position: 3,
                        segment: &crate::legacy::v2_5::segment::nte::NTE,
                        cardinality: Cardinality {
                            min: 0,
                            max: Max::Unbounded,
                        },
                        status: None,
                    }),
                    Node::Group(Group {
                        id: "ORU_R01.3-PATIENT_RESULT.2-ORDER_OBSERVATION.4-TIMING_QTY",
                        position: 4,
                        name: "TIMING_QTY",
                        cardinality: Cardinality {
                            min: 0,
                            max: Max::Unbounded,
                        },
                        kind: GroupKind::Sequence,
                        children: &[
                            Node::Segment(SegmentRef {
                                id: "ORU_R01.3-PATIENT_RESULT.2-ORDER_OBSERVATION.4-TIMING_QTY.1-TQ1",
                                position: 1,
                                segment: &crate::legacy::v2_5::segment::tq1::TQ1,
                                cardinality: Cardinality {
                                    min: 1,
                                    max: Max::Bounded(1),
                                },
                                status: None,
                            }),
                            Node::Segment(SegmentRef {
                                id: "ORU_R01.3-PATIENT_RESULT.2-ORDER_OBSERVATION.4-TIMING_QTY.2-TQ2",
                                position: 2,
                                segment: &crate::segment::tq2::TQ2,
                                cardinality: Cardinality {
                                    min: 0,
                                    max: Max::Unbounded,
                                },
                                status: None,
                            }),
                        ],
                    }),
                    Node::Segment(SegmentRef {
                        id: "ORU_R01.3-PATIENT_RESULT.2-ORDER_OBSERVATION.5-CTD",
                        position: 5,
                        segment: &crate::legacy::v2_5::segment::ctd::CTD,
                        cardinality: Cardinality {
                            min: 0,
                            max: Max::Bounded(1),
                        },
                        status: None,
                    }),
                    Node::Group(Group {
                        id: "ORU_R01.3-PATIENT_RESULT.2-ORDER_OBSERVATION.6-OBSERVATION",
                        position: 6,
                        name: "OBSERVATION",
                        cardinality: Cardinality {
                            min: 0,
                            max: Max::Unbounded,
                        },
                        kind: GroupKind::Sequence,
                        children: &[
                            Node::Segment(SegmentRef {
                                id: "ORU_R01.3-PATIENT_RESULT.2-ORDER_OBSERVATION.6-OBSERVATION.1-OBX",
                                position: 1,
                                segment: &crate::legacy::v2_5_1::segment::obx::OBX,
                                cardinality: Cardinality {
                                    min: 1,
                                    max: Max::Bounded(1),
                                },
                                status: None,
                            }),
                            Node::Segment(SegmentRef {
                                id: "ORU_R01.3-PATIENT_RESULT.2-ORDER_OBSERVATION.6-OBSERVATION.2-NTE",
                                position: 2,
                                segment: &crate::legacy::v2_5::segment::nte::NTE,
                                cardinality: Cardinality {
                                    min: 0,
                                    max: Max::Unbounded,
                                },
                                status: None,
                            }),
                        ],
                    }),
                    Node::Segment(SegmentRef {
                        id: "ORU_R01.3-PATIENT_RESULT.2-ORDER_OBSERVATION.7-FT1",
                        position: 7,
                        segment: &crate::legacy::v2_5::segment::ft1::FT1,
                        cardinality: Cardinality {
                            min: 0,
                            max: Max::Unbounded,
                        },
                        status: None,
                    }),
                    Node::Segment(SegmentRef {
                        id: "ORU_R01.3-PATIENT_RESULT.2-ORDER_OBSERVATION.8-CTI",
                        position: 8,
                        segment: &crate::legacy::v2_5::segment::cti::CTI,
                        cardinality: Cardinality {
                            min: 0,
                            max: Max::Unbounded,
                        },
                        status: None,
                    }),
                    Node::Group(Group {
                        id: "ORU_R01.3-PATIENT_RESULT.2-ORDER_OBSERVATION.9-SPECIMEN",
                        position: 9,
                        name: "SPECIMEN",
                        cardinality: Cardinality {
                            min: 0,
                            max: Max::Unbounded,
                        },
                        kind: GroupKind::Sequence,
                        children: &[
                            Node::Segment(SegmentRef {
                                id: "ORU_R01.3-PATIENT_RESULT.2-ORDER_OBSERVATION.9-SPECIMEN.1-SPM",
                                position: 1,
                                segment: &crate::legacy::v2_5::segment::spm::SPM,
                                cardinality: Cardinality {
                                    min: 1,
                                    max: Max::Bounded(1),
                                },
                                status: None,
                            }),
                            Node::Segment(SegmentRef {
                                id: "ORU_R01.3-PATIENT_RESULT.2-ORDER_OBSERVATION.9-SPECIMEN.2-OBX",
                                position: 2,
                                segment: &crate::legacy::v2_5_1::segment::obx::OBX,
                                cardinality: Cardinality {
                                    min: 0,
                                    max: Max::Unbounded,
                                },
                                status: None,
                            }),
                        ],
                    }),
                ],
            }),
        ],
    }),
    Node::Segment(SegmentRef {
        id: "ORU_R01.4-DSC",
        position: 4,
        segment: &crate::segment::dsc::DSC,
        cardinality: Cardinality {
            min: 0,
            max: Max::Bounded(1),
        },
        status: None,
    }),
];

/// The `ORU_R01` message structure of the 2.5.1 tables.
pub static ORU_R01: Structure = Structure {
    id: "ORU_R01",
    url: None,
    version: "2.5.1",
    withdrawn_as_of: None,
    nodes: &ORU_R01_NODES,
};
