// @generated by fhir-codegen from usnistgov/igamt-hl7Tools-service 83322dffdac18cb129a1bd80149f5439cf5686fd src/main/resources/hl7db. DO NOT EDIT.
// Change the emitter (tools/fhir-codegen) and regenerate.
// SPDX-FileCopyrightText: Vernum Projecten B.V.
// SPDX-License-Identifier: Apache-2.0
//! The `RRI_I12` message structure of the 2.5.1 tables.

use crate::model::{Cardinality, Group, GroupKind, Max, Node, SegmentRef, Structure};

/// The top-level nodes of [`RRI_I12`], one `static` so a structure with the same tree links to it.
pub static RRI_I12_NODES: [Node; 15] = [
    Node::Segment(SegmentRef {
        id: "RRI_I12.1-MSH",
        position: 1,
        segment: &crate::legacy::v2_5::segment::msh::MSH,
        cardinality: Cardinality {
            min: 1,
            max: Max::Bounded(1),
        },
        status: None,
    }),
    Node::Segment(SegmentRef {
        id: "RRI_I12.2-SFT",
        position: 2,
        segment: &crate::legacy::v2_5::segment::sft::SFT,
        cardinality: Cardinality {
            min: 0,
            max: Max::Unbounded,
        },
        status: None,
    }),
    Node::Segment(SegmentRef {
        id: "RRI_I12.3-MSA",
        position: 3,
        segment: &crate::legacy::v2_5_1::segment::msa::MSA,
        cardinality: Cardinality {
            min: 0,
            max: Max::Bounded(1),
        },
        status: None,
    }),
    Node::Segment(SegmentRef {
        id: "RRI_I12.4-RF1",
        position: 4,
        segment: &crate::legacy::v2_5::segment::rf1::RF1,
        cardinality: Cardinality {
            min: 0,
            max: Max::Bounded(1),
        },
        status: None,
    }),
    Node::Group(Group {
        id: "RRI_I12.5-AUTHORIZATION_CONTACT",
        position: 5,
        name: "AUTHORIZATION_CONTACT",
        cardinality: Cardinality {
            min: 0,
            max: Max::Bounded(1),
        },
        kind: GroupKind::Sequence,
        children: &[
            Node::Segment(SegmentRef {
                id: "RRI_I12.5-AUTHORIZATION_CONTACT.1-AUT",
                position: 1,
                segment: &crate::legacy::v2_5::segment::aut::AUT,
                cardinality: Cardinality {
                    min: 1,
                    max: Max::Bounded(1),
                },
                status: None,
            }),
            Node::Segment(SegmentRef {
                id: "RRI_I12.5-AUTHORIZATION_CONTACT.2-CTD",
                position: 2,
                segment: &crate::legacy::v2_5::segment::ctd::CTD,
                cardinality: Cardinality {
                    min: 0,
                    max: Max::Bounded(1),
                },
                status: None,
            }),
        ],
    }),
    Node::Group(Group {
        id: "RRI_I12.6-PROVIDER_CONTACT",
        position: 6,
        name: "PROVIDER_CONTACT",
        cardinality: Cardinality {
            min: 1,
            max: Max::Unbounded,
        },
        kind: GroupKind::Sequence,
        children: &[
            Node::Segment(SegmentRef {
                id: "RRI_I12.6-PROVIDER_CONTACT.1-PRD",
                position: 1,
                segment: &crate::legacy::v2_5::segment::prd::PRD,
                cardinality: Cardinality {
                    min: 1,
                    max: Max::Bounded(1),
                },
                status: None,
            }),
            Node::Segment(SegmentRef {
                id: "RRI_I12.6-PROVIDER_CONTACT.2-CTD",
                position: 2,
                segment: &crate::legacy::v2_5::segment::ctd::CTD,
                cardinality: Cardinality {
                    min: 0,
                    max: Max::Unbounded,
                },
                status: None,
            }),
        ],
    }),
    Node::Segment(SegmentRef {
        id: "RRI_I12.7-PID",
        position: 7,
        segment: &crate::legacy::v2_5_1::segment::pid::PID,
        cardinality: Cardinality {
            min: 1,
            max: Max::Bounded(1),
        },
        status: None,
    }),
    Node::Segment(SegmentRef {
        id: "RRI_I12.8-ACC",
        position: 8,
        segment: &crate::legacy::v2_5::segment::acc::ACC,
        cardinality: Cardinality {
            min: 0,
            max: Max::Bounded(1),
        },
        status: None,
    }),
    Node::Segment(SegmentRef {
        id: "RRI_I12.9-DG1",
        position: 9,
        segment: &crate::legacy::v2_5::segment::dg1::DG1,
        cardinality: Cardinality {
            min: 0,
            max: Max::Unbounded,
        },
        status: None,
    }),
    Node::Segment(SegmentRef {
        id: "RRI_I12.10-DRG",
        position: 10,
        segment: &crate::legacy::v2_5::segment::drg::DRG,
        cardinality: Cardinality {
            min: 0,
            max: Max::Unbounded,
        },
        status: None,
    }),
    Node::Segment(SegmentRef {
        id: "RRI_I12.11-AL1",
        position: 11,
        segment: &crate::legacy::v2_5::segment::al1::AL1,
        cardinality: Cardinality {
            min: 0,
            max: Max::Unbounded,
        },
        status: None,
    }),
    Node::Group(Group {
        id: "RRI_I12.12-PROCEDURE",
        position: 12,
        name: "PROCEDURE",
        cardinality: Cardinality {
            min: 0,
            max: Max::Unbounded,
        },
        kind: GroupKind::Sequence,
        children: &[
            Node::Segment(SegmentRef {
                id: "RRI_I12.12-PROCEDURE.1-PR1",
                position: 1,
                segment: &crate::legacy::v2_5::segment::pr1::PR1,
                cardinality: Cardinality {
                    min: 1,
                    max: Max::Bounded(1),
                },
                status: None,
            }),
            Node::Group(Group {
                id: "RRI_I12.12-PROCEDURE.2-AUTHORIZATION_CONTACT",
                position: 2,
                name: "AUTHORIZATION_CONTACT",
                cardinality: Cardinality {
                    min: 0,
                    max: Max::Bounded(1),
                },
                kind: GroupKind::Sequence,
                children: &[
                    Node::Segment(SegmentRef {
                        id: "RRI_I12.12-PROCEDURE.2-AUTHORIZATION_CONTACT.1-AUT",
                        position: 1,
                        segment: &crate::legacy::v2_5::segment::aut::AUT,
                        cardinality: Cardinality {
                            min: 1,
                            max: Max::Bounded(1),
                        },
                        status: None,
                    }),
                    Node::Segment(SegmentRef {
                        id: "RRI_I12.12-PROCEDURE.2-AUTHORIZATION_CONTACT.2-CTD",
                        position: 2,
                        segment: &crate::legacy::v2_5::segment::ctd::CTD,
                        cardinality: Cardinality {
                            min: 0,
                            max: Max::Bounded(1),
                        },
                        status: None,
                    }),
                ],
            }),
        ],
    }),
    Node::Group(Group {
        id: "RRI_I12.13-OBSERVATION",
        position: 13,
        name: "OBSERVATION",
        cardinality: Cardinality {
            min: 0,
            max: Max::Unbounded,
        },
        kind: GroupKind::Sequence,
        children: &[
            Node::Segment(SegmentRef {
                id: "RRI_I12.13-OBSERVATION.1-OBR",
                position: 1,
                segment: &crate::legacy::v2_5_1::segment::obr::OBR,
                cardinality: Cardinality {
                    min: 1,
                    max: Max::Bounded(1),
                },
                status: None,
            }),
            Node::Segment(SegmentRef {
                id: "RRI_I12.13-OBSERVATION.2-NTE",
                position: 2,
                segment: &crate::legacy::v2_5::segment::nte::NTE,
                cardinality: Cardinality {
                    min: 0,
                    max: Max::Unbounded,
                },
                status: None,
            }),
            Node::Group(Group {
                id: "RRI_I12.13-OBSERVATION.3-RESULTS_NOTES",
                position: 3,
                name: "RESULTS_NOTES",
                cardinality: Cardinality {
                    min: 0,
                    max: Max::Unbounded,
                },
                kind: GroupKind::Sequence,
                children: &[
                    Node::Segment(SegmentRef {
                        id: "RRI_I12.13-OBSERVATION.3-RESULTS_NOTES.1-OBX",
                        position: 1,
                        segment: &crate::legacy::v2_5_1::segment::obx::OBX,
                        cardinality: Cardinality {
                            min: 1,
                            max: Max::Bounded(1),
                        },
                        status: None,
                    }),
                    Node::Segment(SegmentRef {
                        id: "RRI_I12.13-OBSERVATION.3-RESULTS_NOTES.2-NTE",
                        position: 2,
                        segment: &crate::legacy::v2_5::segment::nte::NTE,
                        cardinality: Cardinality {
                            min: 0,
                            max: Max::Unbounded,
                        },
                        status: None,
                    }),
                ],
            }),
        ],
    }),
    Node::Group(Group {
        id: "RRI_I12.14-PATIENT_VISIT",
        position: 14,
        name: "PATIENT_VISIT",
        cardinality: Cardinality {
            min: 0,
            max: Max::Bounded(1),
        },
        kind: GroupKind::Sequence,
        children: &[
            Node::Segment(SegmentRef {
                id: "RRI_I12.14-PATIENT_VISIT.1-PV1",
                position: 1,
                segment: &crate::legacy::v2_5::segment::pv1::PV1,
                cardinality: Cardinality {
                    min: 1,
                    max: Max::Bounded(1),
                },
                status: None,
            }),
            Node::Segment(SegmentRef {
                id: "RRI_I12.14-PATIENT_VISIT.2-PV2",
                position: 2,
                segment: &crate::legacy::v2_5::segment::pv2::PV2,
                cardinality: Cardinality {
                    min: 0,
                    max: Max::Bounded(1),
                },
                status: None,
            }),
        ],
    }),
    Node::Segment(SegmentRef {
        id: "RRI_I12.15-NTE",
        position: 15,
        segment: &crate::legacy::v2_5::segment::nte::NTE,
        cardinality: Cardinality {
            min: 0,
            max: Max::Unbounded,
        },
        status: None,
    }),
];

/// The `RRI_I12` message structure of the 2.5.1 tables.
pub static RRI_I12: Structure = Structure {
    id: "RRI_I12",
    url: None,
    version: "2.5.1",
    withdrawn_as_of: None,
    nodes: &RRI_I12_NODES,
};
