// @generated by fhir-codegen from HL7/v2ig 3adcdbfff654ccbff5cd33aa34bd909a087e8e19 input/sourceOfTruth. DO NOT EDIT.
// Change the emitter (tools/fhir-codegen) and regenerate.
// SPDX-FileCopyrightText: Vernum Projecten B.V.
// SPDX-License-Identifier: Apache-2.0
//! The `CCD` complex data type: charge code and date.

use crate::data_type;
use crate::model::{Cardinality, Component, DataType, Length, Max, Optionality, Table};

/// The `CCD` data type definition, `http://hl7.org/v2/StructureDefinition/CCD`.
pub static CCD: DataType = DataType {
    code: "CCD",
    url: "http://hl7.org/v2/StructureDefinition/CCD",
    name: "charge code and date",
    components: &[
        Component {
            id: "CCD.1",
            position: 1,
            name: "Invocation Event",
            data_type: Some(&data_type::id::ID),
            cardinality: Some(Cardinality {
                min: 1,
                max: Max::Bounded(1),
            }),
            optionality: Optionality::R,
            length: Some(Length {
                min: 1,
                max: Some(1),
            }),
            conformance_length: None,
            table: Some(Table {
                id: "0100",
                value_set: "http://terminology.hl7.org/ValueSet/v2-0100",
            }),
        },
        Component {
            id: "CCD.2",
            position: 2,
            name: "Date/time",
            data_type: Some(&data_type::dtm::DTM),
            cardinality: Some(Cardinality {
                min: 0,
                max: Max::Bounded(1),
            }),
            optionality: Optionality::O,
            length: None,
            conformance_length: None,
            table: None,
        },
    ],
};
