// @generated by fhir-codegen from HL7/v2ig 3adcdbfff654ccbff5cd33aa34bd909a087e8e19 input/sourceOfTruth. DO NOT EDIT.
// Change the emitter (tools/fhir-codegen) and regenerate.
// SPDX-FileCopyrightText: Vernum Projecten B.V.
// SPDX-License-Identifier: Apache-2.0
//! The `CCP` complex data type: channel calibration parameters.

use crate::data_type;
use crate::model::{Cardinality, Component, ConformanceLength, DataType, Max, Optionality};

/// The `CCP` data type definition, `http://hl7.org/v2/StructureDefinition/CCP`.
pub static CCP: DataType = DataType {
    code: "CCP",
    url: "http://hl7.org/v2/StructureDefinition/CCP",
    name: "channel calibration parameters",
    components: &[
        Component {
            id: "CCP.1",
            position: 1,
            name: "Channel Calibration Sensitivity Correction Factor",
            data_type: Some(&data_type::nm::NM),
            cardinality: Some(Cardinality {
                min: 0,
                max: Max::Bounded(1),
            }),
            optionality: Optionality::O,
            length: None,
            conformance_length: Some(ConformanceLength {
                length: Some(6),
                no_truncate: Some(false),
            }),
            table: None,
        },
        Component {
            id: "CCP.2",
            position: 2,
            name: "Channel Calibration Baseline",
            data_type: Some(&data_type::nm::NM),
            cardinality: Some(Cardinality {
                min: 0,
                max: Max::Bounded(1),
            }),
            optionality: Optionality::O,
            length: None,
            conformance_length: Some(ConformanceLength {
                length: Some(6),
                no_truncate: Some(false),
            }),
            table: None,
        },
        Component {
            id: "CCP.3",
            position: 3,
            name: "Channel Calibration Time Skew",
            data_type: Some(&data_type::nm::NM),
            cardinality: Some(Cardinality {
                min: 0,
                max: Max::Bounded(1),
            }),
            optionality: Optionality::O,
            length: None,
            conformance_length: Some(ConformanceLength {
                length: Some(6),
                no_truncate: Some(false),
            }),
            table: None,
        },
    ],
};
