// @generated by fhir-codegen from HL7/v2ig 3adcdbfff654ccbff5cd33aa34bd909a087e8e19 input/sourceOfTruth. DO NOT EDIT.
// Change the emitter (tools/fhir-codegen) and regenerate.
// SPDX-FileCopyrightText: Vernum Projecten B.V.
// SPDX-License-Identifier: Apache-2.0
//! The `DTN` complex data type: day type and number.

use crate::data_type;
use crate::model::{Cardinality, Component, ConformanceLength, DataType, Max, Optionality, Table};

/// The `DTN` data type definition, `http://hl7.org/v2/StructureDefinition/DTN`.
pub static DTN: DataType = DataType {
    code: "DTN",
    url: "http://hl7.org/v2/StructureDefinition/DTN",
    name: "day type and number",
    components: &[
        Component {
            id: "DTN.1",
            position: 1,
            name: "Day Type",
            data_type: Some(&data_type::cwe::CWE),
            cardinality: Some(Cardinality {
                min: 1,
                max: Max::Bounded(1),
            }),
            optionality: Optionality::R,
            length: None,
            conformance_length: None,
            table: Some(Table {
                id: "0149",
                value_set: "http://terminology.hl7.org/ValueSet/v2-0149",
            }),
        },
        Component {
            id: "DTN.2",
            position: 2,
            name: "Number of Days",
            data_type: Some(&data_type::nm::NM),
            cardinality: Some(Cardinality {
                min: 1,
                max: Max::Bounded(1),
            }),
            optionality: Optionality::R,
            length: None,
            conformance_length: Some(ConformanceLength {
                length: Some(3),
                no_truncate: Some(false),
            }),
            table: None,
        },
    ],
};
