// @generated by fhir-codegen from HL7/v2ig 3adcdbfff654ccbff5cd33aa34bd909a087e8e19 input/sourceOfTruth. DO NOT EDIT.
// Change the emitter (tools/fhir-codegen) and regenerate.
// SPDX-FileCopyrightText: Vernum Projecten B.V.
// SPDX-License-Identifier: Apache-2.0
//! The `RCD` complex data type: row column definition.

use crate::data_type;
use crate::model::{Cardinality, Component, DataType, Length, Max, Optionality, Table};

/// The `RCD` data type definition, `http://hl7.org/v2/StructureDefinition/RCD`.
pub static RCD: DataType = DataType {
    code: "RCD",
    url: "http://hl7.org/v2/StructureDefinition/RCD",
    name: "row column definition",
    components: &[
        Component {
            id: "RCD.1",
            position: 1,
            name: "Segment Field Name",
            data_type: Some(&data_type::st::ST),
            cardinality: Some(Cardinality {
                min: 0,
                max: Max::Bounded(1),
            }),
            optionality: Optionality::O,
            length: Some(Length {
                min: 6,
                max: Some(12),
            }),
            conformance_length: None,
            table: None,
        },
        Component {
            id: "RCD.2",
            position: 2,
            name: "HL7 Data Type",
            data_type: Some(&data_type::id::ID),
            cardinality: Some(Cardinality {
                min: 0,
                max: Max::Bounded(1),
            }),
            optionality: Optionality::O,
            length: Some(Length {
                min: 2,
                max: Some(3),
            }),
            conformance_length: None,
            table: Some(Table {
                id: "0440",
                value_set: "http://terminology.hl7.org/ValueSet/v2-0440",
            }),
        },
        Component {
            id: "RCD.3",
            position: 3,
            name: "Maximum Column Width",
            data_type: Some(&data_type::nm::NM),
            cardinality: Some(Cardinality {
                min: 0,
                max: Max::Bounded(1),
            }),
            optionality: Optionality::O,
            length: Some(Length {
                min: 1,
                max: Some(5),
            }),
            conformance_length: None,
            table: None,
        },
    ],
};
