// @generated by fhir-codegen from HL7/v2ig 3adcdbfff654ccbff5cd33aa34bd909a087e8e19 input/sourceOfTruth. DO NOT EDIT.
// Change the emitter (tools/fhir-codegen) and regenerate.
// SPDX-FileCopyrightText: Vernum Projecten B.V.
// SPDX-License-Identifier: Apache-2.0
//! The `RPT` complex data type: repeat pattern.

use crate::data_type;
use crate::model::{
    Cardinality, Component, ConformanceLength, DataType, Length, Max, Optionality, Table,
};

/// The `RPT` data type definition, `http://hl7.org/v2/StructureDefinition/RPT`.
pub static RPT: DataType = DataType {
    code: "RPT",
    url: "http://hl7.org/v2/StructureDefinition/RPT",
    name: "repeat pattern",
    components: &[
        Component {
            id: "RPT.1",
            position: 1,
            name: "Repeat Pattern Code",
            data_type: Some(&data_type::cwe::CWE),
            cardinality: Some(Cardinality {
                min: 1,
                max: Max::Bounded(1),
            }),
            optionality: Optionality::R,
            length: None,
            conformance_length: None,
            table: Some(Table {
                id: "0335",
                value_set: "http://terminology.hl7.org/ValueSet/v2-0335",
            }),
        },
        Component {
            id: "RPT.2",
            position: 2,
            name: "Calendar Alignment",
            data_type: Some(&data_type::id::ID),
            cardinality: Some(Cardinality {
                min: 0,
                max: Max::Bounded(1),
            }),
            optionality: Optionality::O,
            length: Some(Length {
                min: 2,
                max: Some(2),
            }),
            conformance_length: None,
            table: Some(Table {
                id: "0527",
                value_set: "http://terminology.hl7.org/ValueSet/v2-0527",
            }),
        },
        Component {
            id: "RPT.3",
            position: 3,
            name: "Phase Range Begin Value",
            data_type: Some(&data_type::nm::NM),
            cardinality: Some(Cardinality {
                min: 0,
                max: Max::Bounded(1),
            }),
            optionality: Optionality::O,
            length: None,
            conformance_length: Some(ConformanceLength {
                length: Some(10),
                no_truncate: Some(true),
            }),
            table: None,
        },
        Component {
            id: "RPT.4",
            position: 4,
            name: "Phase Range End Value",
            data_type: Some(&data_type::nm::NM),
            cardinality: Some(Cardinality {
                min: 0,
                max: Max::Bounded(1),
            }),
            optionality: Optionality::O,
            length: None,
            conformance_length: Some(ConformanceLength {
                length: Some(10),
                no_truncate: Some(true),
            }),
            table: None,
        },
        Component {
            id: "RPT.5",
            position: 5,
            name: "Period Quantity",
            data_type: Some(&data_type::nm::NM),
            cardinality: Some(Cardinality {
                min: 0,
                max: Max::Bounded(1),
            }),
            optionality: Optionality::O,
            length: None,
            conformance_length: Some(ConformanceLength {
                length: Some(10),
                no_truncate: Some(true),
            }),
            table: None,
        },
        Component {
            id: "RPT.6",
            position: 6,
            name: "Period Units",
            data_type: Some(&data_type::cwe::CWE),
            cardinality: Some(Cardinality {
                min: 0,
                max: Max::Bounded(1),
            }),
            optionality: Optionality::C,
            length: None,
            conformance_length: None,
            table: None,
        },
        Component {
            id: "RPT.7",
            position: 7,
            name: "Institution Specified Time",
            data_type: Some(&data_type::id::ID),
            cardinality: Some(Cardinality {
                min: 0,
                max: Max::Bounded(1),
            }),
            optionality: Optionality::O,
            length: Some(Length {
                min: 1,
                max: Some(1),
            }),
            conformance_length: None,
            table: Some(Table {
                id: "0136",
                value_set: "http://terminology.hl7.org/ValueSet/v2-0136",
            }),
        },
        Component {
            id: "RPT.8",
            position: 8,
            name: "Event",
            data_type: Some(&data_type::id::ID),
            cardinality: Some(Cardinality {
                min: 0,
                max: Max::Bounded(1),
            }),
            optionality: Optionality::O,
            length: Some(Length {
                min: 2,
                max: Some(3),
            }),
            conformance_length: None,
            table: Some(Table {
                id: "0528",
                value_set: "http://terminology.hl7.org/ValueSet/v2-0528",
            }),
        },
        Component {
            id: "RPT.9",
            position: 9,
            name: "Event Offset Quantity",
            data_type: Some(&data_type::nm::NM),
            cardinality: Some(Cardinality {
                min: 0,
                max: Max::Bounded(1),
            }),
            optionality: Optionality::O,
            length: None,
            conformance_length: Some(ConformanceLength {
                length: Some(10),
                no_truncate: Some(true),
            }),
            table: None,
        },
        Component {
            id: "RPT.10",
            position: 10,
            name: "Event Offset Units",
            data_type: Some(&data_type::cwe::CWE),
            cardinality: Some(Cardinality {
                min: 0,
                max: Max::Bounded(1),
            }),
            optionality: Optionality::C,
            length: None,
            conformance_length: None,
            table: None,
        },
        Component {
            id: "RPT.11",
            position: 11,
            name: "General Timing Specification",
            data_type: Some(&data_type::gts::GTS),
            cardinality: Some(Cardinality {
                min: 0,
                max: Max::Bounded(1),
            }),
            optionality: Optionality::O,
            length: None,
            conformance_length: None,
            table: None,
        },
    ],
};
