// @generated by fhir-codegen from usnistgov/igamt-hl7Tools-service 83322dffdac18cb129a1bd80149f5439cf5686fd src/main/resources/hl7db. DO NOT EDIT.
// Change the emitter (tools/fhir-codegen) and regenerate.
// SPDX-FileCopyrightText: Vernum Projecten B.V.
// SPDX-License-Identifier: Apache-2.0
//! The `AIS` segment: Appointment Information.

use crate::model::{Cardinality, DataTypeRef, Field, Length, Max, Optionality, Segment, Table};

/// The `AIS` segment of the 2.5 tables.
pub static AIS: Segment = Segment {
    id: "AIS",
    url: None,
    name: "Appointment Information",
    fields: &[
        Field {
            id: "AIS.1",
            position: 1,
            name: "Set ID - AIS",
            data_type: Some(DataTypeRef::Legacy(&crate::legacy::v2_5::data_type::SI)),
            cardinality: Cardinality {
                min: 1,
                max: Max::Bounded(1),
            },
            optionality: Optionality::R,
            length: Some(Length {
                min: 0,
                max: Some(4),
            }),
            conformance_length: None,
            table: None,
            standards_status: None,
        },
        Field {
            id: "AIS.2",
            position: 2,
            name: "Segment Action Code",
            data_type: Some(DataTypeRef::Legacy(&crate::legacy::v2_5::data_type::ID)),
            cardinality: Cardinality {
                min: 0,
                max: Max::Bounded(1),
            },
            optionality: Optionality::C,
            length: Some(Length {
                min: 0,
                max: Some(3),
            }),
            conformance_length: None,
            table: Some(Table {
                id: "0206",
                value_set: "http://terminology.hl7.org/ValueSet/v2-0206",
            }),
            standards_status: None,
        },
        Field {
            id: "AIS.3",
            position: 3,
            name: "Universal Service Identifier",
            data_type: Some(DataTypeRef::Legacy(&crate::legacy::v2_5::data_type::CE)),
            cardinality: Cardinality {
                min: 1,
                max: Max::Bounded(1),
            },
            optionality: Optionality::R,
            length: Some(Length {
                min: 0,
                max: Some(250),
            }),
            conformance_length: None,
            table: None,
            standards_status: None,
        },
        Field {
            id: "AIS.4",
            position: 4,
            name: "Start Date/Time",
            data_type: Some(DataTypeRef::Legacy(&crate::legacy::v2_5::data_type::TS)),
            cardinality: Cardinality {
                min: 0,
                max: Max::Bounded(1),
            },
            optionality: Optionality::C,
            length: Some(Length {
                min: 0,
                max: Some(26),
            }),
            conformance_length: None,
            table: None,
            standards_status: None,
        },
        Field {
            id: "AIS.5",
            position: 5,
            name: "Start Date/Time Offset",
            data_type: Some(DataTypeRef::Legacy(&crate::legacy::v2_5::data_type::NM)),
            cardinality: Cardinality {
                min: 0,
                max: Max::Bounded(1),
            },
            optionality: Optionality::C,
            length: Some(Length {
                min: 0,
                max: Some(20),
            }),
            conformance_length: None,
            table: None,
            standards_status: None,
        },
        Field {
            id: "AIS.6",
            position: 6,
            name: "Start Date/Time Offset Units",
            data_type: Some(DataTypeRef::Legacy(&crate::legacy::v2_5::data_type::CE)),
            cardinality: Cardinality {
                min: 0,
                max: Max::Bounded(1),
            },
            optionality: Optionality::C,
            length: Some(Length {
                min: 0,
                max: Some(250),
            }),
            conformance_length: None,
            table: None,
            standards_status: None,
        },
        Field {
            id: "AIS.7",
            position: 7,
            name: "Duration",
            data_type: Some(DataTypeRef::Legacy(&crate::legacy::v2_5::data_type::NM)),
            cardinality: Cardinality {
                min: 0,
                max: Max::Bounded(1),
            },
            optionality: Optionality::O,
            length: Some(Length {
                min: 0,
                max: Some(20),
            }),
            conformance_length: None,
            table: None,
            standards_status: None,
        },
        Field {
            id: "AIS.8",
            position: 8,
            name: "Duration Units",
            data_type: Some(DataTypeRef::Legacy(&crate::legacy::v2_5::data_type::CE)),
            cardinality: Cardinality {
                min: 0,
                max: Max::Bounded(1),
            },
            optionality: Optionality::O,
            length: Some(Length {
                min: 0,
                max: Some(250),
            }),
            conformance_length: None,
            table: None,
            standards_status: None,
        },
        Field {
            id: "AIS.9",
            position: 9,
            name: "Allow Substitution Code",
            data_type: Some(DataTypeRef::Legacy(&crate::legacy::v2_5::data_type::IS)),
            cardinality: Cardinality {
                min: 0,
                max: Max::Bounded(1),
            },
            optionality: Optionality::C,
            length: Some(Length {
                min: 0,
                max: Some(10),
            }),
            conformance_length: None,
            table: Some(Table {
                id: "0279",
                value_set: "http://terminology.hl7.org/ValueSet/v2-0279",
            }),
            standards_status: None,
        },
        Field {
            id: "AIS.10",
            position: 10,
            name: "Filler Status Code",
            data_type: Some(DataTypeRef::Legacy(&crate::legacy::v2_5::data_type::CE)),
            cardinality: Cardinality {
                min: 0,
                max: Max::Bounded(1),
            },
            optionality: Optionality::C,
            length: Some(Length {
                min: 0,
                max: Some(250),
            }),
            conformance_length: None,
            table: Some(Table {
                id: "0278",
                value_set: "http://terminology.hl7.org/ValueSet/v2-0278",
            }),
            standards_status: None,
        },
        Field {
            id: "AIS.11",
            position: 11,
            name: "Placer Supplemental Service Information",
            data_type: Some(DataTypeRef::Legacy(&crate::legacy::v2_5::data_type::CE)),
            cardinality: Cardinality {
                min: 0,
                max: Max::Unbounded,
            },
            optionality: Optionality::O,
            length: Some(Length {
                min: 0,
                max: Some(250),
            }),
            conformance_length: None,
            table: Some(Table {
                id: "0411",
                value_set: "http://terminology.hl7.org/ValueSet/v2-0411",
            }),
            standards_status: None,
        },
        Field {
            id: "AIS.12",
            position: 12,
            name: "Filler Supplemental Service Information",
            data_type: Some(DataTypeRef::Legacy(&crate::legacy::v2_5::data_type::CE)),
            cardinality: Cardinality {
                min: 0,
                max: Max::Unbounded,
            },
            optionality: Optionality::O,
            length: Some(Length {
                min: 0,
                max: Some(250),
            }),
            conformance_length: None,
            table: Some(Table {
                id: "0411",
                value_set: "http://terminology.hl7.org/ValueSet/v2-0411",
            }),
            standards_status: None,
        },
    ],
};
