// @generated by fhir-codegen from usnistgov/igamt-hl7Tools-service 83322dffdac18cb129a1bd80149f5439cf5686fd src/main/resources/hl7db. DO NOT EDIT.
// Change the emitter (tools/fhir-codegen) and regenerate.
// SPDX-FileCopyrightText: Vernum Projecten B.V.
// SPDX-License-Identifier: Apache-2.0
//! The `MFI` segment: Master File Identification.

use crate::model::{Cardinality, DataTypeRef, Field, Length, Max, Optionality, Segment, Table};

/// The `MFI` segment of the 2.5 tables.
pub static MFI: Segment = Segment {
    id: "MFI",
    url: None,
    name: "Master File Identification",
    fields: &[
        Field {
            id: "MFI.1",
            position: 1,
            name: "Master File Identifier",
            data_type: Some(DataTypeRef::Legacy(&crate::legacy::v2_5::data_type::CE)),
            cardinality: Cardinality {
                min: 1,
                max: Max::Bounded(1),
            },
            optionality: Optionality::R,
            length: Some(Length {
                min: 0,
                max: Some(250),
            }),
            conformance_length: None,
            table: Some(Table {
                id: "0175",
                value_set: "http://terminology.hl7.org/ValueSet/v2-0175",
            }),
            standards_status: None,
        },
        Field {
            id: "MFI.2",
            position: 2,
            name: "Master File Application Identifier",
            data_type: Some(DataTypeRef::Legacy(&crate::legacy::v2_5::data_type::HD)),
            cardinality: Cardinality {
                min: 0,
                max: Max::Bounded(1),
            },
            optionality: Optionality::O,
            length: Some(Length {
                min: 0,
                max: Some(180),
            }),
            conformance_length: None,
            table: Some(Table {
                id: "0361",
                value_set: "http://terminology.hl7.org/ValueSet/v2-0361",
            }),
            standards_status: None,
        },
        Field {
            id: "MFI.3",
            position: 3,
            name: "File-Level Event Code",
            data_type: Some(DataTypeRef::Legacy(&crate::legacy::v2_5::data_type::ID)),
            cardinality: Cardinality {
                min: 1,
                max: Max::Bounded(1),
            },
            optionality: Optionality::R,
            length: Some(Length {
                min: 0,
                max: Some(3),
            }),
            conformance_length: None,
            table: Some(Table {
                id: "0178",
                value_set: "http://terminology.hl7.org/ValueSet/v2-0178",
            }),
            standards_status: None,
        },
        Field {
            id: "MFI.4",
            position: 4,
            name: "Entered Date/Time",
            data_type: Some(DataTypeRef::Legacy(&crate::legacy::v2_5::data_type::TS)),
            cardinality: Cardinality {
                min: 0,
                max: Max::Bounded(1),
            },
            optionality: Optionality::O,
            length: Some(Length {
                min: 0,
                max: Some(26),
            }),
            conformance_length: None,
            table: None,
            standards_status: None,
        },
        Field {
            id: "MFI.5",
            position: 5,
            name: "Effective Date/Time",
            data_type: Some(DataTypeRef::Legacy(&crate::legacy::v2_5::data_type::TS)),
            cardinality: Cardinality {
                min: 0,
                max: Max::Bounded(1),
            },
            optionality: Optionality::O,
            length: Some(Length {
                min: 0,
                max: Some(26),
            }),
            conformance_length: None,
            table: None,
            standards_status: None,
        },
        Field {
            id: "MFI.6",
            position: 6,
            name: "Response Level Code",
            data_type: Some(DataTypeRef::Legacy(&crate::legacy::v2_5::data_type::ID)),
            cardinality: Cardinality {
                min: 1,
                max: Max::Bounded(1),
            },
            optionality: Optionality::R,
            length: Some(Length {
                min: 0,
                max: Some(2),
            }),
            conformance_length: None,
            table: Some(Table {
                id: "0179",
                value_set: "http://terminology.hl7.org/ValueSet/v2-0179",
            }),
            standards_status: None,
        },
    ],
};
