// @generated by fhir-codegen from HL7/v2ig 3adcdbfff654ccbff5cd33aa34bd909a087e8e19 input/sourceOfTruth. DO NOT EDIT.
// Change the emitter (tools/fhir-codegen) and regenerate.
// SPDX-FileCopyrightText: Vernum Projecten B.V.
// SPDX-License-Identifier: Apache-2.0
//! The `ADT^A55` message definition.

use crate::model::{Message, MessageStatus};
use crate::structure;

/// The `ADT-A55` message definition, `http://hl7.org/v2/StructureDefinition/Message/ADT-A55`.
pub static ADT_A55: Message = Message {
    id: "ADT-A55",
    url: "http://hl7.org/v2/StructureDefinition/Message/ADT-A55",
    code: "ADT",
    event: "A55",
    structure: Some(&structure::adt_a54_b::ADT_A54_B),
    status: MessageStatus::Active,
};
