// @generated by fhir-codegen from HL7/v2ig 3adcdbfff654ccbff5cd33aa34bd909a087e8e19 input/sourceOfTruth. DO NOT EDIT.
// Change the emitter (tools/fhir-codegen) and regenerate.
// SPDX-FileCopyrightText: Vernum Projecten B.V.
// SPDX-License-Identifier: Apache-2.0
//! The `CCF^I22` message definition.

use crate::model::{Message, MessageStatus};
use crate::structure;

/// The `CCF-I22` message definition, `http://hl7.org/v2/StructureDefinition/Message/CCF-I22`.
pub static CCF_I22: Message = Message {
    id: "CCF-I22",
    url: "http://hl7.org/v2/StructureDefinition/Message/CCF-I22",
    code: "CCF",
    event: "I22",
    structure: Some(&structure::ccf_i22::CCF_I22),
    status: MessageStatus::Active,
};
