// @generated by fhir-codegen from HL7/v2ig 3adcdbfff654ccbff5cd33aa34bd909a087e8e19 input/sourceOfTruth. DO NOT EDIT.
// Change the emitter (tools/fhir-codegen) and regenerate.
// SPDX-FileCopyrightText: Vernum Projecten B.V.
// SPDX-License-Identifier: Apache-2.0
//! The `CQU^I19` message definition.

use crate::model::{Message, MessageStatus};
use crate::structure;

/// The `CQU-I19` message definition, `http://hl7.org/v2/StructureDefinition/Message/CQU-I19`.
pub static CQU_I19: Message = Message {
    id: "CQU-I19",
    url: "http://hl7.org/v2/StructureDefinition/Message/CQU-I19",
    code: "CQU",
    event: "I19",
    structure: Some(&structure::cqu_i19::CQU_I19),
    status: MessageStatus::Active,
};
