// @generated by fhir-codegen from HL7/v2ig 3adcdbfff654ccbff5cd33aa34bd909a087e8e19 input/sourceOfTruth. DO NOT EDIT.
// Change the emitter (tools/fhir-codegen) and regenerate.
// SPDX-FileCopyrightText: Vernum Projecten B.V.
// SPDX-License-Identifier: Apache-2.0
//! The `EHC^E02` message definition.

use crate::model::{Message, MessageStatus};
use crate::structure;

/// The `EHC-E02` message definition, `http://hl7.org/v2/StructureDefinition/Message/EHC-E02`.
pub static EHC_E02: Message = Message {
    id: "EHC-E02",
    url: "http://hl7.org/v2/StructureDefinition/Message/EHC-E02",
    code: "EHC",
    event: "E02",
    structure: Some(&structure::ehc_e02::EHC_E02),
    status: MessageStatus::Active,
};
