// @generated by fhir-codegen from HL7/v2ig 3adcdbfff654ccbff5cd33aa34bd909a087e8e19 input/sourceOfTruth. DO NOT EDIT.
// Change the emitter (tools/fhir-codegen) and regenerate.
// SPDX-FileCopyrightText: Vernum Projecten B.V.
// SPDX-License-Identifier: Apache-2.0
//! The `MFK^M02` message definition.

use crate::model::{Message, MessageStatus};
use crate::structure;

/// The `MFK-M02` message definition, `http://hl7.org/v2/StructureDefinition/Message/MFK-M02`.
pub static MFK_M02: Message = Message {
    id: "MFK-M02",
    url: "http://hl7.org/v2/StructureDefinition/Message/MFK-M02",
    code: "MFK",
    event: "M02",
    structure: Some(&structure::mfk_m01_c::MFK_M01_C),
    status: MessageStatus::Active,
};
