// @generated by fhir-codegen from HL7/v2ig 3adcdbfff654ccbff5cd33aa34bd909a087e8e19 input/sourceOfTruth. DO NOT EDIT.
// Change the emitter (tools/fhir-codegen) and regenerate.
// SPDX-FileCopyrightText: Vernum Projecten B.V.
// SPDX-License-Identifier: Apache-2.0
//! The `ORU^R40` message definition.

use crate::model::{Message, MessageStatus};
use crate::structure;

/// The `ORU-R40` message definition, `http://hl7.org/v2/StructureDefinition/Message/ORU-R40`.
pub static ORU_R40: Message = Message {
    id: "ORU-R40",
    url: "http://hl7.org/v2/StructureDefinition/Message/ORU-R40",
    code: "ORU",
    event: "R40",
    structure: Some(&structure::oru_r01_b::ORU_R01_B),
    status: MessageStatus::Active,
};
