// @generated by fhir-codegen from HL7/v2ig 3adcdbfff654ccbff5cd33aa34bd909a087e8e19 input/sourceOfTruth. DO NOT EDIT.
// Change the emitter (tools/fhir-codegen) and regenerate.
// SPDX-FileCopyrightText: Vernum Projecten B.V.
// SPDX-License-Identifier: Apache-2.0
//! The `OUL^R22` message definition.

use crate::model::{Message, MessageStatus};
use crate::structure;

/// The `OUL-R22` message definition, `http://hl7.org/v2/StructureDefinition/Message/OUL-R22`.
pub static OUL_R22: Message = Message {
    id: "OUL-R22",
    url: "http://hl7.org/v2/StructureDefinition/Message/OUL-R22",
    code: "OUL",
    event: "R22",
    structure: Some(&structure::oul_r22::OUL_R22),
    status: MessageStatus::Active,
};
