// @generated by fhir-codegen from HL7/v2ig 3adcdbfff654ccbff5cd33aa34bd909a087e8e19 input/sourceOfTruth. DO NOT EDIT.
// Change the emitter (tools/fhir-codegen) and regenerate.
// SPDX-FileCopyrightText: Vernum Projecten B.V.
// SPDX-License-Identifier: Apache-2.0
//! The `PMU^B03` message definition.

use crate::model::{Message, MessageStatus};
use crate::structure;

/// The `PMU-B03` message definition, `http://hl7.org/v2/StructureDefinition/Message/PMU-B03`.
pub static PMU_B03: Message = Message {
    id: "PMU-B03",
    url: "http://hl7.org/v2/StructureDefinition/Message/PMU-B03",
    code: "PMU",
    event: "B03",
    structure: Some(&structure::pmu_b03::PMU_B03),
    status: MessageStatus::Active,
};
