// @generated by fhir-codegen from HL7/v2ig 3adcdbfff654ccbff5cd33aa34bd909a087e8e19 input/sourceOfTruth. DO NOT EDIT.
// Change the emitter (tools/fhir-codegen) and regenerate.
// SPDX-FileCopyrightText: Vernum Projecten B.V.
// SPDX-License-Identifier: Apache-2.0
//! The `PPP^PCC` message definition.

use crate::model::{Message, MessageStatus};
use crate::structure;

/// The `PPP-PCC` message definition, `http://hl7.org/v2/StructureDefinition/Message/PPP-PCC`.
pub static PPP_PCC: Message = Message {
    id: "PPP-PCC",
    url: "http://hl7.org/v2/StructureDefinition/Message/PPP-PCC",
    code: "PPP",
    event: "PCC",
    structure: Some(&structure::ppp_pcb::PPP_PCB),
    status: MessageStatus::Active,
};
