// @generated by fhir-codegen from HL7/v2ig 3adcdbfff654ccbff5cd33aa34bd909a087e8e19 input/sourceOfTruth. DO NOT EDIT.
// Change the emitter (tools/fhir-codegen) and regenerate.
// SPDX-FileCopyrightText: Vernum Projecten B.V.
// SPDX-License-Identifier: Apache-2.0
//! The `SLN^S35` message definition.

use crate::model::{Message, MessageStatus};
use crate::structure;

/// The `SLN-S35` message definition, `http://hl7.org/v2/StructureDefinition/Message/SLN-S35`.
pub static SLN_S35: Message = Message {
    id: "SLN-S35",
    url: "http://hl7.org/v2/StructureDefinition/Message/SLN-S35",
    code: "SLN",
    event: "S35",
    structure: Some(&structure::slr_s28_e::SLR_S28_E),
    status: MessageStatus::Active,
};
