// @generated by fhir-codegen from HL7/v2ig 3adcdbfff654ccbff5cd33aa34bd909a087e8e19 input/sourceOfTruth. DO NOT EDIT.
// Change the emitter (tools/fhir-codegen) and regenerate.
// SPDX-FileCopyrightText: Vernum Projecten B.V.
// SPDX-License-Identifier: Apache-2.0
//! The `SQM^S25` message definition.

use crate::model::{Message, MessageStatus};

/// The `SQM-S25` message definition, `http://hl7.org/v2/StructureDefinition/Message/SQM-S25`.
pub static SQM_S25: Message = Message {
    id: "SQM-S25",
    url: "http://hl7.org/v2/StructureDefinition/Message/SQM-S25",
    code: "SQM",
    event: "S25",
    structure: None,
    status: MessageStatus::Withdrawn,
};
