// @generated by fhir-codegen from HL7/v2ig 3adcdbfff654ccbff5cd33aa34bd909a087e8e19 input/sourceOfTruth. DO NOT EDIT.
// Change the emitter (tools/fhir-codegen) and regenerate.
// SPDX-FileCopyrightText: Vernum Projecten B.V.
// SPDX-License-Identifier: Apache-2.0
//! The `SRR^S05` message definition.

use crate::model::{Message, MessageStatus};
use crate::structure;

/// The `SRR-S05` message definition, `http://hl7.org/v2/StructureDefinition/Message/SRR-S05`.
pub static SRR_S05: Message = Message {
    id: "SRR-S05",
    url: "http://hl7.org/v2/StructureDefinition/Message/SRR-S05",
    code: "SRR",
    event: "S05",
    structure: Some(&structure::srr_s01::SRR_S01),
    status: MessageStatus::Active,
};
