// @generated by fhir-codegen from usnistgov/igamt-hl7Tools-service 83322dffdac18cb129a1bd80149f5439cf5686fd src/main/resources/hl7db. DO NOT EDIT.
// Change the emitter (tools/fhir-codegen) and regenerate.
// SPDX-FileCopyrightText: Vernum Projecten B.V.
// SPDX-License-Identifier: Apache-2.0
//! The `CTD` segment: Contact Data.

use crate::model::{Cardinality, DataTypeRef, Field, Length, Max, Optionality, Segment, Table};

/// The `CTD` segment of the 2.3.1 tables.
pub static CTD: Segment = Segment {
    id: "CTD",
    url: None,
    name: "Contact Data",
    fields: &[
        Field {
            id: "CTD.1",
            position: 1,
            name: "Contact Role",
            data_type: Some(DataTypeRef::Legacy(
                &crate::legacy::v2_3_1::data_type::CE_0131,
            )),
            cardinality: Cardinality {
                min: 0,
                max: Max::Unbounded,
            },
            optionality: Optionality::Na,
            length: Some(Length {
                min: 0,
                max: Some(200),
            }),
            conformance_length: None,
            table: Some(Table {
                id: "0131",
                value_set: "http://terminology.hl7.org/ValueSet/v2-0131",
            }),
            standards_status: None,
        },
        Field {
            id: "CTD.2",
            position: 2,
            name: "Contact Name",
            data_type: Some(DataTypeRef::Legacy(&crate::legacy::v2_3_1::data_type::XPN)),
            cardinality: Cardinality {
                min: 0,
                max: Max::Unbounded,
            },
            optionality: Optionality::O,
            length: Some(Length {
                min: 0,
                max: Some(106),
            }),
            conformance_length: None,
            table: None,
            standards_status: None,
        },
        Field {
            id: "CTD.3",
            position: 3,
            name: "Contact Address",
            data_type: Some(DataTypeRef::Legacy(&crate::legacy::v2_3_1::data_type::XAD)),
            cardinality: Cardinality {
                min: 0,
                max: Max::Unbounded,
            },
            optionality: Optionality::Na,
            length: Some(Length {
                min: 0,
                max: Some(200),
            }),
            conformance_length: None,
            table: None,
            standards_status: None,
        },
        Field {
            id: "CTD.4",
            position: 4,
            name: "Contact Location",
            data_type: Some(DataTypeRef::Legacy(&crate::legacy::v2_3_1::data_type::PL)),
            cardinality: Cardinality {
                min: 0,
                max: Max::Bounded(1),
            },
            optionality: Optionality::O,
            length: Some(Length {
                min: 0,
                max: Some(60),
            }),
            conformance_length: None,
            table: None,
            standards_status: None,
        },
        Field {
            id: "CTD.5",
            position: 5,
            name: "Contact Communication Information",
            data_type: Some(DataTypeRef::Legacy(&crate::legacy::v2_3_1::data_type::XTN)),
            cardinality: Cardinality {
                min: 0,
                max: Max::Unbounded,
            },
            optionality: Optionality::O,
            length: Some(Length {
                min: 0,
                max: Some(100),
            }),
            conformance_length: None,
            table: None,
            standards_status: None,
        },
        Field {
            id: "CTD.6",
            position: 6,
            name: "Preferred Method Of Contact",
            data_type: Some(DataTypeRef::Legacy(
                &crate::legacy::v2_3_1::data_type::CE_0185,
            )),
            cardinality: Cardinality {
                min: 0,
                max: Max::Bounded(1),
            },
            optionality: Optionality::Na,
            length: Some(Length {
                min: 0,
                max: Some(200),
            }),
            conformance_length: None,
            table: Some(Table {
                id: "0185",
                value_set: "http://terminology.hl7.org/ValueSet/v2-0185",
            }),
            standards_status: None,
        },
        Field {
            id: "CTD.7",
            position: 7,
            name: "Contact Identifiers",
            data_type: Some(DataTypeRef::Legacy(&crate::legacy::v2_3_1::data_type::PI)),
            cardinality: Cardinality {
                min: 0,
                max: Max::Unbounded,
            },
            optionality: Optionality::O,
            length: Some(Length {
                min: 0,
                max: Some(100),
            }),
            conformance_length: None,
            table: None,
            standards_status: None,
        },
    ],
};
