// @generated by fhir-codegen from usnistgov/igamt-hl7Tools-service 83322dffdac18cb129a1bd80149f5439cf5686fd src/main/resources/hl7db. DO NOT EDIT.
// Change the emitter (tools/fhir-codegen) and regenerate.
// SPDX-FileCopyrightText: Vernum Projecten B.V.
// SPDX-License-Identifier: Apache-2.0
//! The `ADT_A60` message structure of the 2.7.1 tables.

use crate::model::{Cardinality, Group, GroupKind, Max, Node, SegmentRef, Structure};

/// The top-level nodes of [`ADT_A60`], one `static` so a structure with the same tree links to it.
pub static ADT_A60_NODES: [Node; 10] = [
    Node::Segment(SegmentRef {
        id: "ADT_A60.1-MSH",
        position: 1,
        segment: &crate::legacy::v2_7_1::segment::msh::MSH,
        cardinality: Cardinality {
            min: 1,
            max: Max::Bounded(1),
        },
        status: None,
    }),
    Node::Segment(SegmentRef {
        id: "ADT_A60.2-SFT",
        position: 2,
        segment: &crate::segment::sft::SFT,
        cardinality: Cardinality {
            min: 0,
            max: Max::Unbounded,
        },
        status: None,
    }),
    Node::Segment(SegmentRef {
        id: "ADT_A60.3-UAC",
        position: 3,
        segment: &crate::segment::uac::UAC,
        cardinality: Cardinality {
            min: 0,
            max: Max::Bounded(1),
        },
        status: None,
    }),
    Node::Segment(SegmentRef {
        id: "ADT_A60.4-EVN",
        position: 4,
        segment: &crate::legacy::v2_7_1::segment::evn::EVN,
        cardinality: Cardinality {
            min: 1,
            max: Max::Bounded(1),
        },
        status: None,
    }),
    Node::Segment(SegmentRef {
        id: "ADT_A60.5-PID",
        position: 5,
        segment: &crate::legacy::v2_7_1::segment::pid::PID,
        cardinality: Cardinality {
            min: 1,
            max: Max::Bounded(1),
        },
        status: None,
    }),
    Node::Segment(SegmentRef {
        id: "ADT_A60.6-ARV",
        position: 6,
        segment: &crate::legacy::v2_7_1::segment::arv::ARV,
        cardinality: Cardinality {
            min: 0,
            max: Max::Unbounded,
        },
        status: None,
    }),
    Node::Segment(SegmentRef {
        id: "ADT_A60.7-PV1",
        position: 7,
        segment: &crate::legacy::v2_7_1::segment::pv1::PV1,
        cardinality: Cardinality {
            min: 0,
            max: Max::Bounded(1),
        },
        status: None,
    }),
    Node::Segment(SegmentRef {
        id: "ADT_A60.8-PV2",
        position: 8,
        segment: &crate::legacy::v2_7_1::segment::pv2::PV2,
        cardinality: Cardinality {
            min: 0,
            max: Max::Bounded(1),
        },
        status: None,
    }),
    Node::Segment(SegmentRef {
        id: "ADT_A60.9-ARV",
        position: 9,
        segment: &crate::legacy::v2_7_1::segment::arv::ARV,
        cardinality: Cardinality {
            min: 0,
            max: Max::Unbounded,
        },
        status: None,
    }),
    Node::Group(Group {
        id: "ADT_A60.10-ADVERSE_REACTION_GROUP",
        position: 10,
        name: "ADVERSE_REACTION_GROUP",
        cardinality: Cardinality {
            min: 0,
            max: Max::Unbounded,
        },
        kind: GroupKind::Sequence,
        children: &[
            Node::Segment(SegmentRef {
                id: "ADT_A60.10-ADVERSE_REACTION_GROUP.1-IAM",
                position: 1,
                segment: &crate::segment::iam::IAM,
                cardinality: Cardinality {
                    min: 1,
                    max: Max::Bounded(1),
                },
                status: None,
            }),
            Node::Segment(SegmentRef {
                id: "ADT_A60.10-ADVERSE_REACTION_GROUP.2-NTE",
                position: 2,
                segment: &crate::legacy::v2_7_1::segment::nte::NTE,
                cardinality: Cardinality {
                    min: 0,
                    max: Max::Unbounded,
                },
                status: None,
            }),
            Node::Segment(SegmentRef {
                id: "ADT_A60.10-ADVERSE_REACTION_GROUP.3-IAR",
                position: 3,
                segment: &crate::segment::iar::IAR,
                cardinality: Cardinality {
                    min: 0,
                    max: Max::Unbounded,
                },
                status: None,
            }),
        ],
    }),
];

/// The `ADT_A60` message structure of the 2.7.1 tables.
pub static ADT_A60: Structure = Structure {
    id: "ADT_A60",
    url: None,
    version: "2.7.1",
    withdrawn_as_of: None,
    nodes: &ADT_A60_NODES,
};
