// @generated by fhir-codegen from usnistgov/igamt-hl7Tools-service 83322dffdac18cb129a1bd80149f5439cf5686fd src/main/resources/hl7db. DO NOT EDIT.
// Change the emitter (tools/fhir-codegen) and regenerate.
// SPDX-FileCopyrightText: Vernum Projecten B.V.
// SPDX-License-Identifier: Apache-2.0
//! The `DFT_P11` message structure of the 2.7.1 tables.

use crate::model::{Cardinality, Group, GroupKind, Max, Node, SegmentRef, Structure};

/// The top-level nodes of [`DFT_P11`], one `static` so a structure with the same tree links to it.
pub static DFT_P11_NODES: [Node; 18] = [
    Node::Segment(SegmentRef {
        id: "DFT_P11.1-MSH",
        position: 1,
        segment: &crate::legacy::v2_7_1::segment::msh::MSH,
        cardinality: Cardinality {
            min: 1,
            max: Max::Bounded(1),
        },
        status: None,
    }),
    Node::Segment(SegmentRef {
        id: "DFT_P11.2-SFT",
        position: 2,
        segment: &crate::segment::sft::SFT,
        cardinality: Cardinality {
            min: 0,
            max: Max::Unbounded,
        },
        status: None,
    }),
    Node::Segment(SegmentRef {
        id: "DFT_P11.3-UAC",
        position: 3,
        segment: &crate::segment::uac::UAC,
        cardinality: Cardinality {
            min: 0,
            max: Max::Bounded(1),
        },
        status: None,
    }),
    Node::Segment(SegmentRef {
        id: "DFT_P11.4-EVN",
        position: 4,
        segment: &crate::legacy::v2_7_1::segment::evn::EVN,
        cardinality: Cardinality {
            min: 1,
            max: Max::Bounded(1),
        },
        status: None,
    }),
    Node::Segment(SegmentRef {
        id: "DFT_P11.5-PID",
        position: 5,
        segment: &crate::legacy::v2_7_1::segment::pid::PID,
        cardinality: Cardinality {
            min: 1,
            max: Max::Bounded(1),
        },
        status: None,
    }),
    Node::Segment(SegmentRef {
        id: "DFT_P11.6-PD1",
        position: 6,
        segment: &crate::legacy::v2_7_1::segment::pd1::PD1,
        cardinality: Cardinality {
            min: 0,
            max: Max::Bounded(1),
        },
        status: None,
    }),
    Node::Segment(SegmentRef {
        id: "DFT_P11.7-ROL",
        position: 7,
        segment: &crate::legacy::v2_7_1::segment::rol::ROL,
        cardinality: Cardinality {
            min: 0,
            max: Max::Unbounded,
        },
        status: None,
    }),
    Node::Segment(SegmentRef {
        id: "DFT_P11.8-PV1",
        position: 8,
        segment: &crate::legacy::v2_7_1::segment::pv1::PV1,
        cardinality: Cardinality {
            min: 0,
            max: Max::Bounded(1),
        },
        status: None,
    }),
    Node::Segment(SegmentRef {
        id: "DFT_P11.9-PV2",
        position: 9,
        segment: &crate::legacy::v2_7_1::segment::pv2::PV2,
        cardinality: Cardinality {
            min: 0,
            max: Max::Bounded(1),
        },
        status: None,
    }),
    Node::Segment(SegmentRef {
        id: "DFT_P11.10-ROL",
        position: 10,
        segment: &crate::legacy::v2_7_1::segment::rol::ROL,
        cardinality: Cardinality {
            min: 0,
            max: Max::Unbounded,
        },
        status: None,
    }),
    Node::Segment(SegmentRef {
        id: "DFT_P11.11-DB1",
        position: 11,
        segment: &crate::segment::db1::DB1,
        cardinality: Cardinality {
            min: 0,
            max: Max::Unbounded,
        },
        status: None,
    }),
    Node::Group(Group {
        id: "DFT_P11.12-COMMON_ORDER",
        position: 12,
        name: "COMMON_ORDER",
        cardinality: Cardinality {
            min: 0,
            max: Max::Unbounded,
        },
        kind: GroupKind::Sequence,
        children: &[
            Node::Segment(SegmentRef {
                id: "DFT_P11.12-COMMON_ORDER.1-ORC",
                position: 1,
                segment: &crate::legacy::v2_7_1::segment::orc::ORC,
                cardinality: Cardinality {
                    min: 0,
                    max: Max::Bounded(1),
                },
                status: None,
            }),
            Node::Group(Group {
                id: "DFT_P11.12-COMMON_ORDER.2-TIMING_QUANTITY",
                position: 2,
                name: "TIMING_QUANTITY",
                cardinality: Cardinality {
                    min: 0,
                    max: Max::Unbounded,
                },
                kind: GroupKind::Sequence,
                children: &[
                    Node::Segment(SegmentRef {
                        id: "DFT_P11.12-COMMON_ORDER.2-TIMING_QUANTITY.1-TQ1",
                        position: 1,
                        segment: &crate::segment::tq1::TQ1,
                        cardinality: Cardinality {
                            min: 1,
                            max: Max::Bounded(1),
                        },
                        status: None,
                    }),
                    Node::Segment(SegmentRef {
                        id: "DFT_P11.12-COMMON_ORDER.2-TIMING_QUANTITY.2-TQ2",
                        position: 2,
                        segment: &crate::segment::tq2::TQ2,
                        cardinality: Cardinality {
                            min: 0,
                            max: Max::Unbounded,
                        },
                        status: None,
                    }),
                ],
            }),
            Node::Group(Group {
                id: "DFT_P11.12-COMMON_ORDER.3-ORDER",
                position: 3,
                name: "ORDER",
                cardinality: Cardinality {
                    min: 0,
                    max: Max::Bounded(1),
                },
                kind: GroupKind::Sequence,
                children: &[
                    Node::Segment(SegmentRef {
                        id: "DFT_P11.12-COMMON_ORDER.3-ORDER.1-OBR",
                        position: 1,
                        segment: &crate::legacy::v2_7_1::segment::obr::OBR,
                        cardinality: Cardinality {
                            min: 1,
                            max: Max::Bounded(1),
                        },
                        status: None,
                    }),
                    Node::Segment(SegmentRef {
                        id: "DFT_P11.12-COMMON_ORDER.3-ORDER.2-NTE",
                        position: 2,
                        segment: &crate::legacy::v2_7_1::segment::nte::NTE,
                        cardinality: Cardinality {
                            min: 0,
                            max: Max::Unbounded,
                        },
                        status: None,
                    }),
                ],
            }),
            Node::Group(Group {
                id: "DFT_P11.12-COMMON_ORDER.4-OBSERVATION",
                position: 4,
                name: "OBSERVATION",
                cardinality: Cardinality {
                    min: 0,
                    max: Max::Unbounded,
                },
                kind: GroupKind::Sequence,
                children: &[
                    Node::Segment(SegmentRef {
                        id: "DFT_P11.12-COMMON_ORDER.4-OBSERVATION.1-OBX",
                        position: 1,
                        segment: &crate::legacy::v2_7_1::segment::obx::OBX,
                        cardinality: Cardinality {
                            min: 1,
                            max: Max::Bounded(1),
                        },
                        status: None,
                    }),
                    Node::Segment(SegmentRef {
                        id: "DFT_P11.12-COMMON_ORDER.4-OBSERVATION.2-NTE",
                        position: 2,
                        segment: &crate::legacy::v2_7_1::segment::nte::NTE,
                        cardinality: Cardinality {
                            min: 0,
                            max: Max::Unbounded,
                        },
                        status: None,
                    }),
                ],
            }),
        ],
    }),
    Node::Segment(SegmentRef {
        id: "DFT_P11.13-DG1",
        position: 13,
        segment: &crate::legacy::v2_7_1::segment::dg1::DG1,
        cardinality: Cardinality {
            min: 0,
            max: Max::Unbounded,
        },
        status: None,
    }),
    Node::Segment(SegmentRef {
        id: "DFT_P11.14-DRG",
        position: 14,
        segment: &crate::segment::drg::DRG,
        cardinality: Cardinality {
            min: 0,
            max: Max::Bounded(1),
        },
        status: None,
    }),
    Node::Segment(SegmentRef {
        id: "DFT_P11.15-GT1",
        position: 15,
        segment: &crate::legacy::v2_7_1::segment::gt1::GT1,
        cardinality: Cardinality {
            min: 0,
            max: Max::Unbounded,
        },
        status: None,
    }),
    Node::Group(Group {
        id: "DFT_P11.16-INSURANCE",
        position: 16,
        name: "INSURANCE",
        cardinality: Cardinality {
            min: 0,
            max: Max::Unbounded,
        },
        kind: GroupKind::Sequence,
        children: &[
            Node::Segment(SegmentRef {
                id: "DFT_P11.16-INSURANCE.1-IN1",
                position: 1,
                segment: &crate::legacy::v2_7_1::segment::in1::IN1,
                cardinality: Cardinality {
                    min: 1,
                    max: Max::Bounded(1),
                },
                status: None,
            }),
            Node::Segment(SegmentRef {
                id: "DFT_P11.16-INSURANCE.2-IN2",
                position: 2,
                segment: &crate::legacy::v2_7_1::segment::in2::IN2,
                cardinality: Cardinality {
                    min: 0,
                    max: Max::Bounded(1),
                },
                status: None,
            }),
            Node::Segment(SegmentRef {
                id: "DFT_P11.16-INSURANCE.3-IN3",
                position: 3,
                segment: &crate::legacy::v2_7_1::segment::in3::IN3,
                cardinality: Cardinality {
                    min: 0,
                    max: Max::Unbounded,
                },
                status: None,
            }),
            Node::Segment(SegmentRef {
                id: "DFT_P11.16-INSURANCE.4-ROL",
                position: 4,
                segment: &crate::legacy::v2_7_1::segment::rol::ROL,
                cardinality: Cardinality {
                    min: 0,
                    max: Max::Unbounded,
                },
                status: None,
            }),
        ],
    }),
    Node::Segment(SegmentRef {
        id: "DFT_P11.17-ACC",
        position: 17,
        segment: &crate::legacy::v2_7_1::segment::acc::ACC,
        cardinality: Cardinality {
            min: 0,
            max: Max::Bounded(1),
        },
        status: None,
    }),
    Node::Group(Group {
        id: "DFT_P11.18-FINANCIAL",
        position: 18,
        name: "FINANCIAL",
        cardinality: Cardinality {
            min: 1,
            max: Max::Unbounded,
        },
        kind: GroupKind::Sequence,
        children: &[
            Node::Segment(SegmentRef {
                id: "DFT_P11.18-FINANCIAL.1-FT1",
                position: 1,
                segment: &crate::legacy::v2_7_1::segment::ft1::FT1,
                cardinality: Cardinality {
                    min: 1,
                    max: Max::Bounded(1),
                },
                status: None,
            }),
            Node::Group(Group {
                id: "DFT_P11.18-FINANCIAL.2-FINANCIAL_PROCEDURE",
                position: 2,
                name: "FINANCIAL_PROCEDURE",
                cardinality: Cardinality {
                    min: 0,
                    max: Max::Unbounded,
                },
                kind: GroupKind::Sequence,
                children: &[
                    Node::Segment(SegmentRef {
                        id: "DFT_P11.18-FINANCIAL.2-FINANCIAL_PROCEDURE.1-PR1",
                        position: 1,
                        segment: &crate::legacy::v2_7_1::segment::pr1::PR1,
                        cardinality: Cardinality {
                            min: 1,
                            max: Max::Bounded(1),
                        },
                        status: None,
                    }),
                    Node::Segment(SegmentRef {
                        id: "DFT_P11.18-FINANCIAL.2-FINANCIAL_PROCEDURE.2-ROL",
                        position: 2,
                        segment: &crate::legacy::v2_7_1::segment::rol::ROL,
                        cardinality: Cardinality {
                            min: 0,
                            max: Max::Unbounded,
                        },
                        status: None,
                    }),
                ],
            }),
            Node::Group(Group {
                id: "DFT_P11.18-FINANCIAL.3-FINANCIAL_COMMON_ORDER",
                position: 3,
                name: "FINANCIAL_COMMON_ORDER",
                cardinality: Cardinality {
                    min: 0,
                    max: Max::Unbounded,
                },
                kind: GroupKind::Sequence,
                children: &[
                    Node::Segment(SegmentRef {
                        id: "DFT_P11.18-FINANCIAL.3-FINANCIAL_COMMON_ORDER.1-ORC",
                        position: 1,
                        segment: &crate::legacy::v2_7_1::segment::orc::ORC,
                        cardinality: Cardinality {
                            min: 0,
                            max: Max::Bounded(1),
                        },
                        status: None,
                    }),
                    Node::Group(Group {
                        id: "DFT_P11.18-FINANCIAL.3-FINANCIAL_COMMON_ORDER.2-FINANCIAL_TIMING_QUANTITY",
                        position: 2,
                        name: "FINANCIAL_TIMING_QUANTITY",
                        cardinality: Cardinality {
                            min: 0,
                            max: Max::Unbounded,
                        },
                        kind: GroupKind::Sequence,
                        children: &[
                            Node::Segment(SegmentRef {
                                id: "DFT_P11.18-FINANCIAL.3-FINANCIAL_COMMON_ORDER.2-FINANCIAL_TIMING_QUANTITY.1-TQ1",
                                position: 1,
                                segment: &crate::segment::tq1::TQ1,
                                cardinality: Cardinality {
                                    min: 1,
                                    max: Max::Bounded(1),
                                },
                                status: None,
                            }),
                            Node::Segment(SegmentRef {
                                id: "DFT_P11.18-FINANCIAL.3-FINANCIAL_COMMON_ORDER.2-FINANCIAL_TIMING_QUANTITY.2-TQ2",
                                position: 2,
                                segment: &crate::segment::tq2::TQ2,
                                cardinality: Cardinality {
                                    min: 0,
                                    max: Max::Unbounded,
                                },
                                status: None,
                            }),
                        ],
                    }),
                    Node::Group(Group {
                        id: "DFT_P11.18-FINANCIAL.3-FINANCIAL_COMMON_ORDER.3-FINANCIAL_ORDER",
                        position: 3,
                        name: "FINANCIAL_ORDER",
                        cardinality: Cardinality {
                            min: 0,
                            max: Max::Bounded(1),
                        },
                        kind: GroupKind::Sequence,
                        children: &[
                            Node::Segment(SegmentRef {
                                id: "DFT_P11.18-FINANCIAL.3-FINANCIAL_COMMON_ORDER.3-FINANCIAL_ORDER.1-OBR",
                                position: 1,
                                segment: &crate::legacy::v2_7_1::segment::obr::OBR,
                                cardinality: Cardinality {
                                    min: 1,
                                    max: Max::Bounded(1),
                                },
                                status: None,
                            }),
                            Node::Segment(SegmentRef {
                                id: "DFT_P11.18-FINANCIAL.3-FINANCIAL_COMMON_ORDER.3-FINANCIAL_ORDER.2-NTE",
                                position: 2,
                                segment: &crate::legacy::v2_7_1::segment::nte::NTE,
                                cardinality: Cardinality {
                                    min: 0,
                                    max: Max::Unbounded,
                                },
                                status: None,
                            }),
                        ],
                    }),
                    Node::Group(Group {
                        id: "DFT_P11.18-FINANCIAL.3-FINANCIAL_COMMON_ORDER.4-FINANCIAL_OBSERVATION",
                        position: 4,
                        name: "FINANCIAL_OBSERVATION",
                        cardinality: Cardinality {
                            min: 0,
                            max: Max::Unbounded,
                        },
                        kind: GroupKind::Sequence,
                        children: &[
                            Node::Segment(SegmentRef {
                                id: "DFT_P11.18-FINANCIAL.3-FINANCIAL_COMMON_ORDER.4-FINANCIAL_OBSERVATION.1-OBX",
                                position: 1,
                                segment: &crate::legacy::v2_7_1::segment::obx::OBX,
                                cardinality: Cardinality {
                                    min: 1,
                                    max: Max::Bounded(1),
                                },
                                status: None,
                            }),
                            Node::Segment(SegmentRef {
                                id: "DFT_P11.18-FINANCIAL.3-FINANCIAL_COMMON_ORDER.4-FINANCIAL_OBSERVATION.2-NTE",
                                position: 2,
                                segment: &crate::legacy::v2_7_1::segment::nte::NTE,
                                cardinality: Cardinality {
                                    min: 0,
                                    max: Max::Unbounded,
                                },
                                status: None,
                            }),
                        ],
                    }),
                ],
            }),
            Node::Segment(SegmentRef {
                id: "DFT_P11.18-FINANCIAL.4-DG1",
                position: 4,
                segment: &crate::legacy::v2_7_1::segment::dg1::DG1,
                cardinality: Cardinality {
                    min: 0,
                    max: Max::Unbounded,
                },
                status: None,
            }),
            Node::Segment(SegmentRef {
                id: "DFT_P11.18-FINANCIAL.5-DRG",
                position: 5,
                segment: &crate::segment::drg::DRG,
                cardinality: Cardinality {
                    min: 0,
                    max: Max::Bounded(1),
                },
                status: None,
            }),
            Node::Segment(SegmentRef {
                id: "DFT_P11.18-FINANCIAL.6-GT1",
                position: 6,
                segment: &crate::legacy::v2_7_1::segment::gt1::GT1,
                cardinality: Cardinality {
                    min: 0,
                    max: Max::Unbounded,
                },
                status: None,
            }),
            Node::Group(Group {
                id: "DFT_P11.18-FINANCIAL.7-FINANCIAL_INSURANCE",
                position: 7,
                name: "FINANCIAL_INSURANCE",
                cardinality: Cardinality {
                    min: 0,
                    max: Max::Unbounded,
                },
                kind: GroupKind::Sequence,
                children: &[
                    Node::Segment(SegmentRef {
                        id: "DFT_P11.18-FINANCIAL.7-FINANCIAL_INSURANCE.1-IN1",
                        position: 1,
                        segment: &crate::legacy::v2_7_1::segment::in1::IN1,
                        cardinality: Cardinality {
                            min: 1,
                            max: Max::Bounded(1),
                        },
                        status: None,
                    }),
                    Node::Segment(SegmentRef {
                        id: "DFT_P11.18-FINANCIAL.7-FINANCIAL_INSURANCE.2-IN2",
                        position: 2,
                        segment: &crate::legacy::v2_7_1::segment::in2::IN2,
                        cardinality: Cardinality {
                            min: 0,
                            max: Max::Bounded(1),
                        },
                        status: None,
                    }),
                    Node::Segment(SegmentRef {
                        id: "DFT_P11.18-FINANCIAL.7-FINANCIAL_INSURANCE.3-IN3",
                        position: 3,
                        segment: &crate::legacy::v2_7_1::segment::in3::IN3,
                        cardinality: Cardinality {
                            min: 0,
                            max: Max::Unbounded,
                        },
                        status: None,
                    }),
                    Node::Segment(SegmentRef {
                        id: "DFT_P11.18-FINANCIAL.7-FINANCIAL_INSURANCE.4-ROL",
                        position: 4,
                        segment: &crate::legacy::v2_7_1::segment::rol::ROL,
                        cardinality: Cardinality {
                            min: 0,
                            max: Max::Unbounded,
                        },
                        status: None,
                    }),
                ],
            }),
        ],
    }),
];

/// The `DFT_P11` message structure of the 2.7.1 tables.
pub static DFT_P11: Structure = Structure {
    id: "DFT_P11",
    url: None,
    version: "2.7.1",
    withdrawn_as_of: None,
    nodes: &DFT_P11_NODES,
};
