// @generated by fhir-codegen from HL7/v2ig 3adcdbfff654ccbff5cd33aa34bd909a087e8e19 input/sourceOfTruth. DO NOT EDIT.
// Change the emitter (tools/fhir-codegen) and regenerate.
// SPDX-FileCopyrightText: Vernum Projecten B.V.
// SPDX-License-Identifier: Apache-2.0
//! The `BLC` segment: Blood Code.

use crate::data_type;
use crate::model::{Cardinality, DataTypeRef, Field, Max, Optionality, Segment, Table};

/// The `BLC` segment definition, `http://hl7.org/v2/StructureDefinition/BLC`.
pub static BLC: Segment = Segment {
    id: "BLC",
    url: "http://hl7.org/v2/StructureDefinition/BLC",
    name: "Blood Code",
    fields: &[
        Field {
            id: "BLC.1-bloodProductCode",
            position: 1,
            name: "Blood Product Code",
            data_type: Some(DataTypeRef::Defined(&data_type::cwe::CWE)),
            cardinality: Cardinality {
                min: 0,
                max: Max::Bounded(1),
            },
            optionality: Optionality::O,
            length: None,
            conformance_length: None,
            table: Some(Table {
                id: "0426",
                value_set: "http://terminology.hl7.org/ValueSet/v2-0426",
            }),
            standards_status: None,
        },
        Field {
            id: "BLC.2-bloodAmount",
            position: 2,
            name: "Blood Amount",
            data_type: Some(DataTypeRef::Defined(&data_type::cq::CQ)),
            cardinality: Cardinality {
                min: 0,
                max: Max::Bounded(1),
            },
            optionality: Optionality::O,
            length: None,
            conformance_length: None,
            table: None,
            standards_status: None,
        },
    ],
};
