// @generated by fhir-codegen from HL7/v2ig 3adcdbfff654ccbff5cd33aa34bd909a087e8e19 input/sourceOfTruth. DO NOT EDIT.
// Change the emitter (tools/fhir-codegen) and regenerate.
// SPDX-FileCopyrightText: Vernum Projecten B.V.
// SPDX-License-Identifier: Apache-2.0
//! The `LAN` segment: Language Detail.

use crate::data_type;
use crate::model::{Cardinality, DataTypeRef, Field, Length, Max, Optionality, Segment, Table};

/// The `LAN` segment definition, `http://hl7.org/v2/StructureDefinition/LAN`.
pub static LAN: Segment = Segment {
    id: "LAN",
    url: "http://hl7.org/v2/StructureDefinition/LAN",
    name: "Language Detail",
    fields: &[
        Field {
            id: "LAN.1-setId",
            position: 1,
            name: "Set ID – LAN",
            data_type: Some(DataTypeRef::Defined(&data_type::si::SI)),
            cardinality: Cardinality {
                min: 1,
                max: Max::Bounded(1),
            },
            optionality: Optionality::R,
            length: Some(Length {
                min: 1,
                max: Some(4),
            }),
            conformance_length: None,
            table: None,
            standards_status: None,
        },
        Field {
            id: "LAN.2-languageCode",
            position: 2,
            name: "Language Code",
            data_type: Some(DataTypeRef::Defined(&data_type::cwe::CWE)),
            cardinality: Cardinality {
                min: 1,
                max: Max::Bounded(1),
            },
            optionality: Optionality::R,
            length: None,
            conformance_length: None,
            table: Some(Table {
                id: "0296",
                value_set: "http://terminology.hl7.org/ValueSet/v2-0296",
            }),
            standards_status: None,
        },
        Field {
            id: "LAN.3-languageAbilityCode",
            position: 3,
            name: "Language Ability Code",
            data_type: Some(DataTypeRef::Defined(&data_type::cwe::CWE)),
            cardinality: Cardinality {
                min: 0,
                max: Max::Unbounded,
            },
            optionality: Optionality::O,
            length: None,
            conformance_length: None,
            table: Some(Table {
                id: "0403",
                value_set: "http://terminology.hl7.org/ValueSet/v2-0403",
            }),
            standards_status: None,
        },
        Field {
            id: "LAN.4-languageProficiencyCode",
            position: 4,
            name: "Language Proficiency Code",
            data_type: Some(DataTypeRef::Defined(&data_type::cwe::CWE)),
            cardinality: Cardinality {
                min: 0,
                max: Max::Bounded(1),
            },
            optionality: Optionality::O,
            length: None,
            conformance_length: None,
            table: Some(Table {
                id: "0404",
                value_set: "http://terminology.hl7.org/ValueSet/v2-0404",
            }),
            standards_status: None,
        },
    ],
};
