// @generated by fhir-codegen from HL7/v2ig 3adcdbfff654ccbff5cd33aa34bd909a087e8e19 input/sourceOfTruth. DO NOT EDIT.
// Change the emitter (tools/fhir-codegen) and regenerate.
// SPDX-FileCopyrightText: Vernum Projecten B.V.
// SPDX-License-Identifier: Apache-2.0
//! The `MFA` segment: Master File Acknowledgment.

use crate::data_type;
use crate::model::{
    Cardinality, ConformanceLength, DataTypeRef, Field, Length, Max, Optionality, Segment, Table,
};

/// The `MFA` segment definition, `http://hl7.org/v2/StructureDefinition/MFA`.
pub static MFA: Segment = Segment {
    id: "MFA",
    url: "http://hl7.org/v2/StructureDefinition/MFA",
    name: "Master File Acknowledgment",
    fields: &[
        Field {
            id: "MFA.1-recordLevelEventCode",
            position: 1,
            name: "Record-Level Event Code",
            data_type: Some(DataTypeRef::Defined(&data_type::id::ID)),
            cardinality: Cardinality {
                min: 1,
                max: Max::Bounded(1),
            },
            optionality: Optionality::R,
            length: Some(Length {
                min: 3,
                max: Some(3),
            }),
            conformance_length: None,
            table: Some(Table {
                id: "0180",
                value_set: "http://terminology.hl7.org/ValueSet/v2-0180",
            }),
            standards_status: None,
        },
        Field {
            id: "MFA.2-mfnControlId",
            position: 2,
            name: "MFN Control ID",
            data_type: Some(DataTypeRef::Defined(&data_type::st::ST)),
            cardinality: Cardinality {
                min: 0,
                max: Max::Bounded(1),
            },
            optionality: Optionality::C,
            length: None,
            conformance_length: Some(ConformanceLength {
                length: Some(20),
                no_truncate: Some(true),
            }),
            table: None,
            standards_status: None,
        },
        Field {
            id: "MFA.3-eventCompletionDateTime",
            position: 3,
            name: "Event Completion Date/Time",
            data_type: Some(DataTypeRef::Defined(&data_type::dtm::DTM)),
            cardinality: Cardinality {
                min: 0,
                max: Max::Bounded(1),
            },
            optionality: Optionality::O,
            length: None,
            conformance_length: None,
            table: None,
            standards_status: None,
        },
        Field {
            id: "MFA.4-mfnRecordLevelErrorReturn",
            position: 4,
            name: "MFN Record Level Error Return",
            data_type: Some(DataTypeRef::Defined(&data_type::cwe::CWE)),
            cardinality: Cardinality {
                min: 1,
                max: Max::Bounded(1),
            },
            optionality: Optionality::R,
            length: None,
            conformance_length: None,
            table: Some(Table {
                id: "0181",
                value_set: "http://terminology.hl7.org/ValueSet/v2-0181",
            }),
            standards_status: None,
        },
        Field {
            id: "MFA.5-primaryKeyValue",
            position: 5,
            name: "Primary Key Value - MFA",
            data_type: Some(DataTypeRef::Undefined("Varies")),
            cardinality: Cardinality {
                min: 1,
                max: Max::Unbounded,
            },
            optionality: Optionality::R,
            length: None,
            conformance_length: None,
            table: Some(Table {
                id: "0607",
                value_set: "http://terminology.hl7.org/ValueSet/v2-0607",
            }),
            standards_status: None,
        },
        Field {
            id: "MFA.6-primaryKeyValueType",
            position: 6,
            name: "Primary Key Value Type - MFA",
            data_type: Some(DataTypeRef::Defined(&data_type::id::ID)),
            cardinality: Cardinality {
                min: 1,
                max: Max::Unbounded,
            },
            optionality: Optionality::R,
            length: Some(Length {
                min: 2,
                max: Some(3),
            }),
            conformance_length: None,
            table: Some(Table {
                id: "0355",
                value_set: "http://terminology.hl7.org/ValueSet/v2-0355",
            }),
            standards_status: None,
        },
    ],
};
