// @generated by fhir-codegen from HL7/v2ig 3adcdbfff654ccbff5cd33aa34bd909a087e8e19 input/sourceOfTruth. DO NOT EDIT.
// Change the emitter (tools/fhir-codegen) and regenerate.
// SPDX-FileCopyrightText: Vernum Projecten B.V.
// SPDX-License-Identifier: Apache-2.0
//! The `OH1` segment: Person Employment Status.

use crate::data_type;
use crate::model::{Cardinality, DataTypeRef, Field, Length, Max, Optionality, Segment, Table};

/// The `OH1` segment definition, `http://hl7.org/v2/StructureDefinition/OH1`.
pub static OH1: Segment = Segment {
    id: "OH1",
    url: Some("http://hl7.org/v2/StructureDefinition/OH1"),
    name: "Person Employment Status",
    fields: &[
        Field {
            id: "OH1.1-setId",
            position: 1,
            name: "Set ID",
            data_type: Some(DataTypeRef::Defined(&data_type::si::SI)),
            cardinality: Cardinality {
                min: 1,
                max: Max::Bounded(1),
            },
            optionality: Optionality::R,
            length: None,
            conformance_length: None,
            table: None,
            standards_status: None,
        },
        Field {
            id: "OH1.2-actionCode",
            position: 2,
            name: "Action Code",
            data_type: Some(DataTypeRef::Defined(&data_type::id::ID)),
            cardinality: Cardinality {
                min: 0,
                max: Max::Bounded(1),
            },
            optionality: Optionality::O,
            length: Some(Length {
                min: 1,
                max: Some(1),
            }),
            conformance_length: None,
            table: Some(Table {
                id: "0206",
                value_set: "http://terminology.hl7.org/ValueSet/v2-0206",
            }),
            standards_status: None,
        },
        Field {
            id: "OH1.3-employmentStatus",
            position: 3,
            name: "Employment Status",
            data_type: Some(DataTypeRef::Defined(&data_type::cwe::CWE)),
            cardinality: Cardinality {
                min: 1,
                max: Max::Bounded(1),
            },
            optionality: Optionality::R,
            length: None,
            conformance_length: None,
            table: Some(Table {
                id: "0957",
                value_set: "http://terminology.hl7.org/ValueSet/v2-0957",
            }),
            standards_status: None,
        },
        Field {
            id: "OH1.4-employmentStatusStartDate",
            position: 4,
            name: "Employment Status Start Date",
            data_type: Some(DataTypeRef::Defined(&data_type::dt::DT)),
            cardinality: Cardinality {
                min: 0,
                max: Max::Bounded(1),
            },
            optionality: Optionality::O,
            length: None,
            conformance_length: None,
            table: None,
            standards_status: None,
        },
        Field {
            id: "OH1.5-employmentStatusEndDate",
            position: 5,
            name: "Employment Status End Date",
            data_type: Some(DataTypeRef::Defined(&data_type::dt::DT)),
            cardinality: Cardinality {
                min: 0,
                max: Max::Bounded(1),
            },
            optionality: Optionality::O,
            length: None,
            conformance_length: None,
            table: None,
            standards_status: None,
        },
        Field {
            id: "OH1.6-enteredDate",
            position: 6,
            name: "Entered Date",
            data_type: Some(DataTypeRef::Defined(&data_type::dt::DT)),
            cardinality: Cardinality {
                min: 1,
                max: Max::Bounded(1),
            },
            optionality: Optionality::R,
            length: None,
            conformance_length: None,
            table: None,
            standards_status: None,
        },
        Field {
            id: "OH1.7-employmentStatusUniqueIdentifier",
            position: 7,
            name: "Employment Status Unique Identifier",
            data_type: Some(DataTypeRef::Defined(&data_type::ei::EI)),
            cardinality: Cardinality {
                min: 0,
                max: Max::Bounded(1),
            },
            optionality: Optionality::O,
            length: None,
            conformance_length: None,
            table: None,
            standards_status: None,
        },
    ],
};
