// @generated by fhir-codegen from HL7/v2ig 3adcdbfff654ccbff5cd33aa34bd909a087e8e19 input/sourceOfTruth. DO NOT EDIT.
// Change the emitter (tools/fhir-codegen) and regenerate.
// SPDX-FileCopyrightText: Vernum Projecten B.V.
// SPDX-License-Identifier: Apache-2.0
//! The `OM3` segment: Categorical Service/Test/Observation.

use crate::model::{
    Cardinality, ConformanceLength, Field, Length, Max, Optionality, Segment, Table,
};

/// The `OM3` segment definition, `http://hl7.org/v2/StructureDefinition/OM3`.
pub static OM3: Segment = Segment {
    id: "OM3",
    url: "http://hl7.org/v2/StructureDefinition/OM3",
    name: "Categorical Service/Test/Observation",
    fields: &[
        Field {
            id: "OM3.1-sequenceNumberTestObservationMasterFile",
            position: 1,
            name: "Sequence Number - Test/Observation Master File",
            data_type: Some("NM"),
            cardinality: Cardinality {
                min: 0,
                max: Max::Bounded(1),
            },
            optionality: Optionality::O,
            length: None,
            conformance_length: Some(ConformanceLength {
                length: Some(4),
                no_truncate: Some(true),
            }),
            table: None,
            standards_status: None,
        },
        Field {
            id: "OM3.2-preferredCodingSystem",
            position: 2,
            name: "Preferred Coding System",
            data_type: Some("CWE"),
            cardinality: Cardinality {
                min: 0,
                max: Max::Bounded(1),
            },
            optionality: Optionality::O,
            length: None,
            conformance_length: None,
            table: Some(Table {
                id: "0650",
                value_set: "http://terminology.hl7.org/ValueSet/v2-0650",
            }),
            standards_status: None,
        },
        Field {
            id: "OM3.3-validCodedAnswers",
            position: 3,
            name: "Valid Coded \"Answers\"",
            data_type: Some("CWE"),
            cardinality: Cardinality {
                min: 0,
                max: Max::Unbounded,
            },
            optionality: Optionality::O,
            length: None,
            conformance_length: None,
            table: Some(Table {
                id: "0652",
                value_set: "http://terminology.hl7.org/ValueSet/v2-0652",
            }),
            standards_status: None,
        },
        Field {
            id: "OM3.4-normalTextCodesForCategoricalObservations",
            position: 4,
            name: "Normal Text/Codes for Categorical Observations",
            data_type: Some("CWE"),
            cardinality: Cardinality {
                min: 0,
                max: Max::Unbounded,
            },
            optionality: Optionality::O,
            length: None,
            conformance_length: None,
            table: Some(Table {
                id: "0654",
                value_set: "http://terminology.hl7.org/ValueSet/v2-0654",
            }),
            standards_status: None,
        },
        Field {
            id: "OM3.5-abnormalTextCodesForCategoricalObservations",
            position: 5,
            name: "Abnormal Text/Codes for Categorical Observations",
            data_type: Some("CWE"),
            cardinality: Cardinality {
                min: 0,
                max: Max::Unbounded,
            },
            optionality: Optionality::O,
            length: None,
            conformance_length: None,
            table: Some(Table {
                id: "0655",
                value_set: "http://terminology.hl7.org/ValueSet/v2-0655",
            }),
            standards_status: None,
        },
        Field {
            id: "OM3.6-criticalTextCodesForCategoricalObservations",
            position: 6,
            name: "Critical Text/Codes for Categorical Observations",
            data_type: Some("CWE"),
            cardinality: Cardinality {
                min: 0,
                max: Max::Unbounded,
            },
            optionality: Optionality::O,
            length: None,
            conformance_length: None,
            table: Some(Table {
                id: "0656",
                value_set: "http://terminology.hl7.org/ValueSet/v2-0656",
            }),
            standards_status: None,
        },
        Field {
            id: "OM3.7-valueType",
            position: 7,
            name: "Value Type",
            data_type: Some("ID"),
            cardinality: Cardinality {
                min: 0,
                max: Max::Bounded(1),
            },
            optionality: Optionality::O,
            length: Some(Length {
                min: 2,
                max: Some(3),
            }),
            conformance_length: None,
            table: Some(Table {
                id: "0125",
                value_set: "http://terminology.hl7.org/ValueSet/v2-0125",
            }),
            standards_status: None,
        },
    ],
};
