// @generated by fhir-codegen from HL7/v2ig 3adcdbfff654ccbff5cd33aa34bd909a087e8e19 input/sourceOfTruth. DO NOT EDIT.
// Change the emitter (tools/fhir-codegen) and regenerate.
// SPDX-FileCopyrightText: Vernum Projecten B.V.
// SPDX-License-Identifier: Apache-2.0
//! The `TCD` segment: Test Code Detail.

use crate::data_type;
use crate::model::{Cardinality, DataTypeRef, Field, Length, Max, Optionality, Segment, Table};

/// The `TCD` segment definition, `http://hl7.org/v2/StructureDefinition/TCD`.
pub static TCD: Segment = Segment {
    id: "TCD",
    url: Some("http://hl7.org/v2/StructureDefinition/TCD"),
    name: "Test Code Detail",
    fields: &[
        Field {
            id: "TCD.1-tcd1",
            position: 1,
            name: "TCD-1",
            data_type: Some(DataTypeRef::Defined(&data_type::cwe::CWE)),
            cardinality: Cardinality {
                min: 1,
                max: Max::Bounded(1),
            },
            optionality: Optionality::R,
            length: None,
            conformance_length: None,
            table: Some(Table {
                id: "0789",
                value_set: "http://terminology.hl7.org/ValueSet/v2-0789",
            }),
            standards_status: None,
        },
        Field {
            id: "TCD.2-tcd2",
            position: 2,
            name: "TCD-2",
            data_type: Some(DataTypeRef::Defined(&data_type::sn::SN)),
            cardinality: Cardinality {
                min: 0,
                max: Max::Bounded(1),
            },
            optionality: Optionality::O,
            length: None,
            conformance_length: None,
            table: None,
            standards_status: None,
        },
        Field {
            id: "TCD.3-tcd3",
            position: 3,
            name: "TCD-3",
            data_type: Some(DataTypeRef::Defined(&data_type::sn::SN)),
            cardinality: Cardinality {
                min: 0,
                max: Max::Bounded(1),
            },
            optionality: Optionality::O,
            length: None,
            conformance_length: None,
            table: None,
            standards_status: None,
        },
        Field {
            id: "TCD.4-tcd4",
            position: 4,
            name: "TCD-4",
            data_type: Some(DataTypeRef::Defined(&data_type::sn::SN)),
            cardinality: Cardinality {
                min: 0,
                max: Max::Bounded(1),
            },
            optionality: Optionality::O,
            length: None,
            conformance_length: None,
            table: None,
            standards_status: None,
        },
        Field {
            id: "TCD.5-tcd5",
            position: 5,
            name: "TCD-5",
            data_type: Some(DataTypeRef::Defined(&data_type::sn::SN)),
            cardinality: Cardinality {
                min: 0,
                max: Max::Bounded(1),
            },
            optionality: Optionality::O,
            length: None,
            conformance_length: None,
            table: None,
            standards_status: None,
        },
        Field {
            id: "TCD.6-tcd6",
            position: 6,
            name: "TCD-6",
            data_type: Some(DataTypeRef::Defined(&data_type::id::ID)),
            cardinality: Cardinality {
                min: 0,
                max: Max::Bounded(1),
            },
            optionality: Optionality::O,
            length: Some(Length {
                min: 1,
                max: Some(1),
            }),
            conformance_length: None,
            table: Some(Table {
                id: "0136",
                value_set: "http://terminology.hl7.org/ValueSet/v2-0136",
            }),
            standards_status: None,
        },
        Field {
            id: "TCD.7-tcd7",
            position: 7,
            name: "TCD-7",
            data_type: Some(DataTypeRef::Defined(&data_type::id::ID)),
            cardinality: Cardinality {
                min: 0,
                max: Max::Bounded(1),
            },
            optionality: Optionality::O,
            length: Some(Length {
                min: 1,
                max: Some(1),
            }),
            conformance_length: None,
            table: Some(Table {
                id: "0136",
                value_set: "http://terminology.hl7.org/ValueSet/v2-0136",
            }),
            standards_status: None,
        },
        Field {
            id: "TCD.8-tcd8",
            position: 8,
            name: "TCD-8",
            data_type: Some(DataTypeRef::Defined(&data_type::cwe::CWE)),
            cardinality: Cardinality {
                min: 0,
                max: Max::Bounded(1),
            },
            optionality: Optionality::O,
            length: None,
            conformance_length: None,
            table: Some(Table {
                id: "0389",
                value_set: "http://terminology.hl7.org/ValueSet/v2-0389",
            }),
            standards_status: None,
        },
        Field {
            id: "TCD.9-tcd9",
            position: 9,
            name: "TCD-9",
            data_type: Some(DataTypeRef::Defined(&data_type::cq::CQ)),
            cardinality: Cardinality {
                min: 0,
                max: Max::Bounded(1),
            },
            optionality: Optionality::O,
            length: None,
            conformance_length: None,
            table: None,
            standards_status: None,
        },
        Field {
            id: "TCD.10-tcd10",
            position: 10,
            name: "TCD-10",
            data_type: Some(DataTypeRef::Defined(&data_type::nm::NM)),
            cardinality: Cardinality {
                min: 0,
                max: Max::Bounded(1),
            },
            optionality: Optionality::O,
            length: None,
            conformance_length: None,
            table: None,
            standards_status: None,
        },
        Field {
            id: "TCD.11-tcd11",
            position: 11,
            name: "TCD-11",
            data_type: Some(DataTypeRef::Defined(&data_type::cwe::CWE)),
            cardinality: Cardinality {
                min: 0,
                max: Max::Bounded(1),
            },
            optionality: Optionality::O,
            length: None,
            conformance_length: None,
            table: Some(Table {
                id: "0945",
                value_set: "http://terminology.hl7.org/ValueSet/v2-0945",
            }),
            standards_status: None,
        },
    ],
};
