// @generated by fhir-codegen from usnistgov/igamt-hl7Tools-service 83322dffdac18cb129a1bd80149f5439cf5686fd src/main/resources/hl7db. DO NOT EDIT.
// Change the emitter (tools/fhir-codegen) and regenerate.
// SPDX-FileCopyrightText: Vernum Projecten B.V.
// SPDX-License-Identifier: Apache-2.0
//! The `EHC_E21` message structure of the 2.8.2 tables.
//!
//! The tables give it the tree of the 2.8.1 tables, which it links to.

use crate::model::Structure;

/// The `EHC_E21` message structure of the 2.8.2 tables.
pub static EHC_E21: Structure = Structure {
    id: "EHC_E21",
    url: None,
    version: "2.8.2",
    withdrawn_as_of: None,
    nodes: &crate::legacy::v2_8_1::structure::ehc_e21::EHC_E21_NODES,
};
