// @generated by fhir-codegen from usnistgov/igamt-hl7Tools-service 83322dffdac18cb129a1bd80149f5439cf5686fd src/main/resources/hl7db. DO NOT EDIT.
// Change the emitter (tools/fhir-codegen) and regenerate.
// SPDX-FileCopyrightText: Vernum Projecten B.V.
// SPDX-License-Identifier: Apache-2.0
//! The `AIP` segment: Appointment Information - Personnel Resource.

use crate::model::{Cardinality, DataTypeRef, Field, Length, Max, Optionality, Segment, Table};

/// The `AIP` segment of the 2.6 tables.
pub static AIP: Segment = Segment {
    id: "AIP",
    url: None,
    name: "Appointment Information - Personnel Resource",
    fields: &[
        Field {
            id: "AIP.1",
            position: 1,
            name: "Set ID - AIP",
            data_type: Some(DataTypeRef::Legacy(&crate::legacy::v2_6::data_type::SI)),
            cardinality: Cardinality {
                min: 1,
                max: Max::Bounded(1),
            },
            optionality: Optionality::R,
            length: Some(Length {
                min: 0,
                max: Some(4),
            }),
            conformance_length: None,
            table: None,
            standards_status: None,
        },
        Field {
            id: "AIP.2",
            position: 2,
            name: "Segment Action Code",
            data_type: Some(DataTypeRef::Legacy(&crate::legacy::v2_6::data_type::ID)),
            cardinality: Cardinality {
                min: 0,
                max: Max::Bounded(1),
            },
            optionality: Optionality::C,
            length: Some(Length {
                min: 0,
                max: Some(3),
            }),
            conformance_length: None,
            table: Some(Table {
                id: "0206",
                value_set: "http://terminology.hl7.org/ValueSet/v2-0206",
            }),
            standards_status: None,
        },
        Field {
            id: "AIP.3",
            position: 3,
            name: "Personnel Resource ID",
            data_type: Some(DataTypeRef::Legacy(&crate::legacy::v2_6::data_type::XCN)),
            cardinality: Cardinality {
                min: 0,
                max: Max::Unbounded,
            },
            optionality: Optionality::C,
            length: Some(Length {
                min: 0,
                max: Some(250),
            }),
            conformance_length: None,
            table: None,
            standards_status: None,
        },
        Field {
            id: "AIP.4",
            position: 4,
            name: "Resource Type",
            data_type: Some(DataTypeRef::Legacy(&crate::legacy::v2_6::data_type::CWE)),
            cardinality: Cardinality {
                min: 0,
                max: Max::Bounded(1),
            },
            optionality: Optionality::C,
            length: Some(Length {
                min: 0,
                max: Some(250),
            }),
            conformance_length: None,
            table: Some(Table {
                id: "0182",
                value_set: "http://terminology.hl7.org/ValueSet/v2-0182",
            }),
            standards_status: None,
        },
        Field {
            id: "AIP.5",
            position: 5,
            name: "Resource Group",
            data_type: Some(DataTypeRef::Legacy(&crate::legacy::v2_6::data_type::CWE)),
            cardinality: Cardinality {
                min: 0,
                max: Max::Bounded(1),
            },
            optionality: Optionality::O,
            length: Some(Length {
                min: 0,
                max: Some(250),
            }),
            conformance_length: None,
            table: None,
            standards_status: None,
        },
        Field {
            id: "AIP.6",
            position: 6,
            name: "Start Date/Time",
            data_type: Some(DataTypeRef::Legacy(&crate::legacy::v2_6::data_type::DTM)),
            cardinality: Cardinality {
                min: 0,
                max: Max::Bounded(1),
            },
            optionality: Optionality::C,
            length: Some(Length {
                min: 0,
                max: Some(24),
            }),
            conformance_length: None,
            table: None,
            standards_status: None,
        },
        Field {
            id: "AIP.7",
            position: 7,
            name: "Start Date/Time Offset",
            data_type: Some(DataTypeRef::Legacy(&crate::legacy::v2_6::data_type::NM)),
            cardinality: Cardinality {
                min: 0,
                max: Max::Bounded(1),
            },
            optionality: Optionality::C,
            length: Some(Length {
                min: 0,
                max: Some(20),
            }),
            conformance_length: None,
            table: None,
            standards_status: None,
        },
        Field {
            id: "AIP.8",
            position: 8,
            name: "Start Date/Time Offset Units",
            data_type: Some(DataTypeRef::Legacy(&crate::legacy::v2_6::data_type::CNE)),
            cardinality: Cardinality {
                min: 0,
                max: Max::Bounded(1),
            },
            optionality: Optionality::C,
            length: Some(Length {
                min: 0,
                max: Some(250),
            }),
            conformance_length: None,
            table: None,
            standards_status: None,
        },
        Field {
            id: "AIP.9",
            position: 9,
            name: "Duration",
            data_type: Some(DataTypeRef::Legacy(&crate::legacy::v2_6::data_type::NM)),
            cardinality: Cardinality {
                min: 0,
                max: Max::Bounded(1),
            },
            optionality: Optionality::O,
            length: Some(Length {
                min: 0,
                max: Some(20),
            }),
            conformance_length: None,
            table: None,
            standards_status: None,
        },
        Field {
            id: "AIP.10",
            position: 10,
            name: "Duration Units",
            data_type: Some(DataTypeRef::Legacy(&crate::legacy::v2_6::data_type::CNE)),
            cardinality: Cardinality {
                min: 0,
                max: Max::Bounded(1),
            },
            optionality: Optionality::O,
            length: Some(Length {
                min: 0,
                max: Some(250),
            }),
            conformance_length: None,
            table: None,
            standards_status: None,
        },
        Field {
            id: "AIP.11",
            position: 11,
            name: "Allow Substitution Code",
            data_type: Some(DataTypeRef::Legacy(&crate::legacy::v2_6::data_type::IS)),
            cardinality: Cardinality {
                min: 0,
                max: Max::Bounded(1),
            },
            optionality: Optionality::C,
            length: Some(Length {
                min: 0,
                max: Some(10),
            }),
            conformance_length: None,
            table: Some(Table {
                id: "0279",
                value_set: "http://terminology.hl7.org/ValueSet/v2-0279",
            }),
            standards_status: None,
        },
        Field {
            id: "AIP.12",
            position: 12,
            name: "Filler Status Code",
            data_type: Some(DataTypeRef::Legacy(&crate::legacy::v2_6::data_type::CWE)),
            cardinality: Cardinality {
                min: 0,
                max: Max::Bounded(1),
            },
            optionality: Optionality::C,
            length: Some(Length {
                min: 0,
                max: Some(250),
            }),
            conformance_length: None,
            table: Some(Table {
                id: "0278",
                value_set: "http://terminology.hl7.org/ValueSet/v2-0278",
            }),
            standards_status: None,
        },
    ],
};
