// @generated by fhir-codegen from usnistgov/igamt-hl7Tools-service 83322dffdac18cb129a1bd80149f5439cf5686fd src/main/resources/hl7db. DO NOT EDIT.
// Change the emitter (tools/fhir-codegen) and regenerate.
// SPDX-FileCopyrightText: Vernum Projecten B.V.
// SPDX-License-Identifier: Apache-2.0
//! The `CSR` segment: Clinical Study Registration.

use crate::model::{Cardinality, DataTypeRef, Field, Length, Max, Optionality, Segment, Table};

/// The `CSR` segment of the 2.6 tables.
pub static CSR: Segment = Segment {
    id: "CSR",
    url: None,
    name: "Clinical Study Registration",
    fields: &[
        Field {
            id: "CSR.1",
            position: 1,
            name: "Sponsor Study ID",
            data_type: Some(DataTypeRef::Legacy(&crate::legacy::v2_6::data_type::EI)),
            cardinality: Cardinality {
                min: 1,
                max: Max::Bounded(1),
            },
            optionality: Optionality::R,
            length: Some(Length {
                min: 0,
                max: Some(427),
            }),
            conformance_length: None,
            table: None,
            standards_status: None,
        },
        Field {
            id: "CSR.2",
            position: 2,
            name: "Alternate Study ID",
            data_type: Some(DataTypeRef::Legacy(&crate::legacy::v2_6::data_type::EI)),
            cardinality: Cardinality {
                min: 0,
                max: Max::Bounded(1),
            },
            optionality: Optionality::O,
            length: Some(Length {
                min: 0,
                max: Some(427),
            }),
            conformance_length: None,
            table: None,
            standards_status: None,
        },
        Field {
            id: "CSR.3",
            position: 3,
            name: "Institution Registering the Patient",
            data_type: Some(DataTypeRef::Legacy(&crate::legacy::v2_6::data_type::CWE)),
            cardinality: Cardinality {
                min: 0,
                max: Max::Bounded(1),
            },
            optionality: Optionality::O,
            length: Some(Length {
                min: 0,
                max: Some(705),
            }),
            conformance_length: None,
            table: Some(Table {
                id: "9999",
                value_set: "http://terminology.hl7.org/ValueSet/v2-9999",
            }),
            standards_status: None,
        },
        Field {
            id: "CSR.4",
            position: 4,
            name: "Sponsor Patient ID",
            data_type: Some(DataTypeRef::Legacy(&crate::legacy::v2_6::data_type::CX)),
            cardinality: Cardinality {
                min: 1,
                max: Max::Bounded(1),
            },
            optionality: Optionality::R,
            length: Some(Length {
                min: 0,
                max: Some(1913),
            }),
            conformance_length: None,
            table: None,
            standards_status: None,
        },
        Field {
            id: "CSR.5",
            position: 5,
            name: "Alternate Patient ID - CSR",
            data_type: Some(DataTypeRef::Legacy(&crate::legacy::v2_6::data_type::CX)),
            cardinality: Cardinality {
                min: 0,
                max: Max::Bounded(1),
            },
            optionality: Optionality::O,
            length: Some(Length {
                min: 0,
                max: Some(1913),
            }),
            conformance_length: None,
            table: None,
            standards_status: None,
        },
        Field {
            id: "CSR.6",
            position: 6,
            name: "Date/Time of Patient Study Registration",
            data_type: Some(DataTypeRef::Legacy(&crate::legacy::v2_6::data_type::DTM)),
            cardinality: Cardinality {
                min: 1,
                max: Max::Bounded(1),
            },
            optionality: Optionality::R,
            length: Some(Length {
                min: 0,
                max: Some(24),
            }),
            conformance_length: None,
            table: None,
            standards_status: None,
        },
        Field {
            id: "CSR.7",
            position: 7,
            name: "Person Performing Study Registration",
            data_type: Some(DataTypeRef::Legacy(&crate::legacy::v2_6::data_type::XCN)),
            cardinality: Cardinality {
                min: 0,
                max: Max::Unbounded,
            },
            optionality: Optionality::O,
            length: Some(Length {
                min: 0,
                max: Some(3220),
            }),
            conformance_length: None,
            table: None,
            standards_status: None,
        },
        Field {
            id: "CSR.8",
            position: 8,
            name: "Study Authorizing Provider",
            data_type: Some(DataTypeRef::Legacy(&crate::legacy::v2_6::data_type::XCN)),
            cardinality: Cardinality {
                min: 1,
                max: Max::Unbounded,
            },
            optionality: Optionality::R,
            length: Some(Length {
                min: 0,
                max: Some(3220),
            }),
            conformance_length: None,
            table: None,
            standards_status: None,
        },
        Field {
            id: "CSR.9",
            position: 9,
            name: "Date/time Patient Study Consent Signed",
            data_type: Some(DataTypeRef::Legacy(&crate::legacy::v2_6::data_type::DTM)),
            cardinality: Cardinality {
                min: 0,
                max: Max::Bounded(1),
            },
            optionality: Optionality::C,
            length: Some(Length {
                min: 0,
                max: Some(24),
            }),
            conformance_length: None,
            table: None,
            standards_status: None,
        },
        Field {
            id: "CSR.10",
            position: 10,
            name: "Patient Study Eligibility Status",
            data_type: Some(DataTypeRef::Legacy(&crate::legacy::v2_6::data_type::CWE)),
            cardinality: Cardinality {
                min: 0,
                max: Max::Bounded(1),
            },
            optionality: Optionality::C,
            length: Some(Length {
                min: 0,
                max: Some(705),
            }),
            conformance_length: None,
            table: Some(Table {
                id: "9999",
                value_set: "http://terminology.hl7.org/ValueSet/v2-9999",
            }),
            standards_status: None,
        },
        Field {
            id: "CSR.11",
            position: 11,
            name: "Study Randomization Date/time",
            data_type: Some(DataTypeRef::Legacy(&crate::legacy::v2_6::data_type::DTM)),
            cardinality: Cardinality {
                min: 0,
                max: Max::Bounded(3),
            },
            optionality: Optionality::O,
            length: Some(Length {
                min: 0,
                max: Some(24),
            }),
            conformance_length: None,
            table: None,
            standards_status: None,
        },
        Field {
            id: "CSR.12",
            position: 12,
            name: "Randomized Study Arm",
            data_type: Some(DataTypeRef::Legacy(&crate::legacy::v2_6::data_type::CWE)),
            cardinality: Cardinality {
                min: 0,
                max: Max::Bounded(3),
            },
            optionality: Optionality::O,
            length: Some(Length {
                min: 0,
                max: Some(705),
            }),
            conformance_length: None,
            table: Some(Table {
                id: "9999",
                value_set: "http://terminology.hl7.org/ValueSet/v2-9999",
            }),
            standards_status: None,
        },
        Field {
            id: "CSR.13",
            position: 13,
            name: "Stratum for Study Randomization",
            data_type: Some(DataTypeRef::Legacy(&crate::legacy::v2_6::data_type::CWE)),
            cardinality: Cardinality {
                min: 0,
                max: Max::Bounded(3),
            },
            optionality: Optionality::O,
            length: Some(Length {
                min: 0,
                max: Some(705),
            }),
            conformance_length: None,
            table: Some(Table {
                id: "9999",
                value_set: "http://terminology.hl7.org/ValueSet/v2-9999",
            }),
            standards_status: None,
        },
        Field {
            id: "CSR.14",
            position: 14,
            name: "Patient Evaluability Status",
            data_type: Some(DataTypeRef::Legacy(&crate::legacy::v2_6::data_type::CWE)),
            cardinality: Cardinality {
                min: 0,
                max: Max::Bounded(1),
            },
            optionality: Optionality::C,
            length: Some(Length {
                min: 0,
                max: Some(705),
            }),
            conformance_length: None,
            table: Some(Table {
                id: "9999",
                value_set: "http://terminology.hl7.org/ValueSet/v2-9999",
            }),
            standards_status: None,
        },
        Field {
            id: "CSR.15",
            position: 15,
            name: "Date/time Ended Study",
            data_type: Some(DataTypeRef::Legacy(&crate::legacy::v2_6::data_type::DTM)),
            cardinality: Cardinality {
                min: 0,
                max: Max::Bounded(1),
            },
            optionality: Optionality::C,
            length: Some(Length {
                min: 0,
                max: Some(24),
            }),
            conformance_length: None,
            table: None,
            standards_status: None,
        },
        Field {
            id: "CSR.16",
            position: 16,
            name: "Reason Ended Study",
            data_type: Some(DataTypeRef::Legacy(&crate::legacy::v2_6::data_type::CWE)),
            cardinality: Cardinality {
                min: 0,
                max: Max::Bounded(1),
            },
            optionality: Optionality::C,
            length: Some(Length {
                min: 0,
                max: Some(705),
            }),
            conformance_length: None,
            table: Some(Table {
                id: "9999",
                value_set: "http://terminology.hl7.org/ValueSet/v2-9999",
            }),
            standards_status: None,
        },
    ],
};
