// @generated by fhir-codegen from HL7/v2ig 3adcdbfff654ccbff5cd33aa34bd909a087e8e19 input/sourceOfTruth. DO NOT EDIT.
// Change the emitter (tools/fhir-codegen) and regenerate.
// SPDX-FileCopyrightText: Vernum Projecten B.V.
// SPDX-License-Identifier: Apache-2.0
//! The `ADT_A15` message structure.

use crate::model::{
    Cardinality, Group, GroupKind, Max, Node, SegmentRef, SegmentStatus, Structure,
};
use crate::segment;

/// The top-level nodes of [`ADT_A15`], one `static` so a structure with the same tree links to it.
pub static ADT_A15_NODES: [Node; 20] = [
    Node::Segment(SegmentRef {
        id: "ADT_A15.1-MSH",
        position: 1,
        segment: &segment::msh::MSH,
        cardinality: Cardinality {
            min: 1,
            max: Max::Bounded(1),
        },
        status: Some(SegmentStatus::A),
    }),
    Node::Segment(SegmentRef {
        id: "ADT_A15.2-ARV",
        position: 2,
        segment: &segment::arv::ARV,
        cardinality: Cardinality {
            min: 0,
            max: Max::Unbounded,
        },
        status: Some(SegmentStatus::A),
    }),
    Node::Segment(SegmentRef {
        id: "ADT_A15.3-SFT",
        position: 3,
        segment: &segment::sft::SFT,
        cardinality: Cardinality {
            min: 0,
            max: Max::Unbounded,
        },
        status: Some(SegmentStatus::A),
    }),
    Node::Segment(SegmentRef {
        id: "ADT_A15.4-UAC",
        position: 4,
        segment: &segment::uac::UAC,
        cardinality: Cardinality {
            min: 0,
            max: Max::Bounded(1),
        },
        status: Some(SegmentStatus::A),
    }),
    Node::Segment(SegmentRef {
        id: "ADT_A15.5-EVN",
        position: 5,
        segment: &segment::evn::EVN,
        cardinality: Cardinality {
            min: 1,
            max: Max::Bounded(1),
        },
        status: Some(SegmentStatus::A),
    }),
    Node::Segment(SegmentRef {
        id: "ADT_A15.6-PID",
        position: 6,
        segment: &segment::pid::PID,
        cardinality: Cardinality {
            min: 1,
            max: Max::Bounded(1),
        },
        status: Some(SegmentStatus::A),
    }),
    Node::Segment(SegmentRef {
        id: "ADT_A15.7-PD1",
        position: 7,
        segment: &segment::pd1::PD1,
        cardinality: Cardinality {
            min: 0,
            max: Max::Bounded(1),
        },
        status: Some(SegmentStatus::A),
    }),
    Node::Segment(SegmentRef {
        id: "ADT_A15.8-GSP",
        position: 8,
        segment: &segment::gsp::GSP,
        cardinality: Cardinality {
            min: 0,
            max: Max::Unbounded,
        },
        status: Some(SegmentStatus::A),
    }),
    Node::Segment(SegmentRef {
        id: "ADT_A15.9-GSR",
        position: 9,
        segment: &segment::gsr::GSR,
        cardinality: Cardinality {
            min: 0,
            max: Max::Unbounded,
        },
        status: Some(SegmentStatus::A),
    }),
    Node::Segment(SegmentRef {
        id: "ADT_A15.10-GSC",
        position: 10,
        segment: &segment::gsc::GSC,
        cardinality: Cardinality {
            min: 0,
            max: Max::Unbounded,
        },
        status: Some(SegmentStatus::A),
    }),
    Node::Segment(SegmentRef {
        id: "ADT_A15.11-ARV",
        position: 11,
        segment: &segment::arv::ARV,
        cardinality: Cardinality {
            min: 0,
            max: Max::Unbounded,
        },
        status: Some(SegmentStatus::B),
    }),
    Node::Segment(SegmentRef {
        id: "ADT_A15.12-ROL",
        position: 12,
        segment: &segment::rol::ROL,
        cardinality: Cardinality {
            min: 0,
            max: Max::Unbounded,
        },
        status: Some(SegmentStatus::B),
    }),
    Node::Segment(SegmentRef {
        id: "ADT_A15.13-PRT",
        position: 13,
        segment: &segment::prt::PRT,
        cardinality: Cardinality {
            min: 0,
            max: Max::Unbounded,
        },
        status: Some(SegmentStatus::A),
    }),
    Node::Segment(SegmentRef {
        id: "ADT_A15.14-PV1",
        position: 14,
        segment: &segment::pv1::PV1,
        cardinality: Cardinality {
            min: 1,
            max: Max::Bounded(1),
        },
        status: Some(SegmentStatus::A),
    }),
    Node::Segment(SegmentRef {
        id: "ADT_A15.15-PV2",
        position: 15,
        segment: &segment::pv2::PV2,
        cardinality: Cardinality {
            min: 0,
            max: Max::Bounded(1),
        },
        status: Some(SegmentStatus::A),
    }),
    Node::Segment(SegmentRef {
        id: "ADT_A15.16-ARV",
        position: 16,
        segment: &segment::arv::ARV,
        cardinality: Cardinality {
            min: 0,
            max: Max::Unbounded,
        },
        status: Some(SegmentStatus::B),
    }),
    Node::Segment(SegmentRef {
        id: "ADT_A15.17-ROL",
        position: 17,
        segment: &segment::rol::ROL,
        cardinality: Cardinality {
            min: 0,
            max: Max::Unbounded,
        },
        status: Some(SegmentStatus::B),
    }),
    Node::Segment(SegmentRef {
        id: "ADT_A15.18-PRT",
        position: 18,
        segment: &segment::prt::PRT,
        cardinality: Cardinality {
            min: 1,
            max: Max::Unbounded,
        },
        status: Some(SegmentStatus::A),
    }),
    Node::Segment(SegmentRef {
        id: "ADT_A15.19-DB1",
        position: 19,
        segment: &segment::db1::DB1,
        cardinality: Cardinality {
            min: 0,
            max: Max::Unbounded,
        },
        status: Some(SegmentStatus::A),
    }),
    Node::Group(Group {
        id: "ADT_A15.20-OBSERVATION",
        position: 20,
        name: "OBSERVATION",
        cardinality: Cardinality {
            min: 0,
            max: Max::Unbounded,
        },
        kind: GroupKind::Sequence,
        children: &[
            Node::Segment(SegmentRef {
                id: "ADT_A15.20-OBSERVATION.1-OBX",
                position: 1,
                segment: &segment::obx::OBX,
                cardinality: Cardinality {
                    min: 1,
                    max: Max::Bounded(1),
                },
                status: Some(SegmentStatus::A),
            }),
            Node::Segment(SegmentRef {
                id: "ADT_A15.20-OBSERVATION.2-PRT",
                position: 2,
                segment: &segment::prt::PRT,
                cardinality: Cardinality {
                    min: 0,
                    max: Max::Unbounded,
                },
                status: Some(SegmentStatus::A),
            }),
        ],
    }),
];

/// The `ADT_A15` message structure definition, `http://hl7.org/v2/StructureDefinition/ADT_A15`.
pub static ADT_A15: Structure = Structure {
    id: "ADT_A15",
    url: Some("http://hl7.org/v2/StructureDefinition/ADT_A15"),
    version: "2.9.1",
    withdrawn_as_of: None,
    nodes: &ADT_A15_NODES,
};
