// @generated by fhir-codegen from HL7/v2ig 3adcdbfff654ccbff5cd33aa34bd909a087e8e19 input/sourceOfTruth. DO NOT EDIT.
// Change the emitter (tools/fhir-codegen) and regenerate.
// SPDX-FileCopyrightText: Vernum Projecten B.V.
// SPDX-License-Identifier: Apache-2.0
//! The `CSU_C09` message structure.

use crate::model::{
    Cardinality, Group, GroupKind, Max, Node, SegmentRef, SegmentStatus, Structure,
};
use crate::segment;

/// The `CSU_C09` message structure definition, `http://hl7.org/v2/StructureDefinition/CSU_C09`.
pub static CSU_C09: Structure = Structure {
    id: "CSU_C09",
    url: Some("http://hl7.org/v2/StructureDefinition/CSU_C09"),
    version: "2.9.1",
    withdrawn_as_of: None,
    nodes: &[
        Node::Segment(SegmentRef {
            id: "CSU_C09.1-MSH",
            position: 1,
            segment: &segment::msh::MSH,
            cardinality: Cardinality {
                min: 1,
                max: Max::Bounded(1),
            },
            status: Some(SegmentStatus::A),
        }),
        Node::Segment(SegmentRef {
            id: "CSU_C09.2-ARV",
            position: 2,
            segment: &segment::arv::ARV,
            cardinality: Cardinality {
                min: 0,
                max: Max::Unbounded,
            },
            status: Some(SegmentStatus::A),
        }),
        Node::Segment(SegmentRef {
            id: "CSU_C09.3-SFT",
            position: 3,
            segment: &segment::sft::SFT,
            cardinality: Cardinality {
                min: 0,
                max: Max::Unbounded,
            },
            status: Some(SegmentStatus::A),
        }),
        Node::Segment(SegmentRef {
            id: "CSU_C09.4-UAC",
            position: 4,
            segment: &segment::uac::UAC,
            cardinality: Cardinality {
                min: 0,
                max: Max::Bounded(1),
            },
            status: Some(SegmentStatus::A),
        }),
        Node::Group(Group {
            id: "CSU_C09.5-PATIENT",
            position: 5,
            name: "PATIENT",
            cardinality: Cardinality {
                min: 1,
                max: Max::Unbounded,
            },
            kind: GroupKind::Sequence,
            children: &[
                Node::Segment(SegmentRef {
                    id: "CSU_C09.5-PATIENT.1-PID",
                    position: 1,
                    segment: &segment::pid::PID,
                    cardinality: Cardinality {
                        min: 1,
                        max: Max::Bounded(1),
                    },
                    status: Some(SegmentStatus::A),
                }),
                Node::Segment(SegmentRef {
                    id: "CSU_C09.5-PATIENT.2-PD1",
                    position: 2,
                    segment: &segment::pd1::PD1,
                    cardinality: Cardinality {
                        min: 0,
                        max: Max::Bounded(1),
                    },
                    status: Some(SegmentStatus::A),
                }),
                Node::Segment(SegmentRef {
                    id: "CSU_C09.5-PATIENT.3-GSP",
                    position: 3,
                    segment: &segment::gsp::GSP,
                    cardinality: Cardinality {
                        min: 0,
                        max: Max::Unbounded,
                    },
                    status: Some(SegmentStatus::A),
                }),
                Node::Segment(SegmentRef {
                    id: "CSU_C09.5-PATIENT.4-GSR",
                    position: 4,
                    segment: &segment::gsr::GSR,
                    cardinality: Cardinality {
                        min: 0,
                        max: Max::Unbounded,
                    },
                    status: Some(SegmentStatus::A),
                }),
                Node::Segment(SegmentRef {
                    id: "CSU_C09.5-PATIENT.5-GSC",
                    position: 5,
                    segment: &segment::gsc::GSC,
                    cardinality: Cardinality {
                        min: 0,
                        max: Max::Unbounded,
                    },
                    status: Some(SegmentStatus::A),
                }),
                Node::Segment(SegmentRef {
                    id: "CSU_C09.5-PATIENT.6-PRT",
                    position: 6,
                    segment: &segment::prt::PRT,
                    cardinality: Cardinality {
                        min: 0,
                        max: Max::Unbounded,
                    },
                    status: Some(SegmentStatus::A),
                }),
                Node::Segment(SegmentRef {
                    id: "CSU_C09.5-PATIENT.7-ARV",
                    position: 7,
                    segment: &segment::arv::ARV,
                    cardinality: Cardinality {
                        min: 0,
                        max: Max::Unbounded,
                    },
                    status: Some(SegmentStatus::B),
                }),
                Node::Segment(SegmentRef {
                    id: "CSU_C09.5-PATIENT.8-NTE",
                    position: 8,
                    segment: &segment::nte::NTE,
                    cardinality: Cardinality {
                        min: 0,
                        max: Max::Unbounded,
                    },
                    status: Some(SegmentStatus::A),
                }),
                Node::Group(Group {
                    id: "CSU_C09.5-PATIENT.9-VISIT",
                    position: 9,
                    name: "VISIT",
                    cardinality: Cardinality {
                        min: 0,
                        max: Max::Bounded(1),
                    },
                    kind: GroupKind::Sequence,
                    children: &[
                        Node::Segment(SegmentRef {
                            id: "CSU_C09.5-PATIENT.9-VISIT.1-PV1",
                            position: 1,
                            segment: &segment::pv1::PV1,
                            cardinality: Cardinality {
                                min: 1,
                                max: Max::Bounded(1),
                            },
                            status: Some(SegmentStatus::A),
                        }),
                        Node::Segment(SegmentRef {
                            id: "CSU_C09.5-PATIENT.9-VISIT.2-PV2",
                            position: 2,
                            segment: &segment::pv2::PV2,
                            cardinality: Cardinality {
                                min: 0,
                                max: Max::Bounded(1),
                            },
                            status: Some(SegmentStatus::A),
                        }),
                        Node::Segment(SegmentRef {
                            id: "CSU_C09.5-PATIENT.9-VISIT.3-PRT",
                            position: 3,
                            segment: &segment::prt::PRT,
                            cardinality: Cardinality {
                                min: 0,
                                max: Max::Unbounded,
                            },
                            status: Some(SegmentStatus::A),
                        }),
                    ],
                }),
                Node::Segment(SegmentRef {
                    id: "CSU_C09.5-PATIENT.10-CSR",
                    position: 10,
                    segment: &segment::csr::CSR,
                    cardinality: Cardinality {
                        min: 1,
                        max: Max::Bounded(1),
                    },
                    status: Some(SegmentStatus::A),
                }),
                Node::Group(Group {
                    id: "CSU_C09.5-PATIENT.11-STUDY_PHASE",
                    position: 11,
                    name: "STUDY_PHASE",
                    cardinality: Cardinality {
                        min: 1,
                        max: Max::Unbounded,
                    },
                    kind: GroupKind::Sequence,
                    children: &[
                        Node::Segment(SegmentRef {
                            id: "CSU_C09.5-PATIENT.11-STUDY_PHASE.1-CSP",
                            position: 1,
                            segment: &segment::csp::CSP,
                            cardinality: Cardinality {
                                min: 0,
                                max: Max::Bounded(1),
                            },
                            status: Some(SegmentStatus::A),
                        }),
                        Node::Group(Group {
                            id: "CSU_C09.5-PATIENT.11-STUDY_PHASE.2-STUDY_SCHEDULE",
                            position: 2,
                            name: "STUDY_SCHEDULE",
                            cardinality: Cardinality {
                                min: 1,
                                max: Max::Unbounded,
                            },
                            kind: GroupKind::Sequence,
                            children: &[
                                Node::Segment(SegmentRef {
                                    id: "CSU_C09.5-PATIENT.11-STUDY_PHASE.2-STUDY_SCHEDULE.1-CSS",
                                    position: 1,
                                    segment: &segment::css::CSS,
                                    cardinality: Cardinality {
                                        min: 0,
                                        max: Max::Bounded(1),
                                    },
                                    status: Some(SegmentStatus::A),
                                }),
                                Node::Group(Group {
                                    id: "CSU_C09.5-PATIENT.11-STUDY_PHASE.2-STUDY_SCHEDULE.2-STUDY_OBSERVATION",
                                    position: 2,
                                    name: "STUDY_OBSERVATION",
                                    cardinality: Cardinality {
                                        min: 1,
                                        max: Max::Unbounded,
                                    },
                                    kind: GroupKind::Sequence,
                                    children: &[
                                        Node::Group(Group {
                                            id: "CSU_C09.5-PATIENT.11-STUDY_PHASE.2-STUDY_SCHEDULE.2-STUDY_OBSERVATION.1-FIXME",
                                            position: 1,
                                            name: "FIXME",
                                            cardinality: Cardinality {
                                                min: 0,
                                                max: Max::Bounded(1),
                                            },
                                            kind: GroupKind::Sequence,
                                            children: &[
                                                Node::Segment(SegmentRef {
                                                    id: "CSU_C09.5-PATIENT.11-STUDY_PHASE.2-STUDY_SCHEDULE.2-STUDY_OBSERVATION.1-FIXME.1-ORC",
                                                    position: 1,
                                                    segment: &segment::orc::ORC,
                                                    cardinality: Cardinality {
                                                        min: 1,
                                                        max: Max::Bounded(1),
                                                    },
                                                    status: Some(SegmentStatus::A),
                                                }),
                                                Node::Segment(SegmentRef {
                                                    id: "CSU_C09.5-PATIENT.11-STUDY_PHASE.2-STUDY_SCHEDULE.2-STUDY_OBSERVATION.1-FIXME.2-PRT",
                                                    position: 2,
                                                    segment: &segment::prt::PRT,
                                                    cardinality: Cardinality {
                                                        min: 0,
                                                        max: Max::Unbounded,
                                                    },
                                                    status: Some(SegmentStatus::A),
                                                }),
                                            ],
                                        }),
                                        Node::Segment(SegmentRef {
                                            id: "CSU_C09.5-PATIENT.11-STUDY_PHASE.2-STUDY_SCHEDULE.2-STUDY_OBSERVATION.2-OBR",
                                            position: 2,
                                            segment: &segment::obr::OBR,
                                            cardinality: Cardinality {
                                                min: 1,
                                                max: Max::Bounded(1),
                                            },
                                            status: Some(SegmentStatus::A),
                                        }),
                                        Node::Segment(SegmentRef {
                                            id: "CSU_C09.5-PATIENT.11-STUDY_PHASE.2-STUDY_SCHEDULE.2-STUDY_OBSERVATION.3-PRT",
                                            position: 3,
                                            segment: &segment::prt::PRT,
                                            cardinality: Cardinality {
                                                min: 0,
                                                max: Max::Unbounded,
                                            },
                                            status: Some(SegmentStatus::A),
                                        }),
                                        Node::Group(Group {
                                            id: "CSU_C09.5-PATIENT.11-STUDY_PHASE.2-STUDY_SCHEDULE.2-STUDY_OBSERVATION.4-TIMING_QTY",
                                            position: 4,
                                            name: "TIMING_QTY",
                                            cardinality: Cardinality {
                                                min: 0,
                                                max: Max::Unbounded,
                                            },
                                            kind: GroupKind::Sequence,
                                            children: &[
                                                Node::Segment(SegmentRef {
                                                    id: "CSU_C09.5-PATIENT.11-STUDY_PHASE.2-STUDY_SCHEDULE.2-STUDY_OBSERVATION.4-TIMING_QTY.1-TQ1",
                                                    position: 1,
                                                    segment: &segment::tq1::TQ1,
                                                    cardinality: Cardinality {
                                                        min: 1,
                                                        max: Max::Bounded(1),
                                                    },
                                                    status: Some(SegmentStatus::A),
                                                }),
                                                Node::Segment(SegmentRef {
                                                    id: "CSU_C09.5-PATIENT.11-STUDY_PHASE.2-STUDY_SCHEDULE.2-STUDY_OBSERVATION.4-TIMING_QTY.2-TQ2",
                                                    position: 2,
                                                    segment: &segment::tq2::TQ2,
                                                    cardinality: Cardinality {
                                                        min: 0,
                                                        max: Max::Unbounded,
                                                    },
                                                    status: Some(SegmentStatus::A),
                                                }),
                                            ],
                                        }),
                                        Node::Segment(SegmentRef {
                                            id: "CSU_C09.5-PATIENT.11-STUDY_PHASE.2-STUDY_SCHEDULE.2-STUDY_OBSERVATION.5-OBX",
                                            position: 5,
                                            segment: &segment::obx::OBX,
                                            cardinality: Cardinality {
                                                min: 1,
                                                max: Max::Bounded(1),
                                            },
                                            status: Some(SegmentStatus::A),
                                        }),
                                        Node::Segment(SegmentRef {
                                            id: "CSU_C09.5-PATIENT.11-STUDY_PHASE.2-STUDY_SCHEDULE.2-STUDY_OBSERVATION.6-PRT",
                                            position: 6,
                                            segment: &segment::prt::PRT,
                                            cardinality: Cardinality {
                                                min: 0,
                                                max: Max::Unbounded,
                                            },
                                            status: Some(SegmentStatus::A),
                                        }),
                                    ],
                                }),
                                Node::Group(Group {
                                    id: "CSU_C09.5-PATIENT.11-STUDY_PHASE.2-STUDY_SCHEDULE.3-STUDY_PHARM",
                                    position: 3,
                                    name: "STUDY_PHARM",
                                    cardinality: Cardinality {
                                        min: 1,
                                        max: Max::Unbounded,
                                    },
                                    kind: GroupKind::Sequence,
                                    children: &[
                                        Node::Group(Group {
                                            id: "CSU_C09.5-PATIENT.11-STUDY_PHASE.2-STUDY_SCHEDULE.3-STUDY_PHARM.1-COMMON_ORDER",
                                            position: 1,
                                            name: "COMMON_ORDER",
                                            cardinality: Cardinality {
                                                min: 0,
                                                max: Max::Bounded(1),
                                            },
                                            kind: GroupKind::Sequence,
                                            children: &[
                                                Node::Segment(SegmentRef {
                                                    id: "CSU_C09.5-PATIENT.11-STUDY_PHASE.2-STUDY_SCHEDULE.3-STUDY_PHARM.1-COMMON_ORDER.1-ORC",
                                                    position: 1,
                                                    segment: &segment::orc::ORC,
                                                    cardinality: Cardinality {
                                                        min: 1,
                                                        max: Max::Bounded(1),
                                                    },
                                                    status: Some(SegmentStatus::A),
                                                }),
                                                Node::Segment(SegmentRef {
                                                    id: "CSU_C09.5-PATIENT.11-STUDY_PHASE.2-STUDY_SCHEDULE.3-STUDY_PHARM.1-COMMON_ORDER.2-PRT",
                                                    position: 2,
                                                    segment: &segment::prt::PRT,
                                                    cardinality: Cardinality {
                                                        min: 0,
                                                        max: Max::Unbounded,
                                                    },
                                                    status: Some(SegmentStatus::A),
                                                }),
                                            ],
                                        }),
                                        Node::Group(Group {
                                            id: "CSU_C09.5-PATIENT.11-STUDY_PHASE.2-STUDY_SCHEDULE.3-STUDY_PHARM.2-RX_ADMIN",
                                            position: 2,
                                            name: "RX_ADMIN",
                                            cardinality: Cardinality {
                                                min: 1,
                                                max: Max::Unbounded,
                                            },
                                            kind: GroupKind::Sequence,
                                            children: &[
                                                Node::Segment(SegmentRef {
                                                    id: "CSU_C09.5-PATIENT.11-STUDY_PHASE.2-STUDY_SCHEDULE.3-STUDY_PHARM.2-RX_ADMIN.1-RXA",
                                                    position: 1,
                                                    segment: &segment::rxa::RXA,
                                                    cardinality: Cardinality {
                                                        min: 1,
                                                        max: Max::Bounded(1),
                                                    },
                                                    status: Some(SegmentStatus::A),
                                                }),
                                                Node::Segment(SegmentRef {
                                                    id: "CSU_C09.5-PATIENT.11-STUDY_PHASE.2-STUDY_SCHEDULE.3-STUDY_PHARM.2-RX_ADMIN.2-RXR",
                                                    position: 2,
                                                    segment: &segment::rxr::RXR,
                                                    cardinality: Cardinality {
                                                        min: 1,
                                                        max: Max::Bounded(1),
                                                    },
                                                    status: Some(SegmentStatus::A),
                                                }),
                                                Node::Segment(SegmentRef {
                                                    id: "CSU_C09.5-PATIENT.11-STUDY_PHASE.2-STUDY_SCHEDULE.3-STUDY_PHARM.2-RX_ADMIN.3-PRT",
                                                    position: 3,
                                                    segment: &segment::prt::PRT,
                                                    cardinality: Cardinality {
                                                        min: 0,
                                                        max: Max::Unbounded,
                                                    },
                                                    status: Some(SegmentStatus::A),
                                                }),
                                            ],
                                        }),
                                    ],
                                }),
                            ],
                        }),
                    ],
                }),
            ],
        }),
    ],
};
