// @generated by fhir-codegen from HL7/v2ig 3adcdbfff654ccbff5cd33aa34bd909a087e8e19 input/sourceOfTruth. DO NOT EDIT.
// Change the emitter (tools/fhir-codegen) and regenerate.
// SPDX-FileCopyrightText: Vernum Projecten B.V.
// SPDX-License-Identifier: Apache-2.0
//! The `DEO_O45` message structure.

use crate::model::{
    Cardinality, Group, GroupKind, Max, Node, SegmentRef, SegmentStatus, Structure,
};
use crate::segment;

/// The `DEO_O45` message structure definition, `http://hl7.org/v2/StructureDefinition/DEO_O45`.
pub static DEO_O45: Structure = Structure {
    id: "DEO_O45",
    url: "http://hl7.org/v2/StructureDefinition/DEO_O45",
    nodes: &[
        Node::Segment(SegmentRef {
            id: "DEO_O45.1-MSH",
            position: 1,
            segment: &segment::msh::MSH,
            cardinality: Cardinality {
                min: 1,
                max: Max::Bounded(1),
            },
            status: Some(SegmentStatus::A),
        }),
        Node::Segment(SegmentRef {
            id: "DEO_O45.2-ARV",
            position: 2,
            segment: &segment::arv::ARV,
            cardinality: Cardinality {
                min: 0,
                max: Max::Unbounded,
            },
            status: Some(SegmentStatus::A),
        }),
        Node::Segment(SegmentRef {
            id: "DEO_O45.3-SFT",
            position: 3,
            segment: &segment::sft::SFT,
            cardinality: Cardinality {
                min: 0,
                max: Max::Unbounded,
            },
            status: Some(SegmentStatus::A),
        }),
        Node::Segment(SegmentRef {
            id: "DEO_O45.4-UAC",
            position: 4,
            segment: &segment::uac::UAC,
            cardinality: Cardinality {
                min: 0,
                max: Max::Bounded(1),
            },
            status: Some(SegmentStatus::A),
        }),
        Node::Group(Group {
            id: "DEO_O45.5-Donor",
            position: 5,
            name: "Donor",
            cardinality: Cardinality {
                min: 0,
                max: Max::Bounded(1),
            },
            kind: GroupKind::Sequence,
            children: &[
                Node::Segment(SegmentRef {
                    id: "DEO_O45.5-Donor.1-PID",
                    position: 1,
                    segment: &segment::pid::PID,
                    cardinality: Cardinality {
                        min: 1,
                        max: Max::Bounded(1),
                    },
                    status: Some(SegmentStatus::A),
                }),
                Node::Segment(SegmentRef {
                    id: "DEO_O45.5-Donor.2-PRT",
                    position: 2,
                    segment: &segment::prt::PRT,
                    cardinality: Cardinality {
                        min: 0,
                        max: Max::Unbounded,
                    },
                    status: Some(SegmentStatus::A),
                }),
                Node::Group(Group {
                    id: "DEO_O45.5-Donor.3-DONOR_OBSERVATIONS",
                    position: 3,
                    name: "DONOR_OBSERVATIONS",
                    cardinality: Cardinality {
                        min: 0,
                        max: Max::Unbounded,
                    },
                    kind: GroupKind::Sequence,
                    children: &[
                        Node::Segment(SegmentRef {
                            id: "DEO_O45.5-Donor.3-DONOR_OBSERVATIONS.1-OBX",
                            position: 1,
                            segment: &segment::obx::OBX,
                            cardinality: Cardinality {
                                min: 1,
                                max: Max::Bounded(1),
                            },
                            status: Some(SegmentStatus::A),
                        }),
                        Node::Segment(SegmentRef {
                            id: "DEO_O45.5-Donor.3-DONOR_OBSERVATIONS.2-PRT",
                            position: 2,
                            segment: &segment::prt::PRT,
                            cardinality: Cardinality {
                                min: 0,
                                max: Max::Unbounded,
                            },
                            status: Some(SegmentStatus::A),
                        }),
                    ],
                }),
                Node::Segment(SegmentRef {
                    id: "DEO_O45.5-Donor.4-ARV",
                    position: 4,
                    segment: &segment::arv::ARV,
                    cardinality: Cardinality {
                        min: 0,
                        max: Max::Unbounded,
                    },
                    status: Some(SegmentStatus::B),
                }),
                Node::Segment(SegmentRef {
                    id: "DEO_O45.5-Donor.5-NTE",
                    position: 5,
                    segment: &segment::nte::NTE,
                    cardinality: Cardinality {
                        min: 0,
                        max: Max::Unbounded,
                    },
                    status: Some(SegmentStatus::A),
                }),
                Node::Group(Group {
                    id: "DEO_O45.5-Donor.6-DONOR_REGISTRATION",
                    position: 6,
                    name: "DONOR_REGISTRATION",
                    cardinality: Cardinality {
                        min: 0,
                        max: Max::Bounded(1),
                    },
                    kind: GroupKind::Sequence,
                    children: &[
                        Node::Segment(SegmentRef {
                            id: "DEO_O45.5-Donor.6-DONOR_REGISTRATION.1-PV1",
                            position: 1,
                            segment: &segment::pv1::PV1,
                            cardinality: Cardinality {
                                min: 1,
                                max: Max::Bounded(1),
                            },
                            status: Some(SegmentStatus::A),
                        }),
                        Node::Segment(SegmentRef {
                            id: "DEO_O45.5-Donor.6-DONOR_REGISTRATION.2-PRT",
                            position: 2,
                            segment: &segment::prt::PRT,
                            cardinality: Cardinality {
                                min: 0,
                                max: Max::Unbounded,
                            },
                            status: Some(SegmentStatus::A),
                        }),
                        Node::Segment(SegmentRef {
                            id: "DEO_O45.5-Donor.6-DONOR_REGISTRATION.3-NTE",
                            position: 3,
                            segment: &segment::nte::NTE,
                            cardinality: Cardinality {
                                min: 0,
                                max: Max::Unbounded,
                            },
                            status: Some(SegmentStatus::A),
                        }),
                    ],
                }),
            ],
        }),
        Node::Group(Group {
            id: "DEO_O45.6-DONATION_ORDER",
            position: 6,
            name: "DONATION_ORDER",
            cardinality: Cardinality {
                min: 1,
                max: Max::Unbounded,
            },
            kind: GroupKind::Sequence,
            children: &[
                Node::Segment(SegmentRef {
                    id: "DEO_O45.6-DONATION_ORDER.1-OBR",
                    position: 1,
                    segment: &segment::obr::OBR,
                    cardinality: Cardinality {
                        min: 1,
                        max: Max::Bounded(1),
                    },
                    status: Some(SegmentStatus::A),
                }),
                Node::Segment(SegmentRef {
                    id: "DEO_O45.6-DONATION_ORDER.2-PRT",
                    position: 2,
                    segment: &segment::prt::PRT,
                    cardinality: Cardinality {
                        min: 0,
                        max: Max::Unbounded,
                    },
                    status: Some(SegmentStatus::A),
                }),
                Node::Segment(SegmentRef {
                    id: "DEO_O45.6-DONATION_ORDER.3-NTE",
                    position: 3,
                    segment: &segment::nte::NTE,
                    cardinality: Cardinality {
                        min: 0,
                        max: Max::Unbounded,
                    },
                    status: Some(SegmentStatus::A),
                }),
                Node::Group(Group {
                    id: "DEO_O45.6-DONATION_ORDER.4-DONATION_OBSERVATION",
                    position: 4,
                    name: "DONATION_OBSERVATION",
                    cardinality: Cardinality {
                        min: 0,
                        max: Max::Unbounded,
                    },
                    kind: GroupKind::Sequence,
                    children: &[
                        Node::Segment(SegmentRef {
                            id: "DEO_O45.6-DONATION_ORDER.4-DONATION_OBSERVATION.1-OBX",
                            position: 1,
                            segment: &segment::obx::OBX,
                            cardinality: Cardinality {
                                min: 1,
                                max: Max::Bounded(1),
                            },
                            status: Some(SegmentStatus::A),
                        }),
                        Node::Segment(SegmentRef {
                            id: "DEO_O45.6-DONATION_ORDER.4-DONATION_OBSERVATION.2-PRT",
                            position: 2,
                            segment: &segment::prt::PRT,
                            cardinality: Cardinality {
                                min: 0,
                                max: Max::Unbounded,
                            },
                            status: Some(SegmentStatus::A),
                        }),
                        Node::Segment(SegmentRef {
                            id: "DEO_O45.6-DONATION_ORDER.4-DONATION_OBSERVATION.3-NTE",
                            position: 3,
                            segment: &segment::nte::NTE,
                            cardinality: Cardinality {
                                min: 0,
                                max: Max::Unbounded,
                            },
                            status: Some(SegmentStatus::A),
                        }),
                    ],
                }),
            ],
        }),
    ],
};
