// @generated by fhir-codegen from HL7/v2ig 3adcdbfff654ccbff5cd33aa34bd909a087e8e19 input/sourceOfTruth. DO NOT EDIT.
// Change the emitter (tools/fhir-codegen) and regenerate.
// SPDX-FileCopyrightText: Vernum Projecten B.V.
// SPDX-License-Identifier: Apache-2.0
//! The `DRC_O47` message structure.

use crate::model::{
    Cardinality, Group, GroupKind, Max, Node, SegmentRef, SegmentStatus, Structure,
};
use crate::segment;

/// The top-level nodes of [`DRC_O47`], one `static` so a structure with the same tree links to it.
pub static DRC_O47_NODES: [Node; 6] = [
    Node::Segment(SegmentRef {
        id: "DRC_O47.1-MSH",
        position: 1,
        segment: &segment::msh::MSH,
        cardinality: Cardinality {
            min: 1,
            max: Max::Bounded(1),
        },
        status: Some(SegmentStatus::A),
    }),
    Node::Segment(SegmentRef {
        id: "DRC_O47.2-ARV",
        position: 2,
        segment: &segment::arv::ARV,
        cardinality: Cardinality {
            min: 0,
            max: Max::Unbounded,
        },
        status: Some(SegmentStatus::A),
    }),
    Node::Segment(SegmentRef {
        id: "DRC_O47.3-SFT",
        position: 3,
        segment: &segment::sft::SFT,
        cardinality: Cardinality {
            min: 0,
            max: Max::Unbounded,
        },
        status: Some(SegmentStatus::A),
    }),
    Node::Segment(SegmentRef {
        id: "DRC_O47.4-UAC",
        position: 4,
        segment: &segment::uac::UAC,
        cardinality: Cardinality {
            min: 0,
            max: Max::Bounded(1),
        },
        status: Some(SegmentStatus::A),
    }),
    Node::Group(Group {
        id: "DRC_O47.5-DONOR",
        position: 5,
        name: "DONOR",
        cardinality: Cardinality {
            min: 0,
            max: Max::Bounded(1),
        },
        kind: GroupKind::Sequence,
        children: &[
            Node::Segment(SegmentRef {
                id: "DRC_O47.5-DONOR.1-PID",
                position: 1,
                segment: &segment::pid::PID,
                cardinality: Cardinality {
                    min: 1,
                    max: Max::Bounded(1),
                },
                status: Some(SegmentStatus::A),
            }),
            Node::Segment(SegmentRef {
                id: "DRC_O47.5-DONOR.2-PD1",
                position: 2,
                segment: &segment::pd1::PD1,
                cardinality: Cardinality {
                    min: 0,
                    max: Max::Bounded(1),
                },
                status: Some(SegmentStatus::A),
            }),
            Node::Segment(SegmentRef {
                id: "DRC_O47.5-DONOR.3-PRT",
                position: 3,
                segment: &segment::prt::PRT,
                cardinality: Cardinality {
                    min: 0,
                    max: Max::Unbounded,
                },
                status: Some(SegmentStatus::A),
            }),
            Node::Group(Group {
                id: "DRC_O47.5-DONOR.4-DONOR_OBSERVATIONS",
                position: 4,
                name: "DONOR_OBSERVATIONS",
                cardinality: Cardinality {
                    min: 0,
                    max: Max::Unbounded,
                },
                kind: GroupKind::Sequence,
                children: &[
                    Node::Segment(SegmentRef {
                        id: "DRC_O47.5-DONOR.4-DONOR_OBSERVATIONS.1-OBX",
                        position: 1,
                        segment: &segment::obx::OBX,
                        cardinality: Cardinality {
                            min: 1,
                            max: Max::Bounded(1),
                        },
                        status: Some(SegmentStatus::A),
                    }),
                    Node::Segment(SegmentRef {
                        id: "DRC_O47.5-DONOR.4-DONOR_OBSERVATIONS.2-PRT",
                        position: 2,
                        segment: &segment::prt::PRT,
                        cardinality: Cardinality {
                            min: 0,
                            max: Max::Unbounded,
                        },
                        status: Some(SegmentStatus::A),
                    }),
                ],
            }),
            Node::Segment(SegmentRef {
                id: "DRC_O47.5-DONOR.5-NTE",
                position: 5,
                segment: &segment::nte::NTE,
                cardinality: Cardinality {
                    min: 0,
                    max: Max::Unbounded,
                },
                status: Some(SegmentStatus::A),
            }),
            Node::Segment(SegmentRef {
                id: "DRC_O47.5-DONOR.6-AL1",
                position: 6,
                segment: &segment::al1::AL1,
                cardinality: Cardinality {
                    min: 0,
                    max: Max::Unbounded,
                },
                status: Some(SegmentStatus::A),
            }),
            Node::Segment(SegmentRef {
                id: "DRC_O47.5-DONOR.7-ARV",
                position: 7,
                segment: &segment::arv::ARV,
                cardinality: Cardinality {
                    min: 0,
                    max: Max::Unbounded,
                },
                status: Some(SegmentStatus::B),
            }),
            Node::Group(Group {
                id: "DRC_O47.5-DONOR.8-DONOR_REGISTRATION",
                position: 8,
                name: "DONOR_REGISTRATION",
                cardinality: Cardinality {
                    min: 0,
                    max: Max::Bounded(1),
                },
                kind: GroupKind::Sequence,
                children: &[
                    Node::Segment(SegmentRef {
                        id: "DRC_O47.5-DONOR.8-DONOR_REGISTRATION.1-PV1",
                        position: 1,
                        segment: &segment::pv1::PV1,
                        cardinality: Cardinality {
                            min: 1,
                            max: Max::Bounded(1),
                        },
                        status: Some(SegmentStatus::A),
                    }),
                    Node::Segment(SegmentRef {
                        id: "DRC_O47.5-DONOR.8-DONOR_REGISTRATION.2-PRT",
                        position: 2,
                        segment: &segment::prt::PRT,
                        cardinality: Cardinality {
                            min: 0,
                            max: Max::Unbounded,
                        },
                        status: Some(SegmentStatus::A),
                    }),
                    Node::Segment(SegmentRef {
                        id: "DRC_O47.5-DONOR.8-DONOR_REGISTRATION.3-NTE",
                        position: 3,
                        segment: &segment::nte::NTE,
                        cardinality: Cardinality {
                            min: 0,
                            max: Max::Unbounded,
                        },
                        status: Some(SegmentStatus::A),
                    }),
                ],
            }),
        ],
    }),
    Node::Group(Group {
        id: "DRC_O47.6-DONATION_ORDER",
        position: 6,
        name: "DONATION_ORDER",
        cardinality: Cardinality {
            min: 1,
            max: Max::Unbounded,
        },
        kind: GroupKind::Sequence,
        children: &[
            Node::Segment(SegmentRef {
                id: "DRC_O47.6-DONATION_ORDER.1-OBR",
                position: 1,
                segment: &segment::obr::OBR,
                cardinality: Cardinality {
                    min: 1,
                    max: Max::Bounded(1),
                },
                status: Some(SegmentStatus::A),
            }),
            Node::Segment(SegmentRef {
                id: "DRC_O47.6-DONATION_ORDER.2-PRT",
                position: 2,
                segment: &segment::prt::PRT,
                cardinality: Cardinality {
                    min: 0,
                    max: Max::Unbounded,
                },
                status: Some(SegmentStatus::A),
            }),
            Node::Segment(SegmentRef {
                id: "DRC_O47.6-DONATION_ORDER.3-NTE",
                position: 3,
                segment: &segment::nte::NTE,
                cardinality: Cardinality {
                    min: 0,
                    max: Max::Unbounded,
                },
                status: Some(SegmentStatus::A),
            }),
        ],
    }),
];

/// The `DRC_O47` message structure definition, `http://hl7.org/v2/StructureDefinition/DRC_O47`.
pub static DRC_O47: Structure = Structure {
    id: "DRC_O47",
    url: Some("http://hl7.org/v2/StructureDefinition/DRC_O47"),
    version: "2.9.1",
    withdrawn_as_of: None,
    nodes: &DRC_O47_NODES,
};
