// @generated by fhir-codegen from HL7/v2ig 3adcdbfff654ccbff5cd33aa34bd909a087e8e19 input/sourceOfTruth. DO NOT EDIT.
// Change the emitter (tools/fhir-codegen) and regenerate.
// SPDX-FileCopyrightText: Vernum Projecten B.V.
// SPDX-License-Identifier: Apache-2.0
//! The `OMI_O23` message structure.

use crate::model::{
    Cardinality, Group, GroupKind, Max, Node, SegmentRef, SegmentStatus, Structure,
};
use crate::segment;

/// The `OMI_O23` message structure definition, `http://hl7.org/v2/StructureDefinition/OMI_O23`.
pub static OMI_O23: Structure = Structure {
    id: "OMI_O23",
    url: Some("http://hl7.org/v2/StructureDefinition/OMI_O23"),
    version: "2.9.1",
    withdrawn_as_of: None,
    nodes: &[
        Node::Segment(SegmentRef {
            id: "OMI_O23.1-MSH",
            position: 1,
            segment: &segment::msh::MSH,
            cardinality: Cardinality {
                min: 1,
                max: Max::Bounded(1),
            },
            status: Some(SegmentStatus::A),
        }),
        Node::Segment(SegmentRef {
            id: "OMI_O23.2-ARV",
            position: 2,
            segment: &segment::arv::ARV,
            cardinality: Cardinality {
                min: 0,
                max: Max::Unbounded,
            },
            status: Some(SegmentStatus::A),
        }),
        Node::Segment(SegmentRef {
            id: "OMI_O23.3-SFT",
            position: 3,
            segment: &segment::sft::SFT,
            cardinality: Cardinality {
                min: 0,
                max: Max::Unbounded,
            },
            status: Some(SegmentStatus::A),
        }),
        Node::Segment(SegmentRef {
            id: "OMI_O23.4-UAC",
            position: 4,
            segment: &segment::uac::UAC,
            cardinality: Cardinality {
                min: 0,
                max: Max::Bounded(1),
            },
            status: Some(SegmentStatus::A),
        }),
        Node::Segment(SegmentRef {
            id: "OMI_O23.5-NTE",
            position: 5,
            segment: &segment::nte::NTE,
            cardinality: Cardinality {
                min: 0,
                max: Max::Unbounded,
            },
            status: Some(SegmentStatus::A),
        }),
        Node::Group(Group {
            id: "OMI_O23.6-PATIENT",
            position: 6,
            name: "PATIENT",
            cardinality: Cardinality {
                min: 0,
                max: Max::Bounded(1),
            },
            kind: GroupKind::Sequence,
            children: &[
                Node::Segment(SegmentRef {
                    id: "OMI_O23.6-PATIENT.1-PID",
                    position: 1,
                    segment: &segment::pid::PID,
                    cardinality: Cardinality {
                        min: 1,
                        max: Max::Bounded(1),
                    },
                    status: Some(SegmentStatus::A),
                }),
                Node::Segment(SegmentRef {
                    id: "OMI_O23.6-PATIENT.2-PD1",
                    position: 2,
                    segment: &segment::pd1::PD1,
                    cardinality: Cardinality {
                        min: 0,
                        max: Max::Bounded(1),
                    },
                    status: Some(SegmentStatus::A),
                }),
                Node::Segment(SegmentRef {
                    id: "OMI_O23.6-PATIENT.3-GSP",
                    position: 3,
                    segment: &segment::gsp::GSP,
                    cardinality: Cardinality {
                        min: 0,
                        max: Max::Unbounded,
                    },
                    status: Some(SegmentStatus::A),
                }),
                Node::Segment(SegmentRef {
                    id: "OMI_O23.6-PATIENT.4-GSR",
                    position: 4,
                    segment: &segment::gsr::GSR,
                    cardinality: Cardinality {
                        min: 0,
                        max: Max::Unbounded,
                    },
                    status: Some(SegmentStatus::A),
                }),
                Node::Segment(SegmentRef {
                    id: "OMI_O23.6-PATIENT.5-GSC",
                    position: 5,
                    segment: &segment::gsc::GSC,
                    cardinality: Cardinality {
                        min: 0,
                        max: Max::Unbounded,
                    },
                    status: Some(SegmentStatus::A),
                }),
                Node::Segment(SegmentRef {
                    id: "OMI_O23.6-PATIENT.6-PRT",
                    position: 6,
                    segment: &segment::prt::PRT,
                    cardinality: Cardinality {
                        min: 0,
                        max: Max::Unbounded,
                    },
                    status: Some(SegmentStatus::A),
                }),
                Node::Group(Group {
                    id: "OMI_O23.6-PATIENT.7-OCCUPATIONAL_DATA_FOR_HEALTH",
                    position: 7,
                    name: "OCCUPATIONAL_DATA_FOR_HEALTH",
                    cardinality: Cardinality {
                        min: 0,
                        max: Max::Bounded(1),
                    },
                    kind: GroupKind::Sequence,
                    children: &[
                        Node::Segment(SegmentRef {
                            id: "OMI_O23.6-PATIENT.7-OCCUPATIONAL_DATA_FOR_HEALTH.1-OH1",
                            position: 1,
                            segment: &segment::oh1::OH1,
                            cardinality: Cardinality {
                                min: 0,
                                max: Max::Unbounded,
                            },
                            status: Some(SegmentStatus::A),
                        }),
                        Node::Segment(SegmentRef {
                            id: "OMI_O23.6-PATIENT.7-OCCUPATIONAL_DATA_FOR_HEALTH.2-OH2",
                            position: 2,
                            segment: &segment::oh2::OH2,
                            cardinality: Cardinality {
                                min: 0,
                                max: Max::Unbounded,
                            },
                            status: Some(SegmentStatus::A),
                        }),
                        Node::Segment(SegmentRef {
                            id: "OMI_O23.6-PATIENT.7-OCCUPATIONAL_DATA_FOR_HEALTH.3-OH3",
                            position: 3,
                            segment: &segment::oh3::OH3,
                            cardinality: Cardinality {
                                min: 0,
                                max: Max::Bounded(1),
                            },
                            status: Some(SegmentStatus::A),
                        }),
                        Node::Segment(SegmentRef {
                            id: "OMI_O23.6-PATIENT.7-OCCUPATIONAL_DATA_FOR_HEALTH.4-OH4",
                            position: 4,
                            segment: &segment::oh4::OH4,
                            cardinality: Cardinality {
                                min: 0,
                                max: Max::Unbounded,
                            },
                            status: Some(SegmentStatus::A),
                        }),
                    ],
                }),
                Node::Segment(SegmentRef {
                    id: "OMI_O23.6-PATIENT.8-ARV",
                    position: 8,
                    segment: &segment::arv::ARV,
                    cardinality: Cardinality {
                        min: 0,
                        max: Max::Unbounded,
                    },
                    status: Some(SegmentStatus::B),
                }),
                Node::Segment(SegmentRef {
                    id: "OMI_O23.6-PATIENT.9-NTE",
                    position: 9,
                    segment: &segment::nte::NTE,
                    cardinality: Cardinality {
                        min: 0,
                        max: Max::Unbounded,
                    },
                    status: Some(SegmentStatus::A),
                }),
                Node::Group(Group {
                    id: "OMI_O23.6-PATIENT.10-PATIENT_VISIT",
                    position: 10,
                    name: "PATIENT_VISIT",
                    cardinality: Cardinality {
                        min: 0,
                        max: Max::Bounded(1),
                    },
                    kind: GroupKind::Sequence,
                    children: &[
                        Node::Segment(SegmentRef {
                            id: "OMI_O23.6-PATIENT.10-PATIENT_VISIT.1-PV1",
                            position: 1,
                            segment: &segment::pv1::PV1,
                            cardinality: Cardinality {
                                min: 1,
                                max: Max::Bounded(1),
                            },
                            status: Some(SegmentStatus::A),
                        }),
                        Node::Segment(SegmentRef {
                            id: "OMI_O23.6-PATIENT.10-PATIENT_VISIT.2-PV2",
                            position: 2,
                            segment: &segment::pv2::PV2,
                            cardinality: Cardinality {
                                min: 0,
                                max: Max::Bounded(1),
                            },
                            status: Some(SegmentStatus::A),
                        }),
                        Node::Segment(SegmentRef {
                            id: "OMI_O23.6-PATIENT.10-PATIENT_VISIT.3-PRT",
                            position: 3,
                            segment: &segment::prt::PRT,
                            cardinality: Cardinality {
                                min: 0,
                                max: Max::Unbounded,
                            },
                            status: Some(SegmentStatus::A),
                        }),
                    ],
                }),
                Node::Group(Group {
                    id: "OMI_O23.6-PATIENT.11-INSURANCE",
                    position: 11,
                    name: "INSURANCE",
                    cardinality: Cardinality {
                        min: 0,
                        max: Max::Unbounded,
                    },
                    kind: GroupKind::Sequence,
                    children: &[
                        Node::Segment(SegmentRef {
                            id: "OMI_O23.6-PATIENT.11-INSURANCE.1-IN1",
                            position: 1,
                            segment: &segment::in1::IN1,
                            cardinality: Cardinality {
                                min: 1,
                                max: Max::Bounded(1),
                            },
                            status: Some(SegmentStatus::A),
                        }),
                        Node::Segment(SegmentRef {
                            id: "OMI_O23.6-PATIENT.11-INSURANCE.2-IN2",
                            position: 2,
                            segment: &segment::in2::IN2,
                            cardinality: Cardinality {
                                min: 0,
                                max: Max::Bounded(1),
                            },
                            status: Some(SegmentStatus::A),
                        }),
                        Node::Segment(SegmentRef {
                            id: "OMI_O23.6-PATIENT.11-INSURANCE.3-IN3",
                            position: 3,
                            segment: &segment::in3::IN3,
                            cardinality: Cardinality {
                                min: 0,
                                max: Max::Bounded(1),
                            },
                            status: Some(SegmentStatus::A),
                        }),
                    ],
                }),
                Node::Segment(SegmentRef {
                    id: "OMI_O23.6-PATIENT.12-GT1",
                    position: 12,
                    segment: &segment::gt1::GT1,
                    cardinality: Cardinality {
                        min: 0,
                        max: Max::Bounded(1),
                    },
                    status: Some(SegmentStatus::A),
                }),
                Node::Segment(SegmentRef {
                    id: "OMI_O23.6-PATIENT.13-AL1",
                    position: 13,
                    segment: &segment::al1::AL1,
                    cardinality: Cardinality {
                        min: 0,
                        max: Max::Unbounded,
                    },
                    status: Some(SegmentStatus::A),
                }),
            ],
        }),
        Node::Group(Group {
            id: "OMI_O23.7-ORDER",
            position: 7,
            name: "ORDER",
            cardinality: Cardinality {
                min: 1,
                max: Max::Unbounded,
            },
            kind: GroupKind::Sequence,
            children: &[
                Node::Segment(SegmentRef {
                    id: "OMI_O23.7-ORDER.1-ORC",
                    position: 1,
                    segment: &segment::orc::ORC,
                    cardinality: Cardinality {
                        min: 1,
                        max: Max::Bounded(1),
                    },
                    status: Some(SegmentStatus::A),
                }),
                Node::Segment(SegmentRef {
                    id: "OMI_O23.7-ORDER.2-PRT",
                    position: 2,
                    segment: &segment::prt::PRT,
                    cardinality: Cardinality {
                        min: 0,
                        max: Max::Unbounded,
                    },
                    status: Some(SegmentStatus::A),
                }),
                Node::Group(Group {
                    id: "OMI_O23.7-ORDER.3-TIMING",
                    position: 3,
                    name: "TIMING",
                    cardinality: Cardinality {
                        min: 0,
                        max: Max::Unbounded,
                    },
                    kind: GroupKind::Sequence,
                    children: &[
                        Node::Segment(SegmentRef {
                            id: "OMI_O23.7-ORDER.3-TIMING.1-TQ1",
                            position: 1,
                            segment: &segment::tq1::TQ1,
                            cardinality: Cardinality {
                                min: 1,
                                max: Max::Bounded(1),
                            },
                            status: Some(SegmentStatus::A),
                        }),
                        Node::Segment(SegmentRef {
                            id: "OMI_O23.7-ORDER.3-TIMING.2-TQ2",
                            position: 2,
                            segment: &segment::tq2::TQ2,
                            cardinality: Cardinality {
                                min: 0,
                                max: Max::Unbounded,
                            },
                            status: Some(SegmentStatus::A),
                        }),
                    ],
                }),
                Node::Segment(SegmentRef {
                    id: "OMI_O23.7-ORDER.4-OBR",
                    position: 4,
                    segment: &segment::obr::OBR,
                    cardinality: Cardinality {
                        min: 1,
                        max: Max::Bounded(1),
                    },
                    status: Some(SegmentStatus::A),
                }),
                Node::Segment(SegmentRef {
                    id: "OMI_O23.7-ORDER.5-NTE",
                    position: 5,
                    segment: &segment::nte::NTE,
                    cardinality: Cardinality {
                        min: 0,
                        max: Max::Unbounded,
                    },
                    status: Some(SegmentStatus::A),
                }),
                Node::Segment(SegmentRef {
                    id: "OMI_O23.7-ORDER.6-PRT",
                    position: 6,
                    segment: &segment::prt::PRT,
                    cardinality: Cardinality {
                        min: 0,
                        max: Max::Unbounded,
                    },
                    status: Some(SegmentStatus::A),
                }),
                Node::Segment(SegmentRef {
                    id: "OMI_O23.7-ORDER.7-CTD",
                    position: 7,
                    segment: &segment::ctd::CTD,
                    cardinality: Cardinality {
                        min: 0,
                        max: Max::Bounded(1),
                    },
                    status: Some(SegmentStatus::A),
                }),
                Node::Segment(SegmentRef {
                    id: "OMI_O23.7-ORDER.8-DG1",
                    position: 8,
                    segment: &segment::dg1::DG1,
                    cardinality: Cardinality {
                        min: 0,
                        max: Max::Unbounded,
                    },
                    status: Some(SegmentStatus::A),
                }),
                Node::Segment(SegmentRef {
                    id: "OMI_O23.7-ORDER.9-REL",
                    position: 9,
                    segment: &segment::rel::REL,
                    cardinality: Cardinality {
                        min: 0,
                        max: Max::Unbounded,
                    },
                    status: Some(SegmentStatus::A),
                }),
                Node::Group(Group {
                    id: "OMI_O23.7-ORDER.10-OBSERVATION",
                    position: 10,
                    name: "OBSERVATION",
                    cardinality: Cardinality {
                        min: 0,
                        max: Max::Unbounded,
                    },
                    kind: GroupKind::Sequence,
                    children: &[
                        Node::Segment(SegmentRef {
                            id: "OMI_O23.7-ORDER.10-OBSERVATION.1-OBX",
                            position: 1,
                            segment: &segment::obx::OBX,
                            cardinality: Cardinality {
                                min: 1,
                                max: Max::Bounded(1),
                            },
                            status: Some(SegmentStatus::A),
                        }),
                        Node::Segment(SegmentRef {
                            id: "OMI_O23.7-ORDER.10-OBSERVATION.2-PRT",
                            position: 2,
                            segment: &segment::prt::PRT,
                            cardinality: Cardinality {
                                min: 0,
                                max: Max::Unbounded,
                            },
                            status: Some(SegmentStatus::A),
                        }),
                        Node::Segment(SegmentRef {
                            id: "OMI_O23.7-ORDER.10-OBSERVATION.3-NTE",
                            position: 3,
                            segment: &segment::nte::NTE,
                            cardinality: Cardinality {
                                min: 0,
                                max: Max::Unbounded,
                            },
                            status: Some(SegmentStatus::A),
                        }),
                    ],
                }),
                Node::Segment(SegmentRef {
                    id: "OMI_O23.7-ORDER.11-IPC",
                    position: 11,
                    segment: &segment::ipc::IPC,
                    cardinality: Cardinality {
                        min: 1,
                        max: Max::Unbounded,
                    },
                    status: Some(SegmentStatus::A),
                }),
            ],
        }),
        Node::Group(Group {
            id: "OMI_O23.8-DEVICE",
            position: 8,
            name: "DEVICE",
            cardinality: Cardinality {
                min: 0,
                max: Max::Unbounded,
            },
            kind: GroupKind::Sequence,
            children: &[
                Node::Segment(SegmentRef {
                    id: "OMI_O23.8-DEVICE.1-DEV",
                    position: 1,
                    segment: &segment::dev::DEV,
                    cardinality: Cardinality {
                        min: 1,
                        max: Max::Bounded(1),
                    },
                    status: Some(SegmentStatus::A),
                }),
                Node::Segment(SegmentRef {
                    id: "OMI_O23.8-DEVICE.2-OBX",
                    position: 2,
                    segment: &segment::obx::OBX,
                    cardinality: Cardinality {
                        min: 0,
                        max: Max::Unbounded,
                    },
                    status: Some(SegmentStatus::A),
                }),
            ],
        }),
    ],
};
