// @generated by fhir-codegen from HL7/v2ig 3adcdbfff654ccbff5cd33aa34bd909a087e8e19 input/sourceOfTruth. DO NOT EDIT.
// Change the emitter (tools/fhir-codegen) and regenerate.
// SPDX-FileCopyrightText: Vernum Projecten B.V.
// SPDX-License-Identifier: Apache-2.0
//! The `ORA_R41` message structure.

use crate::model::{Cardinality, Max, Node, SegmentRef, SegmentStatus, Structure};
use crate::segment;

/// The `ORA_R41` message structure definition, `http://hl7.org/v2/StructureDefinition/ORA_R41`.
pub static ORA_R41: Structure = Structure {
    id: "ORA_R41",
    url: Some("http://hl7.org/v2/StructureDefinition/ORA_R41"),
    version: "2.9.1",
    withdrawn_as_of: None,
    nodes: &[
        Node::Segment(SegmentRef {
            id: "ORA_R41.1-MSH",
            position: 1,
            segment: &segment::msh::MSH,
            cardinality: Cardinality {
                min: 1,
                max: Max::Bounded(1),
            },
            status: Some(SegmentStatus::A),
        }),
        Node::Segment(SegmentRef {
            id: "ORA_R41.2-SFT",
            position: 2,
            segment: &segment::sft::SFT,
            cardinality: Cardinality {
                min: 0,
                max: Max::Unbounded,
            },
            status: Some(SegmentStatus::A),
        }),
        Node::Segment(SegmentRef {
            id: "ORA_R41.3-UAC",
            position: 3,
            segment: &segment::uac::UAC,
            cardinality: Cardinality {
                min: 0,
                max: Max::Bounded(1),
            },
            status: Some(SegmentStatus::A),
        }),
        Node::Segment(SegmentRef {
            id: "ORA_R41.4-MSA",
            position: 4,
            segment: &segment::msa::MSA,
            cardinality: Cardinality {
                min: 1,
                max: Max::Bounded(1),
            },
            status: Some(SegmentStatus::A),
        }),
        Node::Segment(SegmentRef {
            id: "ORA_R41.5-ERR",
            position: 5,
            segment: &segment::err::ERR,
            cardinality: Cardinality {
                min: 0,
                max: Max::Unbounded,
            },
            status: Some(SegmentStatus::A),
        }),
        Node::Segment(SegmentRef {
            id: "ORA_R41.6-PRT",
            position: 6,
            segment: &segment::prt::PRT,
            cardinality: Cardinality {
                min: 0,
                max: Max::Unbounded,
            },
            status: Some(SegmentStatus::A),
        }),
    ],
};
