// @generated by fhir-codegen from HL7/v2ig 3adcdbfff654ccbff5cd33aa34bd909a087e8e19 input/sourceOfTruth. DO NOT EDIT.
// Change the emitter (tools/fhir-codegen) and regenerate.
// SPDX-FileCopyrightText: Vernum Projecten B.V.
// SPDX-License-Identifier: Apache-2.0
//! The `ORP_O10` message structure.

use crate::model::{
    Cardinality, Group, GroupKind, Max, Node, SegmentRef, SegmentStatus, Structure,
};
use crate::segment;

/// The `ORP_O10` message structure definition, `http://hl7.org/v2/StructureDefinition/ORP_O10`.
pub static ORP_O10: Structure = Structure {
    id: "ORP_O10",
    url: "http://hl7.org/v2/StructureDefinition/ORP_O10",
    nodes: &[
        Node::Segment(SegmentRef {
            id: "ORP_O10.1-MSH",
            position: 1,
            segment: &segment::msh::MSH,
            cardinality: Cardinality {
                min: 1,
                max: Max::Bounded(1),
            },
            status: Some(SegmentStatus::A),
        }),
        Node::Segment(SegmentRef {
            id: "ORP_O10.2-MSA",
            position: 2,
            segment: &segment::msa::MSA,
            cardinality: Cardinality {
                min: 1,
                max: Max::Bounded(1),
            },
            status: Some(SegmentStatus::A),
        }),
        Node::Segment(SegmentRef {
            id: "ORP_O10.3-ERR",
            position: 3,
            segment: &segment::err::ERR,
            cardinality: Cardinality {
                min: 0,
                max: Max::Unbounded,
            },
            status: Some(SegmentStatus::A),
        }),
        Node::Segment(SegmentRef {
            id: "ORP_O10.4-SFT",
            position: 4,
            segment: &segment::sft::SFT,
            cardinality: Cardinality {
                min: 0,
                max: Max::Unbounded,
            },
            status: Some(SegmentStatus::A),
        }),
        Node::Segment(SegmentRef {
            id: "ORP_O10.5-UAC",
            position: 5,
            segment: &segment::uac::UAC,
            cardinality: Cardinality {
                min: 0,
                max: Max::Bounded(1),
            },
            status: Some(SegmentStatus::A),
        }),
        Node::Segment(SegmentRef {
            id: "ORP_O10.6-NTE",
            position: 6,
            segment: &segment::nte::NTE,
            cardinality: Cardinality {
                min: 0,
                max: Max::Unbounded,
            },
            status: Some(SegmentStatus::A),
        }),
        Node::Group(Group {
            id: "ORP_O10.7-RESPONSE",
            position: 7,
            name: "RESPONSE",
            cardinality: Cardinality {
                min: 0,
                max: Max::Bounded(1),
            },
            kind: GroupKind::Sequence,
            children: &[
                Node::Group(Group {
                    id: "ORP_O10.7-RESPONSE.1-PATIENT",
                    position: 1,
                    name: "PATIENT",
                    cardinality: Cardinality {
                        min: 0,
                        max: Max::Bounded(1),
                    },
                    kind: GroupKind::Sequence,
                    children: &[
                        Node::Segment(SegmentRef {
                            id: "ORP_O10.7-RESPONSE.1-PATIENT.1-PID",
                            position: 1,
                            segment: &segment::pid::PID,
                            cardinality: Cardinality {
                                min: 1,
                                max: Max::Bounded(1),
                            },
                            status: Some(SegmentStatus::A),
                        }),
                        Node::Segment(SegmentRef {
                            id: "ORP_O10.7-RESPONSE.1-PATIENT.2-PRT",
                            position: 2,
                            segment: &segment::prt::PRT,
                            cardinality: Cardinality {
                                min: 0,
                                max: Max::Unbounded,
                            },
                            status: Some(SegmentStatus::A),
                        }),
                        Node::Segment(SegmentRef {
                            id: "ORP_O10.7-RESPONSE.1-PATIENT.3-NTE",
                            position: 3,
                            segment: &segment::nte::NTE,
                            cardinality: Cardinality {
                                min: 0,
                                max: Max::Unbounded,
                            },
                            status: Some(SegmentStatus::A),
                        }),
                    ],
                }),
                Node::Group(Group {
                    id: "ORP_O10.7-RESPONSE.2-ORDER",
                    position: 2,
                    name: "ORDER",
                    cardinality: Cardinality {
                        min: 1,
                        max: Max::Unbounded,
                    },
                    kind: GroupKind::Sequence,
                    children: &[
                        Node::Segment(SegmentRef {
                            id: "ORP_O10.7-RESPONSE.2-ORDER.1-ORC",
                            position: 1,
                            segment: &segment::orc::ORC,
                            cardinality: Cardinality {
                                min: 1,
                                max: Max::Bounded(1),
                            },
                            status: Some(SegmentStatus::A),
                        }),
                        Node::Segment(SegmentRef {
                            id: "ORP_O10.7-RESPONSE.2-ORDER.2-PRT",
                            position: 2,
                            segment: &segment::prt::PRT,
                            cardinality: Cardinality {
                                min: 0,
                                max: Max::Unbounded,
                            },
                            status: Some(SegmentStatus::A),
                        }),
                        Node::Group(Group {
                            id: "ORP_O10.7-RESPONSE.2-ORDER.3-TIMING",
                            position: 3,
                            name: "TIMING",
                            cardinality: Cardinality {
                                min: 0,
                                max: Max::Unbounded,
                            },
                            kind: GroupKind::Sequence,
                            children: &[
                                Node::Segment(SegmentRef {
                                    id: "ORP_O10.7-RESPONSE.2-ORDER.3-TIMING.1-TQ1",
                                    position: 1,
                                    segment: &segment::tq1::TQ1,
                                    cardinality: Cardinality {
                                        min: 1,
                                        max: Max::Bounded(1),
                                    },
                                    status: Some(SegmentStatus::A),
                                }),
                                Node::Segment(SegmentRef {
                                    id: "ORP_O10.7-RESPONSE.2-ORDER.3-TIMING.2-TQ2",
                                    position: 2,
                                    segment: &segment::tq2::TQ2,
                                    cardinality: Cardinality {
                                        min: 0,
                                        max: Max::Unbounded,
                                    },
                                    status: Some(SegmentStatus::A),
                                }),
                            ],
                        }),
                        Node::Group(Group {
                            id: "ORP_O10.7-RESPONSE.2-ORDER.4-ORDER_DETAIL",
                            position: 4,
                            name: "ORDER_DETAIL",
                            cardinality: Cardinality {
                                min: 0,
                                max: Max::Bounded(1),
                            },
                            kind: GroupKind::Sequence,
                            children: &[
                                Node::Segment(SegmentRef {
                                    id: "ORP_O10.7-RESPONSE.2-ORDER.4-ORDER_DETAIL.1-RXO",
                                    position: 1,
                                    segment: &segment::rxo::RXO,
                                    cardinality: Cardinality {
                                        min: 1,
                                        max: Max::Bounded(1),
                                    },
                                    status: Some(SegmentStatus::A),
                                }),
                                Node::Segment(SegmentRef {
                                    id: "ORP_O10.7-RESPONSE.2-ORDER.4-ORDER_DETAIL.2-PRT",
                                    position: 2,
                                    segment: &segment::prt::PRT,
                                    cardinality: Cardinality {
                                        min: 0,
                                        max: Max::Unbounded,
                                    },
                                    status: Some(SegmentStatus::A),
                                }),
                                Node::Segment(SegmentRef {
                                    id: "ORP_O10.7-RESPONSE.2-ORDER.4-ORDER_DETAIL.3-NTE",
                                    position: 3,
                                    segment: &segment::nte::NTE,
                                    cardinality: Cardinality {
                                        min: 0,
                                        max: Max::Unbounded,
                                    },
                                    status: Some(SegmentStatus::A),
                                }),
                                Node::Segment(SegmentRef {
                                    id: "ORP_O10.7-RESPONSE.2-ORDER.4-ORDER_DETAIL.4-RXR",
                                    position: 4,
                                    segment: &segment::rxr::RXR,
                                    cardinality: Cardinality {
                                        min: 1,
                                        max: Max::Unbounded,
                                    },
                                    status: Some(SegmentStatus::A),
                                }),
                                Node::Group(Group {
                                    id: "ORP_O10.7-RESPONSE.2-ORDER.4-ORDER_DETAIL.5-COMPONENT",
                                    position: 5,
                                    name: "COMPONENT",
                                    cardinality: Cardinality {
                                        min: 0,
                                        max: Max::Unbounded,
                                    },
                                    kind: GroupKind::Sequence,
                                    children: &[
                                        Node::Segment(SegmentRef {
                                            id: "ORP_O10.7-RESPONSE.2-ORDER.4-ORDER_DETAIL.5-COMPONENT.1-RXC",
                                            position: 1,
                                            segment: &segment::rxc::RXC,
                                            cardinality: Cardinality {
                                                min: 1,
                                                max: Max::Bounded(1),
                                            },
                                            status: Some(SegmentStatus::A),
                                        }),
                                        Node::Segment(SegmentRef {
                                            id: "ORP_O10.7-RESPONSE.2-ORDER.4-ORDER_DETAIL.5-COMPONENT.2-NTE",
                                            position: 2,
                                            segment: &segment::nte::NTE,
                                            cardinality: Cardinality {
                                                min: 0,
                                                max: Max::Unbounded,
                                            },
                                            status: Some(SegmentStatus::A),
                                        }),
                                    ],
                                }),
                            ],
                        }),
                    ],
                }),
            ],
        }),
    ],
};
