// @generated by fhir-codegen from HL7/v2ig 3adcdbfff654ccbff5cd33aa34bd909a087e8e19 input/sourceOfTruth. DO NOT EDIT.
// Change the emitter (tools/fhir-codegen) and regenerate.
// SPDX-FileCopyrightText: Vernum Projecten B.V.
// SPDX-License-Identifier: Apache-2.0
//! The `ORU_R30-B` message structure.

use crate::model::{
    Cardinality, Group, GroupKind, Max, Node, SegmentRef, SegmentStatus, Structure,
};
use crate::segment;

/// The top-level nodes of [`ORU_R30_B`], one `static` so a structure with the same tree links to it.
pub static ORU_R30_B_NODES: [Node; 25] = [
    Node::Segment(SegmentRef {
        id: "ORU_R30-B.1-MSH",
        position: 1,
        segment: &segment::msh::MSH,
        cardinality: Cardinality {
            min: 1,
            max: Max::Bounded(1),
        },
        status: Some(SegmentStatus::A),
    }),
    Node::Segment(SegmentRef {
        id: "ORU_R30-B.2-ARV",
        position: 2,
        segment: &segment::arv::ARV,
        cardinality: Cardinality {
            min: 0,
            max: Max::Unbounded,
        },
        status: Some(SegmentStatus::A),
    }),
    Node::Segment(SegmentRef {
        id: "ORU_R30-B.3-SFT",
        position: 3,
        segment: &segment::sft::SFT,
        cardinality: Cardinality {
            min: 0,
            max: Max::Unbounded,
        },
        status: Some(SegmentStatus::A),
    }),
    Node::Segment(SegmentRef {
        id: "ORU_R30-B.4-UAC",
        position: 4,
        segment: &segment::uac::UAC,
        cardinality: Cardinality {
            min: 0,
            max: Max::Bounded(1),
        },
        status: Some(SegmentStatus::A),
    }),
    Node::Segment(SegmentRef {
        id: "ORU_R30-B.5-PID",
        position: 5,
        segment: &segment::pid::PID,
        cardinality: Cardinality {
            min: 1,
            max: Max::Bounded(1),
        },
        status: Some(SegmentStatus::A),
    }),
    Node::Segment(SegmentRef {
        id: "ORU_R30-B.6-PD1",
        position: 6,
        segment: &segment::pd1::PD1,
        cardinality: Cardinality {
            min: 0,
            max: Max::Bounded(1),
        },
        status: Some(SegmentStatus::A),
    }),
    Node::Segment(SegmentRef {
        id: "ORU_R30-B.7-GSP",
        position: 7,
        segment: &segment::gsp::GSP,
        cardinality: Cardinality {
            min: 0,
            max: Max::Unbounded,
        },
        status: Some(SegmentStatus::A),
    }),
    Node::Segment(SegmentRef {
        id: "ORU_R30-B.8-GSR",
        position: 8,
        segment: &segment::gsr::GSR,
        cardinality: Cardinality {
            min: 0,
            max: Max::Unbounded,
        },
        status: Some(SegmentStatus::A),
    }),
    Node::Segment(SegmentRef {
        id: "ORU_R30-B.9-GSC",
        position: 9,
        segment: &segment::gsc::GSC,
        cardinality: Cardinality {
            min: 0,
            max: Max::Unbounded,
        },
        status: Some(SegmentStatus::A),
    }),
    Node::Segment(SegmentRef {
        id: "ORU_R30-B.10-PRT",
        position: 10,
        segment: &segment::prt::PRT,
        cardinality: Cardinality {
            min: 0,
            max: Max::Unbounded,
        },
        status: Some(SegmentStatus::A),
    }),
    Node::Segment(SegmentRef {
        id: "ORU_R30-B.11-OH1",
        position: 11,
        segment: &segment::oh1::OH1,
        cardinality: Cardinality {
            min: 0,
            max: Max::Unbounded,
        },
        status: Some(SegmentStatus::A),
    }),
    Node::Segment(SegmentRef {
        id: "ORU_R30-B.12-OH2",
        position: 12,
        segment: &segment::oh2::OH2,
        cardinality: Cardinality {
            min: 0,
            max: Max::Unbounded,
        },
        status: Some(SegmentStatus::A),
    }),
    Node::Segment(SegmentRef {
        id: "ORU_R30-B.13-OH3",
        position: 13,
        segment: &segment::oh3::OH3,
        cardinality: Cardinality {
            min: 0,
            max: Max::Bounded(1),
        },
        status: Some(SegmentStatus::A),
    }),
    Node::Segment(SegmentRef {
        id: "ORU_R30-B.14-OH4",
        position: 14,
        segment: &segment::oh4::OH4,
        cardinality: Cardinality {
            min: 0,
            max: Max::Unbounded,
        },
        status: Some(SegmentStatus::A),
    }),
    Node::Segment(SegmentRef {
        id: "ORU_R30-B.15-ARV",
        position: 15,
        segment: &segment::arv::ARV,
        cardinality: Cardinality {
            min: 0,
            max: Max::Unbounded,
        },
        status: Some(SegmentStatus::B),
    }),
    Node::Group(Group {
        id: "ORU_R30-B.16-PATIENT_OBSERVATION",
        position: 16,
        name: "PATIENT_OBSERVATION",
        cardinality: Cardinality {
            min: 0,
            max: Max::Unbounded,
        },
        kind: GroupKind::Sequence,
        children: &[
            Node::Segment(SegmentRef {
                id: "ORU_R30-B.16-PATIENT_OBSERVATION.1-OBX",
                position: 1,
                segment: &segment::obx::OBX,
                cardinality: Cardinality {
                    min: 1,
                    max: Max::Bounded(1),
                },
                status: Some(SegmentStatus::A),
            }),
            Node::Segment(SegmentRef {
                id: "ORU_R30-B.16-PATIENT_OBSERVATION.2-PRT",
                position: 2,
                segment: &segment::prt::PRT,
                cardinality: Cardinality {
                    min: 0,
                    max: Max::Unbounded,
                },
                status: Some(SegmentStatus::A),
            }),
        ],
    }),
    Node::Group(Group {
        id: "ORU_R30-B.17-VISIT",
        position: 17,
        name: "VISIT",
        cardinality: Cardinality {
            min: 0,
            max: Max::Bounded(1),
        },
        kind: GroupKind::Sequence,
        children: &[
            Node::Segment(SegmentRef {
                id: "ORU_R30-B.17-VISIT.1-PV1",
                position: 1,
                segment: &segment::pv1::PV1,
                cardinality: Cardinality {
                    min: 1,
                    max: Max::Bounded(1),
                },
                status: Some(SegmentStatus::A),
            }),
            Node::Segment(SegmentRef {
                id: "ORU_R30-B.17-VISIT.2-PV2",
                position: 2,
                segment: &segment::pv2::PV2,
                cardinality: Cardinality {
                    min: 0,
                    max: Max::Bounded(1),
                },
                status: Some(SegmentStatus::A),
            }),
            Node::Segment(SegmentRef {
                id: "ORU_R30-B.17-VISIT.3-PRT",
                position: 3,
                segment: &segment::prt::PRT,
                cardinality: Cardinality {
                    min: 0,
                    max: Max::Unbounded,
                },
                status: Some(SegmentStatus::A),
            }),
        ],
    }),
    Node::Segment(SegmentRef {
        id: "ORU_R30-B.18-ORC",
        position: 18,
        segment: &segment::orc::ORC,
        cardinality: Cardinality {
            min: 1,
            max: Max::Bounded(1),
        },
        status: Some(SegmentStatus::A),
    }),
    Node::Segment(SegmentRef {
        id: "ORU_R30-B.19-PRT",
        position: 19,
        segment: &segment::prt::PRT,
        cardinality: Cardinality {
            min: 0,
            max: Max::Unbounded,
        },
        status: Some(SegmentStatus::A),
    }),
    Node::Segment(SegmentRef {
        id: "ORU_R30-B.20-OBR",
        position: 20,
        segment: &segment::obr::OBR,
        cardinality: Cardinality {
            min: 1,
            max: Max::Bounded(1),
        },
        status: Some(SegmentStatus::A),
    }),
    Node::Segment(SegmentRef {
        id: "ORU_R30-B.21-NTE",
        position: 21,
        segment: &segment::nte::NTE,
        cardinality: Cardinality {
            min: 0,
            max: Max::Unbounded,
        },
        status: Some(SegmentStatus::A),
    }),
    Node::Segment(SegmentRef {
        id: "ORU_R30-B.22-PRT",
        position: 22,
        segment: &segment::prt::PRT,
        cardinality: Cardinality {
            min: 0,
            max: Max::Unbounded,
        },
        status: Some(SegmentStatus::A),
    }),
    Node::Group(Group {
        id: "ORU_R30-B.23-TIMING_QTY",
        position: 23,
        name: "TIMING_QTY",
        cardinality: Cardinality {
            min: 0,
            max: Max::Unbounded,
        },
        kind: GroupKind::Sequence,
        children: &[
            Node::Segment(SegmentRef {
                id: "ORU_R30-B.23-TIMING_QTY.1-TQ1",
                position: 1,
                segment: &segment::tq1::TQ1,
                cardinality: Cardinality {
                    min: 1,
                    max: Max::Bounded(1),
                },
                status: Some(SegmentStatus::A),
            }),
            Node::Segment(SegmentRef {
                id: "ORU_R30-B.23-TIMING_QTY.2-TQ2",
                position: 2,
                segment: &segment::tq2::TQ2,
                cardinality: Cardinality {
                    min: 0,
                    max: Max::Unbounded,
                },
                status: Some(SegmentStatus::A),
            }),
        ],
    }),
    Node::Group(Group {
        id: "ORU_R30-B.24-OBSERVATION",
        position: 24,
        name: "OBSERVATION",
        cardinality: Cardinality {
            min: 1,
            max: Max::Unbounded,
        },
        kind: GroupKind::Sequence,
        children: &[
            Node::Segment(SegmentRef {
                id: "ORU_R30-B.24-OBSERVATION.1-OBX",
                position: 1,
                segment: &segment::obx::OBX,
                cardinality: Cardinality {
                    min: 1,
                    max: Max::Bounded(1),
                },
                status: Some(SegmentStatus::A),
            }),
            Node::Segment(SegmentRef {
                id: "ORU_R30-B.24-OBSERVATION.2-PRT",
                position: 2,
                segment: &segment::prt::PRT,
                cardinality: Cardinality {
                    min: 0,
                    max: Max::Unbounded,
                },
                status: Some(SegmentStatus::A),
            }),
            Node::Segment(SegmentRef {
                id: "ORU_R30-B.24-OBSERVATION.3-NTE",
                position: 3,
                segment: &segment::nte::NTE,
                cardinality: Cardinality {
                    min: 0,
                    max: Max::Unbounded,
                },
                status: Some(SegmentStatus::A),
            }),
        ],
    }),
    Node::Group(Group {
        id: "ORU_R30-B.25-DEVICE",
        position: 25,
        name: "DEVICE",
        cardinality: Cardinality {
            min: 0,
            max: Max::Unbounded,
        },
        kind: GroupKind::Sequence,
        children: &[
            Node::Segment(SegmentRef {
                id: "ORU_R30-B.25-DEVICE.1-DEV",
                position: 1,
                segment: &segment::dev::DEV,
                cardinality: Cardinality {
                    min: 1,
                    max: Max::Bounded(1),
                },
                status: Some(SegmentStatus::A),
            }),
            Node::Segment(SegmentRef {
                id: "ORU_R30-B.25-DEVICE.2-OBX",
                position: 2,
                segment: &segment::obx::OBX,
                cardinality: Cardinality {
                    min: 0,
                    max: Max::Unbounded,
                },
                status: Some(SegmentStatus::A),
            }),
        ],
    }),
];

/// The `ORU_R30-B` message structure definition, `http://hl7.org/v2/StructureDefinition/ORU_R30-B`.
pub static ORU_R30_B: Structure = Structure {
    id: "ORU_R30-B",
    url: Some("http://hl7.org/v2/StructureDefinition/ORU_R30-B"),
    version: "2.9.1",
    withdrawn_as_of: None,
    nodes: &ORU_R30_B_NODES,
};
