// @generated by fhir-codegen from HL7/v2ig 3adcdbfff654ccbff5cd33aa34bd909a087e8e19 input/sourceOfTruth. DO NOT EDIT.
// Change the emitter (tools/fhir-codegen) and regenerate.
// SPDX-FileCopyrightText: Vernum Projecten B.V.
// SPDX-License-Identifier: Apache-2.0
//! The `PMU_B01-A` message structure.

use crate::model::{
    Cardinality, Group, GroupKind, Max, Node, SegmentRef, SegmentStatus, Structure,
};
use crate::segment;

/// The `PMU_B01-A` message structure definition, `http://hl7.org/v2/StructureDefinition/PMU_B01-A`.
pub static PMU_B01_A: Structure = Structure {
    id: "PMU_B01-A",
    url: Some("http://hl7.org/v2/StructureDefinition/PMU_B01-A"),
    version: "2.9.1",
    withdrawn_as_of: None,
    nodes: &[
        Node::Segment(SegmentRef {
            id: "PMU_B01-A.1-MSH",
            position: 1,
            segment: &segment::msh::MSH,
            cardinality: Cardinality {
                min: 1,
                max: Max::Bounded(1),
            },
            status: Some(SegmentStatus::A),
        }),
        Node::Segment(SegmentRef {
            id: "PMU_B01-A.2-SFT",
            position: 2,
            segment: &segment::sft::SFT,
            cardinality: Cardinality {
                min: 0,
                max: Max::Unbounded,
            },
            status: Some(SegmentStatus::A),
        }),
        Node::Segment(SegmentRef {
            id: "PMU_B01-A.3-UAC",
            position: 3,
            segment: &segment::uac::UAC,
            cardinality: Cardinality {
                min: 0,
                max: Max::Bounded(1),
            },
            status: Some(SegmentStatus::A),
        }),
        Node::Segment(SegmentRef {
            id: "PMU_B01-A.4-EVN",
            position: 4,
            segment: &segment::evn::EVN,
            cardinality: Cardinality {
                min: 1,
                max: Max::Bounded(1),
            },
            status: Some(SegmentStatus::A),
        }),
        Node::Segment(SegmentRef {
            id: "PMU_B01-A.5-STF",
            position: 5,
            segment: &segment::stf::STF,
            cardinality: Cardinality {
                min: 1,
                max: Max::Bounded(1),
            },
            status: Some(SegmentStatus::A),
        }),
        Node::Segment(SegmentRef {
            id: "PMU_B01-A.6-GSP",
            position: 6,
            segment: &segment::gsp::GSP,
            cardinality: Cardinality {
                min: 0,
                max: Max::Unbounded,
            },
            status: Some(SegmentStatus::A),
        }),
        Node::Segment(SegmentRef {
            id: "PMU_B01-A.7-GSR",
            position: 7,
            segment: &segment::gsr::GSR,
            cardinality: Cardinality {
                min: 0,
                max: Max::Unbounded,
            },
            status: Some(SegmentStatus::A),
        }),
        Node::Segment(SegmentRef {
            id: "PMU_B01-A.8-PRA",
            position: 8,
            segment: &segment::pra::PRA,
            cardinality: Cardinality {
                min: 0,
                max: Max::Unbounded,
            },
            status: Some(SegmentStatus::A),
        }),
        Node::Segment(SegmentRef {
            id: "PMU_B01-A.9-ORG",
            position: 9,
            segment: &segment::org::ORG,
            cardinality: Cardinality {
                min: 0,
                max: Max::Unbounded,
            },
            status: Some(SegmentStatus::A),
        }),
        Node::Segment(SegmentRef {
            id: "PMU_B01-A.10-AFF",
            position: 10,
            segment: &segment::aff::AFF,
            cardinality: Cardinality {
                min: 0,
                max: Max::Unbounded,
            },
            status: Some(SegmentStatus::A),
        }),
        Node::Segment(SegmentRef {
            id: "PMU_B01-A.11-LAN",
            position: 11,
            segment: &segment::lan::LAN,
            cardinality: Cardinality {
                min: 0,
                max: Max::Unbounded,
            },
            status: Some(SegmentStatus::A),
        }),
        Node::Segment(SegmentRef {
            id: "PMU_B01-A.12-EDU",
            position: 12,
            segment: &segment::edu::EDU,
            cardinality: Cardinality {
                min: 0,
                max: Max::Unbounded,
            },
            status: Some(SegmentStatus::A),
        }),
        Node::Segment(SegmentRef {
            id: "PMU_B01-A.13-CER",
            position: 13,
            segment: &segment::cer::CER,
            cardinality: Cardinality {
                min: 0,
                max: Max::Unbounded,
            },
            status: Some(SegmentStatus::A),
        }),
        Node::Group(Group {
            id: "PMU_B01-A.14-NEXT_OF_KIN",
            position: 14,
            name: "NEXT_OF_KIN",
            cardinality: Cardinality {
                min: 0,
                max: Max::Unbounded,
            },
            kind: GroupKind::Sequence,
            children: &[
                Node::Segment(SegmentRef {
                    id: "PMU_B01-A.14-NEXT_OF_KIN.1-NK1",
                    position: 1,
                    segment: &segment::nk1::NK1,
                    cardinality: Cardinality {
                        min: 0,
                        max: Max::Unbounded,
                    },
                    status: Some(SegmentStatus::A),
                }),
                Node::Segment(SegmentRef {
                    id: "PMU_B01-A.14-NEXT_OF_KIN.2-GSP",
                    position: 2,
                    segment: &segment::gsp::GSP,
                    cardinality: Cardinality {
                        min: 0,
                        max: Max::Unbounded,
                    },
                    status: Some(SegmentStatus::A),
                }),
                Node::Segment(SegmentRef {
                    id: "PMU_B01-A.14-NEXT_OF_KIN.3-GSR",
                    position: 3,
                    segment: &segment::gsr::GSR,
                    cardinality: Cardinality {
                        min: 0,
                        max: Max::Unbounded,
                    },
                    status: Some(SegmentStatus::A),
                }),
            ],
        }),
        Node::Segment(SegmentRef {
            id: "PMU_B01-A.15-PRT",
            position: 15,
            segment: &segment::prt::PRT,
            cardinality: Cardinality {
                min: 0,
                max: Max::Unbounded,
            },
            status: Some(SegmentStatus::A),
        }),
        Node::Segment(SegmentRef {
            id: "PMU_B01-A.16-ROL",
            position: 16,
            segment: &segment::rol::ROL,
            cardinality: Cardinality {
                min: 0,
                max: Max::Unbounded,
            },
            status: Some(SegmentStatus::D),
        }),
    ],
};
