// @generated by fhir-codegen from usnistgov/igamt-hl7Tools-service 83322dffdac18cb129a1bd80149f5439cf5686fd src/main/resources/hl7db. DO NOT EDIT.
// Change the emitter (tools/fhir-codegen) and regenerate.
// SPDX-FileCopyrightText: Vernum Projecten B.V.
// SPDX-License-Identifier: Apache-2.0
//! The `MRG` segment: Merge Patient Information.

use crate::model::{Cardinality, DataTypeRef, Field, Length, Max, Optionality, Segment, Table};

/// The `MRG` segment of the 2.8 tables.
pub static MRG: Segment = Segment {
    id: "MRG",
    url: None,
    name: "Merge Patient Information",
    fields: &[
        Field {
            id: "MRG.1",
            position: 1,
            name: "Prior Patient Identifier List",
            data_type: Some(DataTypeRef::Legacy(&crate::legacy::v2_8::data_type::CX)),
            cardinality: Cardinality {
                min: 1,
                max: Max::Unbounded,
            },
            optionality: Optionality::R,
            length: Some(Length {
                min: 0,
                max: Some(0),
            }),
            conformance_length: None,
            table: Some(Table {
                id: "0061",
                value_set: "http://terminology.hl7.org/ValueSet/v2-0061",
            }),
            standards_status: None,
        },
        Field {
            id: "MRG.2",
            position: 2,
            name: "Prior Alternate Patient ID",
            data_type: None,
            cardinality: Cardinality {
                min: 0,
                max: Max::Bounded(1),
            },
            optionality: Optionality::X,
            length: Some(Length {
                min: 0,
                max: Some(0),
            }),
            conformance_length: None,
            table: None,
            standards_status: None,
        },
        Field {
            id: "MRG.3",
            position: 3,
            name: "Prior Patient Account Number",
            data_type: Some(DataTypeRef::Legacy(&crate::legacy::v2_8::data_type::CX)),
            cardinality: Cardinality {
                min: 0,
                max: Max::Bounded(1),
            },
            optionality: Optionality::O,
            length: Some(Length {
                min: 0,
                max: Some(0),
            }),
            conformance_length: None,
            table: Some(Table {
                id: "0061",
                value_set: "http://terminology.hl7.org/ValueSet/v2-0061",
            }),
            standards_status: None,
        },
        Field {
            id: "MRG.4",
            position: 4,
            name: "Prior Patient ID",
            data_type: None,
            cardinality: Cardinality {
                min: 0,
                max: Max::Bounded(1),
            },
            optionality: Optionality::X,
            length: Some(Length {
                min: 0,
                max: Some(0),
            }),
            conformance_length: None,
            table: None,
            standards_status: None,
        },
        Field {
            id: "MRG.5",
            position: 5,
            name: "Prior Visit Number",
            data_type: Some(DataTypeRef::Legacy(&crate::legacy::v2_8::data_type::CX)),
            cardinality: Cardinality {
                min: 0,
                max: Max::Bounded(1),
            },
            optionality: Optionality::O,
            length: Some(Length {
                min: 0,
                max: Some(0),
            }),
            conformance_length: None,
            table: Some(Table {
                id: "0061",
                value_set: "http://terminology.hl7.org/ValueSet/v2-0061",
            }),
            standards_status: None,
        },
        Field {
            id: "MRG.6",
            position: 6,
            name: "Prior Alternate Visit ID",
            data_type: Some(DataTypeRef::Legacy(&crate::legacy::v2_8::data_type::CX)),
            cardinality: Cardinality {
                min: 0,
                max: Max::Unbounded,
            },
            optionality: Optionality::O,
            length: Some(Length {
                min: 0,
                max: Some(0),
            }),
            conformance_length: None,
            table: Some(Table {
                id: "0061",
                value_set: "http://terminology.hl7.org/ValueSet/v2-0061",
            }),
            standards_status: None,
        },
        Field {
            id: "MRG.7",
            position: 7,
            name: "Prior Patient Name",
            data_type: Some(DataTypeRef::Legacy(&crate::legacy::v2_8::data_type::XPN)),
            cardinality: Cardinality {
                min: 0,
                max: Max::Unbounded,
            },
            optionality: Optionality::O,
            length: Some(Length {
                min: 0,
                max: Some(0),
            }),
            conformance_length: None,
            table: Some(Table {
                id: "0200",
                value_set: "http://terminology.hl7.org/ValueSet/v2-0200",
            }),
            standards_status: None,
        },
    ],
};
