// @generated by fhir-codegen from usnistgov/igamt-hl7Tools-service 83322dffdac18cb129a1bd80149f5439cf5686fd src/main/resources/hl7db. DO NOT EDIT.
// Change the emitter (tools/fhir-codegen) and regenerate.
// SPDX-FileCopyrightText: Vernum Projecten B.V.
// SPDX-License-Identifier: Apache-2.0
//! The `QBP_Q13` message structure of the 2.5 tables.

use crate::model::{Cardinality, Max, Node, SegmentRef, Structure};

/// The top-level nodes of [`QBP_Q13`], one `static` so a structure with the same tree links to it.
pub static QBP_Q13_NODES: [Node; 6] = [
    Node::Segment(SegmentRef {
        id: "QBP_Q13.1-MSH",
        position: 1,
        segment: &crate::legacy::v2_5::segment::msh::MSH,
        cardinality: Cardinality {
            min: 1,
            max: Max::Bounded(1),
        },
        status: None,
    }),
    Node::Segment(SegmentRef {
        id: "QBP_Q13.2-SFT",
        position: 2,
        segment: &crate::legacy::v2_5::segment::sft::SFT,
        cardinality: Cardinality {
            min: 0,
            max: Max::Unbounded,
        },
        status: None,
    }),
    Node::Segment(SegmentRef {
        id: "QBP_Q13.3-QPD",
        position: 3,
        segment: &crate::legacy::v2_5::segment::qpd::QPD,
        cardinality: Cardinality {
            min: 1,
            max: Max::Bounded(1),
        },
        status: None,
    }),
    Node::Segment(SegmentRef {
        id: "QBP_Q13.4-RDF",
        position: 4,
        segment: &crate::segment::rdf::RDF,
        cardinality: Cardinality {
            min: 0,
            max: Max::Bounded(1),
        },
        status: None,
    }),
    Node::Segment(SegmentRef {
        id: "QBP_Q13.5-RCP",
        position: 5,
        segment: &crate::legacy::v2_5::segment::rcp::RCP,
        cardinality: Cardinality {
            min: 1,
            max: Max::Bounded(1),
        },
        status: None,
    }),
    Node::Segment(SegmentRef {
        id: "QBP_Q13.6-DSC",
        position: 6,
        segment: &crate::segment::dsc::DSC,
        cardinality: Cardinality {
            min: 0,
            max: Max::Bounded(1),
        },
        status: None,
    }),
];

/// The `QBP_Q13` message structure of the 2.5 tables.
pub static QBP_Q13: Structure = Structure {
    id: "QBP_Q13",
    url: None,
    version: "2.5",
    withdrawn_as_of: None,
    nodes: &QBP_Q13_NODES,
};
