// @generated by fhir-codegen from usnistgov/igamt-hl7Tools-service 83322dffdac18cb129a1bd80149f5439cf5686fd src/main/resources/hl7db. DO NOT EDIT.
// Change the emitter (tools/fhir-codegen) and regenerate.
// SPDX-FileCopyrightText: Vernum Projecten B.V.
// SPDX-License-Identifier: Apache-2.0
//! The `SUR_P09` message structure of the 2.6 tables, withdrawn as of 2.7.

use crate::model::{Cardinality, Group, GroupKind, Max, Node, SegmentRef, Structure};

/// The `SUR_P09` message structure of the 2.6 tables, withdrawn as of 2.7.
pub static SUR_P09: Structure = Structure {
    id: "SUR_P09",
    url: None,
    version: "2.6",
    withdrawn_as_of: Some("2.7"),
    nodes: &[
        Node::Segment(SegmentRef {
            id: "SUR_P09.1-MSH",
            position: 1,
            segment: &crate::legacy::v2_6::segment::msh::MSH,
            cardinality: Cardinality {
                min: 1,
                max: Max::Bounded(1),
            },
            status: None,
        }),
        Node::Group(Group {
            id: "SUR_P09.2-FACILITY",
            position: 2,
            name: "FACILITY",
            cardinality: Cardinality {
                min: 1,
                max: Max::Unbounded,
            },
            kind: GroupKind::Sequence,
            children: &[
                Node::Segment(SegmentRef {
                    id: "SUR_P09.2-FACILITY.1-FAC",
                    position: 1,
                    segment: &crate::segment::fac::FAC,
                    cardinality: Cardinality {
                        min: 1,
                        max: Max::Bounded(1),
                    },
                    status: None,
                }),
                Node::Group(Group {
                    id: "SUR_P09.2-FACILITY.2-PRODUCT",
                    position: 2,
                    name: "PRODUCT",
                    cardinality: Cardinality {
                        min: 1,
                        max: Max::Unbounded,
                    },
                    kind: GroupKind::Sequence,
                    children: &[
                        Node::Segment(SegmentRef {
                            id: "SUR_P09.2-FACILITY.2-PRODUCT.1-PSH",
                            position: 1,
                            segment: &crate::segment::psh::PSH,
                            cardinality: Cardinality {
                                min: 1,
                                max: Max::Bounded(1),
                            },
                            status: None,
                        }),
                        Node::Segment(SegmentRef {
                            id: "SUR_P09.2-FACILITY.2-PRODUCT.2-PDC",
                            position: 2,
                            segment: &crate::legacy::v2_6::segment::pdc::PDC,
                            cardinality: Cardinality {
                                min: 1,
                                max: Max::Bounded(1),
                            },
                            status: None,
                        }),
                    ],
                }),
                Node::Segment(SegmentRef {
                    id: "SUR_P09.2-FACILITY.3-PSH",
                    position: 3,
                    segment: &crate::segment::psh::PSH,
                    cardinality: Cardinality {
                        min: 1,
                        max: Max::Bounded(1),
                    },
                    status: None,
                }),
                Node::Group(Group {
                    id: "SUR_P09.2-FACILITY.4-FACILITY_DETAIL",
                    position: 4,
                    name: "FACILITY_DETAIL",
                    cardinality: Cardinality {
                        min: 1,
                        max: Max::Unbounded,
                    },
                    kind: GroupKind::Sequence,
                    children: &[
                        Node::Segment(SegmentRef {
                            id: "SUR_P09.2-FACILITY.4-FACILITY_DETAIL.1-FAC",
                            position: 1,
                            segment: &crate::segment::fac::FAC,
                            cardinality: Cardinality {
                                min: 1,
                                max: Max::Bounded(1),
                            },
                            status: None,
                        }),
                        Node::Segment(SegmentRef {
                            id: "SUR_P09.2-FACILITY.4-FACILITY_DETAIL.2-PDC",
                            position: 2,
                            segment: &crate::legacy::v2_6::segment::pdc::PDC,
                            cardinality: Cardinality {
                                min: 1,
                                max: Max::Bounded(1),
                            },
                            status: None,
                        }),
                        Node::Segment(SegmentRef {
                            id: "SUR_P09.2-FACILITY.4-FACILITY_DETAIL.3-NTE",
                            position: 3,
                            segment: &crate::legacy::v2_6::segment::nte::NTE,
                            cardinality: Cardinality {
                                min: 1,
                                max: Max::Bounded(1),
                            },
                            status: None,
                        }),
                    ],
                }),
                Node::Segment(SegmentRef {
                    id: "SUR_P09.2-FACILITY.5-ED",
                    position: 5,
                    segment: &crate::legacy::v2_6::segment::ed::ED,
                    cardinality: Cardinality {
                        min: 1,
                        max: Max::Bounded(1),
                    },
                    status: None,
                }),
            ],
        }),
    ],
};
